{
  "hash": "75346c7b0ca0f0959a9fd17f7e7dc56d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Analysis of Variance\"\nsubtitle: \"Inference comparing multiple population means\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    mermaid:\n      theme: neutral\nexecute: \n  echo: false\n  warning: false\n  message: false\n---\n\n::: {.cell}\n\n:::\n\n\n\n## Today's agenda\n\n1. \\[lecture\\] inference comparing several population means\n2. \\[lab\\] fitting ANOVA models in R\n\n## More than two means?\n\n::: columns\n::: column\nYou previously considered this data on chick weights at 20 days of age by diet:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week7-anova_files/figure-revealjs/unnamed-chunk-2-1.png){width=384}\n:::\n:::\n\n\n:::\n\n::: column\nHere we have *four means* to compare rather than just two. \n\n\n::: {.cell}\n::: {.cell-output-display}\n\n-----------------------------------\n diet   mean     se      sd     n  \n------ ------- ------- ------- ----\n  1     170.4   13.45   55.44   17 \n\n  2     205.6   22.22   70.25   10 \n\n  3     258.9   20.63   65.24   10 \n\n  4     233.9   12.52   37.57   9  \n-----------------------------------\n\n\n:::\n:::\n\n\n:::\n:::\n\n> Does mean weight at 20 days differ by diet? How do you test this?\n\n## Hypotheses for a difference in means\n\nLet $\\mu_i = \\text{mean weight on diet } i = 1, 2, 3, 4$.\n\nThe hypothesis that there are **no differences** in means by diet is:\n\n$$\nH_0: \\mu_1 = \\mu_2 = \\mu_3 = \\mu_4 \\quad (\\text{no difference in means})\n$$\n\nThe alternative, if this is false, is that there is **at least one difference**:\n\n$$\nH_A: \\mu_i \\neq \\mu_j \\quad (\\text{at least one difference})\n$$\n\n## How much difference is enough?\n\nHere are two made-up examples of four sample means.\n\n::: columns\n::: {.column width=\"70%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week7-anova_files/figure-revealjs/unnamed-chunk-4-1.png){width=768}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n\n> Why does it look like there's a difference at right but not at left?\n\n:::\n:::\n\nThink about the $t$-test: we say there's a difference if $T = \\frac{\\text{estimate} - \\text{hypothesis}}{\\text{variability}}$ is large.\n\nSame idea here: we see differences if they are big *relative to the variability in estimates*.\n\n## Partitioning variation\n\n> Partitioning variation into two or more components is called \"analysis of variance\"\n\n::: columns\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week7-anova_files/figure-revealjs/unnamed-chunk-5-1.png){width=480}\n:::\n:::\n\n:::\n\n::: {.column width=\"55%\"}\nFor the chick data, two sources of variability:\n\n-   [group]{style=\"color:red\"} variability between diets\n\n-   [error]{style=\"color:blue\"} variability among chicks\n\nThe analysis of variance (ANOVA) model:\n\n$$\\color{grey}{\\text{total variation}} = \\color{red}{\\text{group variation}} + \\color{blue}{\\text{error variation}}$$\n:::\n:::\n\n\nWe'll base the test on the ratio $F = \\frac{\\color{red}{\\text{group variation}}}{\\color{blue}{\\text{error variation}}}$.\n\n\n## The $F$ statistic: a variance ratio\n\n> The $F$ statistic measures variability attributable to group differences relative to variability attributable to individual differences.\n\n\n::: columns\n::: column\nNotation:\n\n-   $\\bar{x}$: \"grand\" mean of all observations\n-   $\\bar{x}_i$: mean of observations in group $i$\n-   $s_i$: SD of observations in group $i$\n-   $k$ groups\n-   $n$ total observations\n-   $n_i$ observations per group\n\n:::\n\n::: column\nMeasures of variability:\n\n$$\\color{red}{MSG} = \\frac{1}{k - 1}\\sum_i n_i(\\bar{x}_i - \\bar{x})^2 \\quad(\\color{red}{\\text{group}})$$ \n$$\\color{blue}{MSE} = \\frac{1}{n - k}\\sum_i (n_i - 1)s_i^2 \\quad(\\color{blue}{\\text{error}})$$ Ratio:\n\n$$F = \\frac{\\color{red}{MSG}}{\\color{blue}{MSE}} \\quad\\left(\\frac{\\color{red}{\\text{group variation}}}{\\color{blue}{\\text{error variation}}}\\right)$$\n:::\n:::\n\n## Sampling distribution for $F$\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\nIf the data satisfy these conditions:\n\n1. the distribution of values is symmetric and unimodal within each group\n2. the variability (standard deviation) is roughly the same across groups\n\nThen the $F$ statistic has a sampling distribution well-approximated by an $F_{k - 1, n - k}$ model.\n\n- numerator degrees of freedom $k - 1$\n- denominator degrees of freedom $n - k$\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![$F$ models for several different numerator degrees of freedom $k - 1$ with fixed $n = 30$.](week7-anova_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n:::\n\n:::\n\n## $p$-values for the $F$ test\n\n::: {.columns}\n\n::: {.column}\nTo test the hypotheses:\n\n$$\n\\begin{cases}\nH_0: &\\mu_1 = \\mu_2 = \\mu_3 = \\mu_4 \\\\\nH_0: &\\mu_i \\neq \\mu_j \\quad\\text{for some}\\quad i \\neq j\n\\end{cases}\n$$\nCalculate the $F$ statistic:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ingredients of mean squares\nk <- nrow(chicks.summary)\nn <- nrow(chicks)\nn.i <- chicks.summary$n\nxbar.i <- chicks.summary$mean\ns.i <- chicks.summary$sd\nxbar <- mean(chicks$weight)\n\n# mean squares\nmsg <- sum(n.i*(xbar.i - xbar)^2)/(k - 1)\nmse <- sum((n.i - 1)*s.i^2)/(n - k)\n\n# f statistic\nfstat <- msg/mse\nfstat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.463598\n```\n\n\n:::\n:::\n\n\nAnd reject $H_0$ when $F$ is large. \n:::\n\n::: {.column}\n\nFor a significance level $\\alpha$ test, reject $H_0$ when $\\underbrace{P(F > F_\\text{obs})}_\\text{p-value} < \\alpha$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week7-anova_files/figure-revealjs/unnamed-chunk-8-1.png){width=480}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npf(fstat, 4 - 1, 46 - 4, lower.tail = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.002909054\n```\n\n\n:::\n:::\n\n:::\n\n:::\n\n## Interpreting $F$ statistics and $p$-values\n\n::: {.columns}\n\n::: {.column}\n$$\n\\begin{cases}\nH_0: &\\mu_1 = \\mu_2 = \\mu_3 = \\mu_4 \\\\\nH_0: &\\mu_i \\neq \\mu_j \\quad\\text{for some}\\quad i \\neq j\n\\end{cases}\n$$\n\n$F = \\frac{\\color{red}{\\text{group variation}}}{\\color{blue}{\\text{error variation}}} = \\frac{MSG}{MSE} = 5.4636$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week7-anova_files/figure-revealjs/unnamed-chunk-10-1.png){width=480}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npf(fstat, 4 - 1, 46 - 4, lower.tail = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.002909054\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n\n> *F = 5.4636* means the proportion of variation in weight attributable to diets is 5.46 times greater than the proportion of variation attributable to chicks.\n\nThe statistical significance of this result is measured by the $p$-value:\n\n- if there is in fact no difference in means, then only 0.29% of samples (*i.e.*, 2 in 1000) would produce at least as much diet-to-diet variability as we observed.\n\n- so in this case we reject $H_0$ at the 1% level\n\n:::\n\n:::\n\n## ANOVA in R\n\nThe `aov(...)` function fits ANOVA models using a formula/dataframe specification:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit anova model\nfit <- aov(weight ~ diet, data = chicks)\n\n# generate table\nsummary(fit)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n------------------------------------------------------------\n    &nbsp;       Df   Sum Sq   Mean Sq   F value    Pr(>F)  \n--------------- ---- -------- --------- --------- ----------\n   **diet**      3    55881     18627     5.464    0.002909 \n\n **Residuals**   42   143190    3409       NA         NA    \n------------------------------------------------------------\n\nTable: Analysis of Variance Model\n\n\n:::\n:::\n\n\nThe typical style for interpretation closely follows that of previous inferences for the mean:\n\n> The data provide strong evidence of an effect of diet on mean weight (*F = 5.464* on *3* and *42* df, *p = 0.0029*).\n\n## Analysis of variance table\n\nThe results of an analysis of variance are traditionally displayed in a table.\n\nSource | degrees of freedom | Sum of squares | Mean square | F statistic | *p*-value\n---|---|---|---|---|---\nGroup | $k - 1$ | SSG | $MSG = \\frac{SSG}{k - 1}$ | $\\frac{MSG}{MSE}$  | $P(F > F_\\text{obs})$\nError | $n - k$ | SSE | $MSE = \\frac{SSE}{n - k}$ | \n\n- the sum of square terms are 'raw' measures of variability\n- the mean square terms are averages adjusted for the amount of data available to estimate variability due to each source\n\nFormally, the ANOVA model says $(n - 1)s^2 = SSG + SSE$.\n\n## Checking assumptions\n\n::: {.columns}\n\n::: {.column}\nThe ANOVA test assumes:\n\n1. the distribution of values is symmetric and unimodal within each group\n2. the variability (standard deviation) is roughly the same across groups\n\nTo check these assumptions:\n\n- compare group standard deviations for similarity\n- visually inspect distributions within each group for approximate symmetry\n\nSimilar to the $t$ test, greater departures from these assumptions are allowable for larger sample sizes.\n:::\n\n::: {.column}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week7-anova_files/figure-revealjs/unnamed-chunk-14-1.png){width=384}\n:::\n\n::: {.cell-output-display}\n\n-----------------------------------\n diet   mean     se      sd     n  \n------ ------- ------- ------- ----\n  1     170.4   13.45   55.44   17 \n\n  2     205.6   22.22   70.25   10 \n\n  3     258.9   20.63   65.24   10 \n\n  4     233.9   12.52   37.57   9  \n-----------------------------------\n\n\n:::\n:::\n\n\n:::\n\n:::\n\n## Another example: treating anorexia\n\n::: {.columns}\n\n::: {.column}\nWeight change was measured for 72 young female anorexia patients randomly allocated to three treatment groups:\n\n- cognitive behavioral therapy (CBT)\n- family treatment (FT)\n- a control (Cont)\n\nGrouped summary statistics:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n---------------------------------\n treat   post - pre    sd     n  \n------- ------------ ------- ----\n  CBT      3.007      7.309   29 \n\n Cont      -0.45      7.989   26 \n\n  FT       7.265      7.157   17 \n---------------------------------\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week7-anova_files/figure-revealjs/unnamed-chunk-16-1.png){width=576}\n:::\n:::\n\n\n> Were any of the treatments more effective than others?\n:::\n\n:::\n\n## Another example: treating anorexia\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit anova model\nfit <- aov(change ~ treat, data = anorexia)\n\n# generate table\nsummary(fit)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n------------------------------------------------------------\n    &nbsp;       Df   Sum Sq   Mean Sq   F value    Pr(>F)  \n--------------- ---- -------- --------- --------- ----------\n   **treat**     2    614.6     307.3     5.422    0.006499 \n\n **Residuals**   69    3911     56.68      NA         NA    \n------------------------------------------------------------\n\nTable: Analysis of Variance Model\n\n\n:::\n:::\n\n\n> The data provide strong evidence of an effect of therapeutic treatment on mean weight change among young women with anorexia (*F = 5.422* on *2* and *69* degrees of freedom, *p = 0.0065*).\n\n",
    "supporting": [
      "week7-anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}