{
  "hash": "c7fb522b721cbd5435ba69b846f8bcc6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 11: Inference for binomial proportions\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  echo: true\n  eval: true\n  message: false\n  warning: false\n  results: 'markup'\nformat: \n  html:\n    toc: true\n  docx:\n    toc: false\nprefer-html: true\nembed-resources: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n::: {.cell}\n\n:::\n\n\n\nThe goal of this lab is to learn how to implement:\n\n1. tests and intervals for binomial proportions from one sample\n2. tests and intervals comparing two proportions from independent samples\n\nThe activity represents our first foray into categorical data analysis. You'll reproduce examples from lecture using the NHANES data to estimate diabetets prevalence and the Vitamin C experiment; you'll practice on a few additional datasets.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload('data/vitamin.RData')\nload('data/nhanes500.RData')\nload('data/obesity.RData')\n```\n:::\n\n\n\n\n### Inference for one proportion\n\n#### Refresher: categorical frequency distributions\n\nInference for proportions -- and for that matter, future material on inference for categorical data -- will leverage frequency distributions to perform calculations. \n\nYou learned how to make these descriptive summaries at the beginning of the quarter, but a refresher may be helpful. Recall that a frequency distribution, for a categorical variable, is simply a set of counts of observations of each unique value of the variable. We made these using `table(...)`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract variable of interest\ndia <- nhanes$diabetes\n\n# construct table of counts (frequency distribution)\ntable(dia)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndia\nYes  No \n 57 443 \n```\n\n\n:::\n\n```{.r .cell-code}\n# render as proportions (still frequency distribution, but normalized)\ntable(dia) |> prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndia\n  Yes    No \n0.114 0.886 \n```\n\n\n:::\n\n```{.r .cell-code}\n# barplot\ntable(dia) |> prop.table() |> barplot()\n```\n\n::: {.cell-output-display}\n![](lab11-proportions_files/figure-docx/frequency distribution refresher-1.png)\n:::\n:::\n\n\n\n::: callout-note\n## Your turn 1\n\nCompute the frequency distribution, in both counts and proportions, for the `sleeptrouble` variable in the NHANES dataset, which records whether the participant experiences sleep trouble. Also construct a barplot to visualize the frequency distribution\n\n\n\n::: {.cell}\n\n:::\n\n\n:::\n\n#### Point estimation\n\nThe point estimate for a population proportion is simply the corresponding sample proportion:\n\n$$\n\\hat{p} = \\frac{\\#\\text{ observations of category of interest}}{\\text{sample size }n}\n$$\nThis can be ascertained directly from the frequency distribution. In the diabetes example, $\\hat{p}=57$.\n\nThe standard error for $\\hat{p}$ is:\n$$\nSE(\\hat{p}) = \\sqrt{\\frac{\\hat{p}(1 - \\hat{p})}{n}}\n$$\nThis measures the sample-to-sample variability of $\\hat{p}$. To compute the standard error for a binomial proportion, take the product of the two proportions and divide by the sample size, as shown below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# point estimates *are* sample proportions in the frequency distribution table\ndia.p <- table(dia) |> prop.table()\n\n# point estimate (sample proportion of interest)\ndia.p.hat <- dia.p[1]\ndia.p.hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Yes \n0.114 \n```\n\n\n:::\n\n```{.r .cell-code}\n# standard error\ndia.n <- length(dia)\ndia.p.hat.se <- sqrt(prod(dia.p)/dia.n)\ndia.p.hat.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01421295\n```\n\n\n:::\n:::\n\n\n\nThis is interpreted as follows:\n\n> The proportion of U.S. adults with diagnosed diabetes is estimated to be 0.114 (SE = 0.0142).\n\n::: callout-note\n## Your turn 2\n\nUsing the NHANES data, compute a point estimate and standard error for the proportion of U.S. adults who have sleep trouble. Interpret the estimate in context as shown above.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n:::\n\n#### Confidence intervals (manually)\n\nThe confidence interval is straightforward to compute by hand:\n$$\n\\hat{p} \\pm c\\times SE(\\hat{p})\n$$\nOnce estimates are in hand, the calculation requires only finding an appropriate critical value $c$. For a $1 - \\alpha$ confidence interval, this is the $1 - \\frac{\\alpha}{2}$ quantile of the normal model, *i.e.*, the value satisfying:\n\n$$\nP(Z \\leq c) = 1 - \\frac{\\alpha}{2}\n$$\n\nHere are several examples:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 90% interval\ncval <- qnorm(1 - 0.10/2)\ndia.p.hat + c(-1, 1)*cval*dia.p.hat.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09062177 0.13737823\n```\n\n\n:::\n\n```{.r .cell-code}\n# 95% interval\ncval <- qnorm(1 - 0.05/2)\ndia.p.hat + c(-1, 1)*cval*dia.p.hat.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08614313 0.14185687\n```\n\n\n:::\n\n```{.r .cell-code}\n# 99% interval\ncval <- qnorm(1 - 0.01/2)\ndia.p.hat + c(-1, 1)*cval*dia.p.hat.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07738986 0.15061014\n```\n\n\n:::\n\n```{.r .cell-code}\n# 99.9% interval\ncval <- qnorm(1 - 0.001/2)\ndia.p.hat + c(-1, 1)*cval*dia.p.hat.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0672319 0.1607681\n```\n\n\n:::\n:::\n\n\n\nTo interpret the last interval:\n\n> With 99.9% confidence, the proportion of U.S. adults with diagnosed diabetes is estimated to be between 0.067 and 0.161, with a point estimate of 0.114 (SE 0.0142).\n\n::: callout-note\n## Your turn 3\n\nUsing the NHANES data, construct and interpret a 98% confidence interval for the proportion of U.S. adults who have sleep trouble.\n\n\n\n::: {.cell}\n\n:::\n\n\n:::\n\n#### Hypothesis tests\n\nTo test the hypothesis that a population proportion is some null value $p_0$ against a non-directional (two-sided) alternative, *i.e.*,\n\n$$\n\\begin{cases}\nH_0: &p = p_0 \\\\\nH_A: &p \\neq p_0\n\\end{cases}\n$$\n\nwe use a test statistic that is *almost* the estimation error divided by the standard error, but we substitute the hypothetical value for the estimate in the standard error:\n\n$$\nZ = \\frac{\\hat{p} - p_0}{\\sqrt{\\frac{p_0(1 - p_0)}{n}}}\n$$\n\nThe $p$-value is simply the proportion of the normal model for the sampling distribution of $Z$ that exceeds the observed statistic in either direction: $P(|Z| > Z_obs)$. This can be computed by hand as shown below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# test stat\ndia.z <- (dia.p.hat - 0.1)/sqrt(0.1*0.9/dia.n)\n\n# two sided p value\ndia.pval <- 2*pnorm(abs(dia.z), lower.tail = F)\ndia.pval\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Yes \n0.2967175 \n```\n\n\n:::\n:::\n\n\n\nThe result is interpreted as follows in standard narrative style:\n\n> The data provide no evidence that the proportion of U.S. adults with diagnosed diabetes differs from 0.1 (Z = 1.04, *p* = 0.2967).\n\n::: callout-note\n## Your turn 4\n\nTest the hypothesis that the proportion of U.S. adults who have sleep trouble is 0.3 against a two-sided alternative at the 5% significance level. Interpret the result in context.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# test stat\n\n# two sided p value\n```\n:::\n\n\n\n:::\n\nA more straightforward way to perform the inference -- both the test and interval -- utilizes `prop.test(...)`. The command below matches our prior results:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pass table (counts) to prop.test\ntable(dia) |> \n  prop.test(p = 0.1, alternative = 'two.sided', \n            conf.level = 0.95, correct = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  table(dia), null probability 0.1\nX-squared = 1.0889, df = 1, p-value = 0.2967\nalternative hypothesis: true p is not equal to 0.1\n95 percent confidence interval:\n 0.0890369 0.1448491\nsample estimates:\n    p \n0.114 \n```\n\n\n:::\n:::\n\n\n\nThe resulting test and interval would be reported jointly:\n\n> The data provide no evidence that the proportion of U.S. adults with diagnosed diabetes differs from 0.1 (Z = 1.04, *p* = 0.2967). > With 95% confidence, the proportion of U.S. adults with diagnosed diabetes is estimated to be between 0.089 and 0.145, with a point estimate of 0.114 (SE 0.0142).\n\nThe `prop.test(...)` function also makes doing directional tests easier. Below are two examples:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# upper sided test/interval: does p exceed 0.09?\ntable(dia) |> \n  prop.test(p = 0.09, alternative = 'greater', \n            conf.level = 0.95, correct = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  table(dia), null probability 0.09\nX-squared = 3.5165, df = 1, p-value = 0.03038\nalternative hypothesis: true p is greater than 0.09\n95 percent confidence interval:\n 0.09266984 1.00000000\nsample estimates:\n    p \n0.114 \n```\n\n\n:::\n\n```{.r .cell-code}\n# upper sided test/interval: is p under 0.14?\ntable(dia) |> \n  prop.test(p = 0.14, alternative = 'less', \n            conf.level = 0.95, correct = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  table(dia), null probability 0.14\nX-squared = 2.8073, df = 1, p-value = 0.04692\nalternative hypothesis: true p is less than 0.14\n95 percent confidence interval:\n 0.000000 0.139485\nsample estimates:\n    p \n0.114 \n```\n\n\n:::\n:::\n\n\n\n::: callout-note\n## Your turn 5\n\nTest whether the proportion of U.S. adults who experience sleep trouble is under 0.3 at the 1% significance level. Provide an upper confidence bound along with your test.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# test whether the proportion with sleep trouble is under 0.3\n```\n:::\n\n\n\n:::\n\nThe default approach is to apply the continuity correction (set `correct = T` or omit this argument). We omitted it so that results would match the manual calculations above. You should apply the correction in practice.\n\n### Inference for two proportions\n\nInference comparing two proportions proceeds from a two-way table or \"contingency\" table. You may recall that this is a bivariate frequency distribution of two categorical variables. Take a moment to refresh your memory on how to construct these tables:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# variables of interest\ntrt <- vitamin$vitamin\nout <- vitamin$autism\n\n# construct contingency table\nvitamin.tbl <- table(trt, out)\nvitamin.tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            out\ntrt          autism no autism\n  no vitamin    111        70\n  vitamin       143       159\n```\n\n\n:::\n:::\n\n\n\nFor inference to work appropriately with `prop.test(...)`, it is important that the outcome be shown in the column dimension and the groups be shown in the row dimension. Further, the outcome of interest should be the first column (not the second).\n\n::: callout-note\n## Your turn 6\n\nConstruct a contingency table for the `obesity` data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# variables of interest\n\n# contingency table\n```\n:::\n\n\n\n:::\n\nThe contingency table can be used directly to perform inference on a difference in proportions:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# test for difference in proportions\nprop.test(vitamin.tbl, \n          alternative = 'two.sided', \n          conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  vitamin.tbl\nX-squared = 8.3131, df = 1, p-value = 0.003936\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.04475176 0.23474771\nsample estimates:\n   prop 1    prop 2 \n0.6132597 0.4735099 \n```\n\n\n:::\n:::\n\n\n\n::: callout-note\n## Your turn 7\n\nTest whether the rate of CHD deaths differs among obese and non-obese populations.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n:::\n",
    "supporting": [
      "lab11-proportions_files/figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}