{
  "hash": "e793795d5100a131be34d1bcd040adbe",
  "result": {
    "markdown": "---\ntitle: \"Two sample inference\"\nsubtitle: \"Hypothesis tests and intervals for comparing means from paired and independent data\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    mermaid:\n      theme: neutral\nexecute: \n  echo: false\n  warning: false\n  message: false\n---\n\n\n## Today's agenda\n\n\n::: {.cell}\n\n:::\n\n\n1.  Reading quiz \\[[2pm section](https://forms.office.com/r/f81B2eHCv7)\\] \\[[4pm section](https://forms.office.com/r/1HiaaNEXCG)\\]\n2.  [lecture/lab] Two-sample inference for population means\n    \n    a. Paired data\n    b. Independent data\n    \n3.  [if time] Introduction to power analysis\n\n## From last time\n\n> Are swimmers faster in bodysuits than in regular swimsuits?\n\nBelow are the first few observations of the average velocity of competitive swimmers in a 1500m; one measurement was taken in a swimsuit, the other in a bodysuit.\n\n\n::: {.cell}\n::: {.cell-output-display}\n---------------------------------------------------\n swimmer   body.suit.velocity   swim.suit.velocity \n--------- -------------------- --------------------\n    1             1.57                 1.49        \n\n    2             1.47                 1.37        \n\n    3             1.42                 1.35        \n---------------------------------------------------\n:::\n:::\n\n\n-   *two-sample* problem because there are two sets of observations\n-   observations are **paired** by swimmer\n\nThis is the easiest kind of two-sample problem because we can reduce it to a one-sample problem by performing inference on paired differences.\n\n## Inference for paired data\n\n1.  Calculate paired differences.\n\n\n::: {.cell}\n::: {.cell-output-display}\n-------------------------------------------------------------------\n swimmer   body.suit.velocity   swim.suit.velocity   velocity.diff \n--------- -------------------- -------------------- ---------------\n    1             1.57                 1.49              0.08      \n\n    2             1.47                 1.37               0.1      \n\n    3             1.42                 1.35              0.07      \n-------------------------------------------------------------------\n:::\n:::\n\n\n::: columns\n::: column\n2.  Perform test as before.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# test for paired difference\nt.test(diffs, mu = 0, alternative = 'greater')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  diffs\nt = 12.318, df = 11, p-value = 4.443e-08\nalternative hypothesis: true mean is greater than 0\n95 percent confidence interval:\n 0.06620114        Inf\nsample estimates:\nmean of x \n   0.0775 \n```\n:::\n:::\n\n:::\n\n::: column\n3.  Report the result of the test. *You try.*\n:::\n:::\n\n## Formulating a two-sample problem\n\n::: columns\n::: {.column width=\"60%\"}\nTwo-sample problems are characterized by:\n\n-   one variable of interest\n-   two groups of observations\n-   objective to compare group means\n\nInference concerns the *difference in means*\n\n$$\\delta = \\mu_1 - \\mu_2$$\n\nWe just tested:\n\n$$H_0: \\mu_\\text{body} \\leq \\mu_\\text{swim}$$ $$H_A: \\mu_\\text{body} > \\mu_\\text{swim}$$\n:::\n\n::: {.column width=\"40%\"}\nRearranging the data to emphasize two-sample problem structure:\n\n\n::: {.cell}\n::: {.cell-output-display}\n---------------------------\n swimmer   suit   velocity \n--------- ------ ----------\n    1      body     1.57   \n\n    1      swim     1.49   \n\n    2      body     1.47   \n\n    2      swim     1.37   \n\n    3      body     1.42   \n---------------------------\n:::\n:::\n\n\n-   variable of interest: `velocity`\n-   grouping: `suit`\n-   pairing: `swimmer`\n:::\n:::\n\n## Hypotheses for two-sample tests\n\nWe can articulate two-sided and directional tests for the difference in means $\\delta = \\mu_1 - \\mu_2$ and the corresponding interpretation in terms of the group means.\n\n::: columns\n::: column\n**Difference in means**\n\n$$\\text{two-sided}\\begin{cases} H_0: \\delta \\qquad 0 \\\\ H_A: \\delta \\qquad 0 \\end{cases}$$\n\n$$\\text{lower-sided}\\begin{cases} H_0: \\delta \\qquad 0 \\\\ H_A: \\delta \\qquad 0 \\end{cases}$$\n\n$$\\text{upper-sided}\\begin{cases} H_0: \\delta \\qquad 0 \\\\ H_A: \\delta \\qquad 0 \\end{cases}$$\n:::\n\n::: column\n**Group interpretation**\n\n$$\\begin{cases} H_0: \\mu_1 \\qquad \\mu_2 \\\\ H_A: \\mu_1 \\qquad \\mu_2 \\end{cases}$$\n\n$$\\begin{cases} H_0: \\mu_1 \\qquad \\mu_2 \\\\ H_A: \\mu_1 \\qquad \\mu_2 \\end{cases}$$\n\n$$\\begin{cases} H_0: \\mu_1 \\qquad \\mu_2 \\\\ H_A: \\mu_1 \\qquad \\mu_2 \\end{cases}$$\n:::\n:::\n\n## Your turn: FAMuSS\n\n> Does resistance training lead to greater strength gains on the nondominant arm?\n\n\n::: {.cell}\n::: {.cell-output-display}\n-------------------------------------------------------------------------------------\n ndrm.ch   drm.ch    sex     age     race      height   weight   actn3.r577x    bmi  \n--------- -------- -------- ----- ----------- -------- -------- ------------- -------\n   40        40     Female   27    Caucasian     65      199         CC        33.11 \n\n   25        0       Male    36    Caucasian    71.7     189         CT        25.84 \n\n   40        0      Female   24    Caucasian     65      134         CT        22.3  \n-------------------------------------------------------------------------------------\n:::\n:::\n\n\nArticulate and test an appropriate hypothesis for $\\delta = \\mu_\\text{ndrm} - \\mu_\\text{drm}$\n\n::: columns\n::: {.column width=\"40%\"}\n-   Hypotheses: $$H_0: \\hspace{15cm}$$ $$H_A: \\hspace{15cm}$$\n:::\n\n::: {.column width=\"60%\"}\n-   Result:\n:::\n:::\n\n## Evolution of Darwin's finches\n\n::: columns\n::: {.column width=\"70%\"}\n> Grant, P. (1986). Ecology and Evolution of Darwin's Finches, Princeton University Press, Princeton, N.J.\n\nPeter and Rosemary Grant caught and measured all the birds from more than 20 generations of finches on the Galapagos island of Daphne Major.\n\n-   severe drought in 1977 limited food to large tough seeds\n\n-   selection pressure favoring larger and stronger beaks\n\n-   hypothesis: beak depth increased in 1978 relative to 1976\n\n*How do we test for a difference in the absence of pairing?*\n:::\n\n::: {.column width=\"30%\"}\nFinch beak data:\n\n\n::: {.cell}\n::: {.cell-output-display}\n--------------\n Year   Depth \n------ -------\n 1976    9.5  \n\n 1976   11.7  \n\n 1976    9.3  \n\n 1978   10.9  \n\n 1978   11.5  \n\n 1978    9.7  \n--------------\n:::\n:::\n\n\n-   Variable: `Depth`\n-   Grouping: `Year`\n-   *No pairing!*\n:::\n:::\n\n## Inference for independent data\n\n> Beak depths exemplify **independent data**: the groups of observations are unrelated.\n\n::: columns\n::: column\nInference is based on the difference in group means:\n\n$$\nT = \\frac{\\bar{x} - \\bar{y}}{SE(\\bar{x} - \\bar{y})}\n$$\n\n-   $\\bar{x}, \\bar{y}$ are groupwise sample means\n-   $SE(\\bar{x} - \\bar{y}) = \\sqrt{\\frac{s_x^2}{n_x} + \\frac{s_x^2}{n_y}}$\n-   degrees of freedom for $t$ model are approximated\n:::\n\n::: column\n$$H_0: \\mu_{1976} \\geq \\mu_{1978}$$ $$H_A: \\mu_{1976} < \\mu_{1978}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(Depth ~ Year, data = finch,\n       mu = 0, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  Depth by Year\nt = -4.5833, df = 172.98, p-value = 4.37e-06\nalternative hypothesis: true difference in means between group 1976 and group 1978 is less than 0\n95 percent confidence interval:\n      -Inf -0.427321\nsample estimates:\nmean in group 1976 mean in group 1978 \n          9.469663          10.138202 \n```\n:::\n:::\n\n:::\n:::\n\n## Two input formats\n\n\n::: {.cell}\n\n:::\n\n\n::: columns\n::: column\nThe **formula** format takes inputs:\n\n1.  an R formula\n2.  a data frame\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# two-sample test (formula inputs)\nt.test(Depth ~ Year, data = finch,\n       mu = 0, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  Depth by Year\nt = -4.5833, df = 172.98, p-value = 4.37e-06\nalternative hypothesis: true difference in means between group 1976 and group 1978 is less than 0\n95 percent confidence interval:\n      -Inf -0.427321\nsample estimates:\nmean in group 1976 mean in group 1978 \n          9.469663          10.138202 \n```\n:::\n:::\n\n\n`Depth ~ Year`: \"depth *depends on* year\"\n:::\n\n::: column\nThe **vector** format takes inputs:\n\n1.  vector of observations for one group\n2.  vector of observations for the other group\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# two-sample test (vector inputs)\nt.test(depth76, depth78,\n       mu = 0, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  depth76 and depth78\nt = -4.5833, df = 172.98, p-value = 4.37e-06\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n      -Inf -0.427321\nsample estimates:\nmean of x mean of y \n 9.469663 10.138202 \n```\n:::\n:::\n\n:::\n:::\n\n## Interpreting results\n\n::: columns\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  Depth by Year\nt = -4.5833, df = 172.98, p-value = 4.37e-06\nalternative hypothesis: true difference in means between group 1976 and group 1978 is less than 0\n95 percent confidence interval:\n      -Inf -0.427321\nsample estimates:\nmean in group 1976 mean in group 1978 \n          9.469663          10.138202 \n```\n:::\n:::\n\n\nTo report the results:\n\n1.  State conclusion\n2.  Interpret test result in context\n3.  Report statistics (*T*, *df*, *p*-value)\n4.  Provide point estimates\n\n*Careful about signs and directions!*\n:::\n\n::: {.column width=\"55%\"}\n> Our findings suggest finch beak depth on Daphne Major increased as a result of natural selection following drought. The data provide strong evidence against the null hypothesis that mean beak depth remained comparable or diminished in the generation following the drought in favor of the alternative that mean beak depth increased (*T* = -4.58 on 172.98 degrees of freedom, *p* = 0.00000437). With 95% confidence, the increase in beak depth is estimated to be at least 0.427 mm, with a point estimate of 0.669 mm (*SE* = 0.1459).\n:::\n:::\n\n## Cloud data: paired or independent?\n\n> Does dropping silver iodide onto clouds increase rainfall?\n\n::: columns\n::: {.column width=\"60%\"}\nData are rainfall measurements in a target area from 26 days when clouds were seeded and 26 days when clouds were not seeded.\n\n-   `rainfall` gives volume of rainfall in acre-feet\n-   `treatment` indicates whether clouds were seeded\n\nHypotheses to test: $$H_0: \\mu_\\text{seeded} \\quad \\mu_\\text{unseeded}$$ $$H_A: \\mu_\\text{seeded} \\quad \\mu_\\text{unseeded}$$\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n----------------------\n rainfall   treatment \n---------- -----------\n   92.4      Seeded   \n\n   31.4      Seeded   \n\n   119       Seeded   \n\n  703.4      Seeded   \n\n   163      Unseeded  \n\n   21.7     Unseeded  \n\n  321.2     Unseeded  \n\n  147.8     Unseeded  \n----------------------\n:::\n:::\n\n:::\n:::\n\n## Sleep drugs: paired or independent?\n\n> Which (if either) of two soporific drugs is more effective?\n\n::: columns\n::: {.column width=\"60%\"}\nData are extra hours of sleep for 10 study participants when taking each of two drugs.\n\n-   `extra.sleep` gives hours of additional sleep relative to control\n-   `drug` indicates which sleep drug was taken\n-   `subject` indicates study participant id\n\nHypotheses to test: $$H_0: \\mu_1 \\quad \\mu_2$$ $$H_A: \\mu_1 \\quad \\mu_2$$\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n------------------------------\n extra.sleep   drug   subject \n------------- ------ ---------\n     0.7        1        1    \n\n     1.9        2        1    \n\n    -1.6        1        2    \n\n     0.8        2        2    \n\n    -0.2        1        3    \n\n     1.1        2        3    \n------------------------------\n:::\n:::\n\n:::\n:::\n\n\n## Test assumptions\n\n::: columns\n::: {.column width=\"40%\"}\nInference relies on a $t$ model providing a good approximation to the sampling distribution. This requires three assumptions:\n\n1.  variable of interest is numeric and not too discrete\n\n2.  observations are independent (besides pairing)\n\n3.  either:\n\n    a.  sample sizes are not too small\n    b.  or distribution(s) are symmetric and unimodal\n:::\n\n::: {.column width=\"60%\"}\nCommon issues:\n\n| Issue                                                             | Consequence                                                        |\n|------------------------------------|------------------------------------|\n| Highly discrete data                                              | $t$ model not appropriate                                          |\n| Dependent observations                                            | $SE$ is a biased estimate: nominal error rates and coverage are inaccurate |\n| Small samples with [*heavy*]{.underline} skew or [*extreme*]{.underline} outliers | $SE$ too small: inflated type I error and under-coverage           |\n\n> *In each of these scenarios, different inference procedures should be used.*\n\n:::\n:::\n\n\n::: {.cell}\n\n:::\n\n\n## Power calculations\n\n> How much data do you need to collect in order to detect a difference of $\\delta$?\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\nThe statistical **power** of a test captures how often it detects a specified alternative.\n\n- defined as $\\beta = (1 - \\text{type II error rate})$\n- measures how often the test correctly rejects\n- value depends on...\n\n    a. magnitude of difference between null value and true value of parameter\n    b. significance level\n    c. sample size\n\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npower.t.test(power = 0.95, \n             delta = 0.5, \n             sig.level = 0.05, \n             type = 'two.sample',\n             alternative = 'two.sided')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     Two-sample t test power calculation \n\n              n = 104.928\n          delta = 0.5\n             sd = 1\n      sig.level = 0.05\n          power = 0.95\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n:::\n:::\n\n$\\Rightarrow$ need 105 observations in each group to detect a difference of 0.5 standard deviations at level 0.05 with type II error rate 5% or less\n:::\n\n:::\n\n## The equal-variance $t$-test\n\nIf it is reasonable to assume the (population) standard deviations are the same in each group, one can gain a bit of power (lower type II error rate) by using a different standard error:\n\n$$SE_\\text{pooled}(\\bar{x} - \\bar{y}) = \\sqrt{\\frac{\\color{red}{s_p^2}}{n_x} + \\frac{\\color{red}{s_p^2}}{n_y}}\n\\quad\\text{where}\\quad \\color{red}{s_p} = \\underbrace{\\sqrt{\\frac{(n_x - 1)s_x^2 + (n_y - 1)s_y^2}{n_x + n_y - 2}}}_{\\text{weighted average of } s_x^2 \\;\\&\\; s_y^2}$$\n\nImplement by adding `var.equal = T` as an argument to `t.test()`.\n\n- larger df is used, hence more frequent rejections\n- avoid unless you have a small sample\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}