{
  "hash": "460f567a2f88ad13a8acf96feed34ba8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inference for population proportions\"\nsubtitle: \"An introduction to categorical data analysis\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    mermaid:\n      theme: neutral\nexecute: \n  echo: false\n  warning: false\n  message: false\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n::: {.cell}\n\n:::\n\n\n## Today's agenda\n\n1. [lecture] Inference for binomial proportions\n2. [lab] Tests for proportions in R\n\n## Binomial proportions\n\n> A binomial variable is a nominal categorical variable with two unique values.\n\n::: columns\n::: {.column width=\"65%\"}\nUsually, binomial data record the presence/absence of an event, trait, or property of interest.\n\nInference for binomial data has a different flavor:\n\n-   non-numeric values $\\Rightarrow$ can't compute usual statistics (mean, variance, etc.)\n-   focus on proportions instead\n\nExample: prevalence of diabetes among US adults?\n\n-   estimate and standard error?\n-   confidence interval?\n-   hypothesis test?\n:::\n\n::: {.column width=\"35%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-proportions_files/figure-revealjs/unnamed-chunk-2-1.png){width=384}\n:::\n:::\n\n:::\n:::\n\n## Estimating proportions\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n----------------------------------------\n     &nbsp;        Yes     No     total \n---------------- ------- ------- -------\n   **count**       57      443     500  \n\n **proportion**   0.114   0.886     1   \n----------------------------------------\n\nTable: *Diabetes data summary*\n\n\n:::\n:::\n\n\nEstimated diabetes prevalence: 11.4%.\n\n-   NHANES data are a random sample of the U.S. adult population\n-   sample statistics should approximate population statistics\n:::\n\n::: {.column width=\"50%\"}\nWe'll formalize this as estimating the **population proportion** $$p = \\frac{\\# \\text{ individuals with diabetes}}{\\text{total population size } N}$$ Using the **sample proportion** $$\\hat{p} = \\frac{\\# \\text{ respondents with diabetes}}{\\text{sample size } n}$$\n:::\n:::\n\nThe first step towards inference is a measure of precision for $\\hat{p}$. What is $SE(\\hat{p})$?\n\n## SE for a sample proportion\n\n> Binomial data are most variable when $p = 0.5$ and least variable when $p \\approx 0$ or $1$\n\n::: columns\n::: {.column width=\"45%\"}\nMeasure of spread for binomial data: $$\\sqrt{\\hat{p}(1 - \\hat{p})}$$\n\n-   highest when $\\hat{p} \\approx 0.5$\n-   lowest when $\\hat{p} \\approx 0 \\text{ or } 1$\n\nAnalogous to estimating a mean: $$\nSE\\left(\\hat{p}\\right) \n= \\frac{\\text{spread}}{\\sqrt{\\text{sample size}}} \n= \\sqrt{\\frac{\\hat{p}(1 - \\hat{p})}{n}}\n$$\n:::\n\n::: {.column width=\"55%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week8-proportions_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=480}\n:::\n:::\n\n:::\n:::\n\n## Sampling distribution of $\\hat{p}$\n\n::: columns\n::: column\nThe sample proportion $\\hat{p}$ has a sampling distribution that can be approximated by a normal model, provided:\n\n-   $\\hat{p}$ isn't too close to 0 or 1\n-   $n$ is sufficiently large\n\nA common condition to check:\n\n$$n\\hat{p} \\geq 10\\text{ and }n(1 - \\hat{p}) \\geq 10$$\n:::\n\n::: column\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-proportions_files/figure-revealjs/unnamed-chunk-5-1.png){width=480}\n:::\n:::\n\n:::\n:::\n\nThis model can be used to construct hypothesis tests and confidence intervals for $p$.\n\n## Confidence interval for $p$\n\nA confidence interval for a binomial proportion $p$ is:\n\n$$\\hat{p} \\pm c \\times SE(\\hat{p})$$\n\nThe critical value $c$ comes from the normal model.\n\n-   empirical rule:\n\n    -   $c = 1$ gives a 68% interval\n    -   $c = 2$ gives a 95% interval\n    -   $c = 3$ gives a 99.7% interval\n\n-   for a $(1 - \\alpha)\\times 100 \\%$ confidence interval use the $1 - \\frac{\\alpha}{2}$ quantile of the normal model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(1 - 0.1/2) # c for 90% interval\nqnorm(1 - 0.05/2) # c for 95% interval\nqnorm(1 - 0.01/2) # c for 99% interval\n```\n:::\n\n\n## Example: diabetes prevalence\n\n::: columns\n::: column\n\n::: {.cell}\n::: {.cell-output-display}\n\n-----------------------\n p.hat     se       n  \n------- --------- -----\n 0.114   0.01421   500 \n-----------------------\n\nTable: Point estimate for diabetes prevalence\n\n\n:::\n:::\n\n:::\n\n::: column\n> It is estimated that the proportion of the U.S. adult population with diagnosed diabetes is 11.4% (*SE = 1.42%*).\n:::\n:::\n\nCheck assumptions for the normal model:\n\n$$\n500\\times 0.114 = 57 \\geq 10\n\\quad\\text{and}\\quad 500\\times 0.886 = 443 \\geq 10\n$$\n\n::: columns\n::: column\n95% confidence interval for diabetes prevalence:\n\n$$\n0.114 \\pm 2\\times 0.01421 = (0.0881, 0.1459)\n$$\n:::\n\n::: column\n> With 95% confidence, the proportuion of U.S. adults with diagnosed diabetes is estimated to be between 8.81% and 14.59%.\n:::\n:::\n\n## Hypothesis tests for $p$\n\n::: columns\n::: {.column width=\"45%\"}\nTo test whether true prevalence is 10%: \n$$\n\\begin{cases}\nH_0: &p = 0.1 \\\\ \nH_A: &p \\neq 0.1\n\\end{cases}\n$$\n\nWe can use the test statistic:\n\n$$\nZ = \\frac{\\hat{p} - p_0}{\\sqrt{\\frac{p_0 (1 - p_0)}{n}}}\n= \\frac{\\hat{p} - 0.1}{\\sqrt{\\frac{0.1 (0.9)}{500}}}\n$$\nUnder $H_0$, the sampling distribution of $Z$ is approximated by a normal model, provided:\n\n- $np_0 \\geq 10$\n- $n(1 - p_0) \\geq 10$\n:::\n\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-proportions_files/figure-revealjs/unnamed-chunk-8-1.png){width=624}\n:::\n:::\n\n\nHere $p = P(|Z| > 1.043) = 0.2967$, so:\n\n> the data provide no evidence that prevalence differs from 10%.\n\n\n\n:::\n:::\n\n## Hypothesis tests for $p$\n\n::: columns\n::: {.column width=\"45%\"}\nTo test whether true prevalence is 15%: \n$$\n\\begin{cases}\nH_0: &p = 0.15 \\\\ \nH_A: &p \\neq 0.15\n\\end{cases}\n$$\n\nWe can use the test statistic:\n\n$$\nZ = \\frac{\\hat{p} - p_0}{\\sqrt{\\frac{p_0 (1 - p_0)}{n}}}\n= \\frac{\\hat{p} - 0.15}{\\sqrt{\\frac{0.15 (0.85)}{500}}}\n$$\nUnder $H_0$, the sampling distribution of $Z$ is approximated by a normal model, provided:\n\n- $np_0 \\geq 10$\n- $n(1 - p_0) \\geq 10$\n:::\n\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-proportions_files/figure-revealjs/unnamed-chunk-9-1.png){width=624}\n:::\n:::\n\n\nHere $p = P(|Z| > 2.254) = 0.0242$, so:\n\n> the data provide moderate evidence that prevalence differs from 15%.\n\n:::\n:::\n\n## Hypothesis tests for $p$\n\n::: columns\n::: {.column width=\"45%\"}\nTo test if prevalence is below 14%: \n$$\n\\begin{cases}\nH_0: &p = 0.14 \\\\ \nH_A: &p < 0.14\n\\end{cases}\n$$\n\nWe can use the test statistic:\n\n$$\nZ = \\frac{\\hat{p} - p_0}{\\sqrt{\\frac{p_0 (1 - p_0)}{n}}}\n= \\frac{\\hat{p} - 0.14}{\\sqrt{\\frac{0.14 (0.86)}{500}}}\n$$\n\nUnder $H_0$, the sampling distribution of $Z$ is approximated by a normal model, provided:\n\n- $np_0 \\geq 10$\n- $n(1 - p_0) \\geq 10$\n:::\n\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-proportions_files/figure-revealjs/unnamed-chunk-10-1.png){width=624}\n:::\n:::\n\n\nHere $p = P(Z < 1.676) = 0.0469$, so:\n\n> the data provide moderate evidence that prevalence is less than 14%.\n\n\n\n:::\n:::\n\n## Inference for a proportion in R\n\n::: columns\n::: {.column width=\"45%\"}\nInference using the normal model in R:\n\n1.  Construct a table of the frequency distribution\n2.  Pass the table to `prop.test()`\n\nRemarks about output:\n\n-   `X-squared` gives $Z^2$\n-   `correct = F` performs the test without continuity correction\n:::\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"5-7\"}\n# variable of interest\ndia <- nhanes$diabetes\n\n# pass table to prop.test\ntable(dia) |> \n  prop.test(p = 0.1, alternative = 'two.sided',\n            conf.level = 0.95, correct = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  table(dia), null probability 0.1\nX-squared = 1.0889, df = 1, p-value = 0.2967\nalternative hypothesis: true p is not equal to 0.1\n95 percent confidence interval:\n 0.0890369 0.1448491\nsample estimates:\n    p \n0.114 \n```\n\n\n:::\n:::\n\n:::\n:::\n\n> The data provide no evidence that diabetes prevalence among U.S. adults differs from 10%. With 95% confidence, prevalence is estimated to be between 8.90% and 14.48%, with a point estimate of 11.4% (SE = 1.42%).\n\n## `correct = F`?\n\n> A \"continuity correction\" reduces approximation error for the normal model.\n\n::: columns\n::: column\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"5\"}\ntable(dia) |> \n  prop.test(p = 0.1, \n            alternative = 'two.sided',\n            conf.level = 0.95, \n            correct = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  table(dia), null probability 0.1\nX-squared = 1.0889, df = 1, p-value = 0.2967\nalternative hypothesis: true p is not equal to 0.1\n95 percent confidence interval:\n 0.0890369 0.1448491\nsample estimates:\n    p \n0.114 \n```\n\n\n:::\n:::\n\n:::\n\n::: column\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"5\"}\ntable(dia) |> \n  prop.test(p = 0.1, \n            alternative = 'two.sided',\n            conf.level = 0.95, \n            correct = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  table(dia), null probability 0.1\nX-squared = 0.93889, df = 1, p-value = 0.3326\nalternative hypothesis: true p is not equal to 0.1\n95 percent confidence interval:\n 0.08814952 0.14594579\nsample estimates:\n    p \n0.114 \n```\n\n\n:::\n:::\n\n:::\n:::\n\nOmitting the `correct` argument implements the correction by default.\n\n## Exact inference for a proportion\n\nThe test can also be performed using the *exact* sampling distribution obtained from a binomial probability model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom.test(x = 57, n = 500, p = 0.1, alternative = 'two.sided')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  57 and 500\nnumber of successes = 57, number of trials = 500, p-value = 0.2964\nalternative hypothesis: true probability of success is not equal to 0.1\n95 percent confidence interval:\n 0.0874949 0.1451685\nsample estimates:\nprobability of success \n                 0.114 \n```\n\n\n:::\n:::\n\n\nInputs:\n\n-   `x` gives the number of occurrences of the category of interest\n-   `n` gives the sample size\n\n\n\n<!-- ## Your turn: sleep trouble -->\n\n<!-- > Use the NHANES data to estimate the proportion of U.S. adults reporting sleep trouble. Test whether at least 20% of U.S. adults report sleep trouble. -->\n\n<!-- ::: columns -->\n<!-- ::: column -->\n<!-- 1.  Compute point estimate and standard error -->\n\n<!-- 2.  Perform the hypothesis test -->\n\n<!--     -   write the hypotheses -->\n<!--     -   calculate the value of the test statistic -->\n<!--     -   record the $p$-value -->\n\n<!-- 3.  Construct an interval estimate -->\n<!-- ::: -->\n\n<!-- ::: column -->\n<!-- ```{r, echo = T} -->\n<!-- # to get you started -->\n<!-- trouble <- factor(nhanes$SleepTrouble,  -->\n<!--                   levels = c('Yes', 'No')) -->\n<!-- trouble.tbl <- table(trouble) -->\n<!-- ``` -->\n\n<!-- ```{r} -->\n<!-- trouble.tbl |>  -->\n<!--   pander(caption = 'Having sleep trouble?') -->\n<!-- ``` -->\n<!-- ::: -->\n<!-- ::: -->\n\n## Two-way tables\n\n> Two-way tables or \"contingency\" tables compare two categorical variables.\n\n::: columns\n::: column\n\n::: {.cell}\n::: {.cell-output-display}\n\n-----------------------------------\n   &nbsp;      Cold   NoCold    n  \n------------- ------ -------- -----\n **Placebo**   335      76     411 \n\n  **VitC**     302     105     407 \n-----------------------------------\n\nTable: Vitamin C experiment\n\n\n:::\n:::\n\n\n:::\n\n::: column\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-proportions_files/figure-revealjs/unnamed-chunk-16-1.png){width=576}\n:::\n:::\n\n\n:::\n:::\n\n-   vitamin C and placebo treatments were randomly allocated to 818 volunteers\n-   volunteers took treatments daily for a cold season\n-   study recorded how many volunteers came down with a cold\n\n*Is vitamin C effective at preventing common cold?*\n\n## Inference for two proportions\n\nWe can first consider inferences on the difference in proportions:\n\n$$\\delta = p_\\text{placebo} - p_\\text{vitC}$$\n\n<!-- $$\\begin{cases}H_0: p_\\text{placebo} - p_\\text{vitamin C} \\leq 0 \\\\ H_A: p_\\text{placebo} - p_\\text{vitamin C} > 0 \\end{cases}$$ -->\n\nInferences are based on groupwise estimates:\n\n-   point estimate: $\\hat{p}_\\text{placebo} - \\hat{p}_\\text{vitC}$\n\n-   standard error: $\\sqrt{SE^2(\\hat{p}_\\text{placebo}) + SE^2(\\hat{p}_\\text{vitC})}$\n\nWhen both groups meet the conditions for inference for one proportion, the statistic\n\n$$\nZ = \\frac{\\hat{p}_1 - \\hat{p}_2 - \\delta}{SE(\\hat{p}_1 - \\hat{p}_2)}\n$$\nhas a sampling distribution well-approximated by a normal model.\n\n## Confidence interval for the difference\n\n\n$$\n\\hat{p}_\\text{placebo} - \\hat{p}_\\text{vitC} \\pm c\\times SE(\\hat{p}_\\text{placebo} - \\hat{p}_\\text{vitC})\n$$\nFor a $(1 - \\alpha)\\times 100\\%$ confidence interval the critical value $c$ is chosen to be the $\\left(1 - \\frac{\\alpha}{2}\\right)$ quantile of the normal model.\n\n-   point estimate: $\\hat{p}_\\text{placebo} - \\hat{p}_\\text{vitC} = 0.0731$\n\n-   standard error: $\\sqrt{SE^2(\\hat{p}_\\text{placebo}) + SE^2(\\hat{p}_\\text{vitC})} = 0.0289$\n\n- critical value for 95% interval: `qnorm(1 - 0.05/2) = 1.959964`\n\n95% confidence interval: (0.0164, 0.1298)\n\n> With 95% confidence, the prevalence of common cold is estimated to be between 1.64% and 12.98% lower among adults who take daily vitamin C supplements.\n\n## Tests for a difference in proportions\n\n::: columns\n::: column\nWe can also test whether vitamin C prevents common cold:\n\n$$\n\\begin{cases} \nH_0: &p_\\text{placebo} - p_\\text{vitC} = 0\\\\ \nH_A: &p_\\text{placebo} - p_\\text{vitC} > 0 \n\\end{cases}\n$$\n\nHypothesis tests use the test statistic:\n\n$$Z = \\frac{\\hat{p}_1 - \\hat{p}_2}{\\sqrt{\\hat{p}(1 - \\hat{p})\\left(\\frac{1}{n_1} + \\frac{1}{n_2}\\right)}}$$\n\nWith a slightly different SE where: \n$$\\hat{p} = \\frac{n_1\\hat{p}_1 + n_2\\hat{p}_2}{n_1 + n_2}$$\n:::\n\n::: column\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-proportions_files/figure-revealjs/unnamed-chunk-17-1.png){width=624}\n:::\n:::\n\n\nHere $p = P(Z > 2.517) = 0.0059$, so:\n\n> the data provide strong evidence that vitamin C prevents common cold.\n\n:::\n:::\n\n\n## Inference in R\n\n\n::: {.cell}\n\n:::\n\n\n::: columns\n::: column\nThree steps:\n\n1.  Construct a table of the frequency distribution by group\n\n    -   outcomes should be columns\n    -   groups should be rows\n\n2.  Pass to `prop.test()`\n\nThe alternative reads the same way as in `t.test`.\n:::\n\n::: column\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"6-8\"}\n# variables of interest\ntreatment <- vitamin$treatment\noutcome <- vitamin$outcome\n\n# pass table to prop.test\ntable(treatment, outcome) |>\n  prop.test(alternative = 'greater', \n            correct = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  table(treatment, outcome)\nX-squared = 6.3366, df = 1, p-value = 0.005914\nalternative hypothesis: greater\n95 percent confidence interval:\n 0.02548153 1.00000000\nsample estimates:\n   prop 1    prop 2 \n0.8150852 0.7420147 \n```\n\n\n:::\n:::\n\n:::\n:::\n\n> The data provide strong evidence that vitamin C prevents common cold (Z = 2.517, *p* = 0.0059). With 95% confidence, the reduction in probability is estimated to be at least 0.0255, with a point estimate of 0.0731 (SE = 0.0289).\n\n\n## Sampling and two-way tables\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\nConsider this case-control study:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n-----------------------------------------\n   &nbsp;      Smokers   NonSmokers   n  \n------------- --------- ------------ ----\n **Cancer**      83          3        86 \n\n **Control**     72          14       86 \n-----------------------------------------\n\n\n:::\n:::\n\nThis is an example of *outcome-based* sampling:\n\n- 86 lung cancer patients and 86 controls \n- can't estimate cancer prevalence\n\n::: \n\n::: {.column width=\"45%\"}\nA different approach to inference is needed to analyze this data. Next time:\n\n- tests of association in two-way tables\n- inference for risk and odds ratios\n\n:::\n\n:::\n\n\n<!-- ## Your turn: two cases -->\n\n<!-- ```{r} -->\n<!-- obesity <- case1801 |> column_to_rownames('Obesity') |> as.matrix() |> as.table() -->\n<!-- smoking <- case1803 |> column_to_rownames('Smoking') |> as.matrix() |> as.table() |> t() -->\n\n<!-- save(list = c('obesity', 'smoking', 'cold'), file = 'data/prop-cases.RData') -->\n<!-- ``` -->\n\n<!-- ::: columns -->\n<!-- ::: column -->\n<!-- Researchers categorized 3,112 individuals in American Samoa according to whether they were obese and recorded whether subjects had cardiovascular disease (CVD). -->\n\n<!-- ```{r} -->\n<!-- obesity |> pander() -->\n<!-- ``` -->\n\n<!-- *Test for a difference in disease rates between obese and non-obese populations, and produce an interval estimate for the difference in proportions.* -->\n<!-- ::: -->\n\n<!-- ::: column -->\n<!-- Researchers identified 86 lung cancer patients and 86 controls (without lung cancer), and categorized them according to whether they were smokers or non-smokers. -->\n\n<!-- ```{r} -->\n<!-- smoking |> pander() -->\n<!-- ``` -->\n\n<!-- *Test for a difference in the proportion of smokers among cancer patients compared with controls, and produce an interval estimate for the difference.* -->\n<!-- ::: -->\n<!-- ::: -->\n",
    "supporting": [
      "week8-proportions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}