{
  "hash": "f7b7419a516173479d8640ec6c33a905",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 12: Chi-square tests of association\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  echo: true\n  eval: true\n  message: false\n  warning: false\n  results: 'markup'\nformat: \n  html:\n    toc: true\n  docx:\n    toc: false\nprefer-html: true\nembed-resources: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n::: {.cell}\n\n:::\n\n\nThe purpose of this lab is to learn to implement $\\chi^2$ tests of independence/association for two-way contingency tables:\n\n- inference and residual analysis in $2\\times 2$ tables\n- extension to $I\\times J$ tables\n\nMuch of the focus of the lab activity is on the $2\\times 2$ setting. You'll replicate the examples from class using the `asthma` data from an NHANES subsample, and practice using the `diabetes_meds` data. \n\nThe `diabetes_meds` data comes from an observational study of 227,571 Medicare beneficiaries who initiated treatment with one of two diabetes medications. In the study, it was recorded whether each patient reported cardiovascular problems.\n\nApplications in the $I\\times J$ case will both use the `famuss` dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload('data/asthma.RData')\nload('data/diabetes_meds.RData')\nload('data/famuss.RData')\n```\n:::\n\n\n### Inference for $2\\times 2$ tables\n\n#### Basic implementation and checking assumptions\n\nThe test of association/independence in two-way tables pertains to the hypotheses:\n$$\n\\begin{cases}\nH_0: &\\text{row variable} \\perp \\text{column variable} \\\\\nH_A: &\\neg(\\text{row variable} \\perp \\text{column variable})\n\\end{cases}\n$$\n\nIn words, the hypotheses are: (null) the row variable and column variable are independent; (alternative) there is an association between the row and column variables. This is fairly straightforward to implement in R using `prop.test(...)`, which takes a contingency table as input:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make a two-way table\ntable(asthma$sex, asthma$asthma) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         asthma no asthma\n  female     49       781\n  male       30       769\n```\n\n\n:::\n\n```{.r .cell-code}\n# pass to chisq.test\ntable(asthma$sex, asthma$asthma) |>\n  chisq.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  table(asthma$sex, asthma$asthma)\nX-squared = 3.6217, df = 1, p-value = 0.05703\n```\n\n\n:::\n:::\n\n\nThe test (with Yates' continuity correction) produces $p > 0.05$, so we'd fail to reject $H_0$. The typical narrative style for the report is:\n\n> The data provide suggestive but insufficient evidence at the 5% significance level that sex and asthma prevalence are associated ($\\chi^2$ = 3.62 on 1 degree of freedom, *p* = 0.057).\n\n::: callout-note\n## Your turn 1\n\nTest whether diabetes medication is associated with cardiovascular problems. Carry out inference at the 5% significance level and report the result of the test in the narrative style above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# test whether diabetes medication is associated with cardiovascular problems\n```\n:::\n\n:::\n\nThese inferences rely on the assumption that expected counts are all over 10. The expected counts can be inspected directly by storing the result of the test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# store test result\nasthma.rslt <- table(asthma$sex, asthma$asthma) |>\n  chisq.test()\n\n# view expected counts to check assumptions\nasthma.rslt$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n           asthma no asthma\n  female 40.25169  789.7483\n  male   38.74831  760.2517\n```\n\n\n:::\n:::\n\n\nEach expected count exceeds ten, so the test is appropriate to use.\n\n::: callout-note\n## Your turn 2\n\nCheck the expected counts for the inference you performed above to determine whether conditions for the Chi-square test are met.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# store test result\n\n# view expected counts to check assumptions\n```\n:::\n\n:::\n\nLuckily, `prop.test(...)` will print a warning if the counts are too small. For instance:\n\n::: {.cell}\n\n```{.r .cell-code}\n# example using a dataset with low counts\nopenintro::malaria |> table() |> chisq.test()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(table(openintro::malaria)): Chi-squared approximation may\nbe incorrect\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  table(openintro::malaria)\nX-squared = 4.6561, df = 1, p-value = 0.03094\n```\n\n\n:::\n:::\n\n\nWe can check that indeed the assumptions are not met by inspecting expected counts:\n\n::: {.cell}\n\n```{.r .cell-code}\n# all expected counts are under ten\nmalaria.rslt <- openintro::malaria |> table() |> chisq.test()\nmalaria.rslt$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         outcome\ntreatment infection no infection\n  placebo       3.3          2.7\n  vaccine       7.7          6.3\n```\n\n\n:::\n:::\n\n\n#### Residual analysis\n\nIf significant results (or suggestive evidence) is obtained from the Chi-square test, it is useful to be able to say which categories account for the association (or possible association).\n\nIn this context, residuals are standardized differences in expected and observed counts:\n\n$$\nr_{ij} = \\frac{n_{ij} - \\hat{n}_{ij}}{\\sqrt{\\hat{n}_{ij}}}\n$$\n\nThese convey information about which value combinations are 'unusual' under the assumption of independence between row and column variables.\n\n- positive residual: larger-than-expected count\n- negative residual: smaller-than-expected count\n\nYou can retrieve the residuals from the test and inspect for the largest (absolute) values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# view residuals\nasthma.rslt$residual\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n             asthma  no asthma\n  female  1.3788982 -0.3113006\n  male   -1.4053932  0.3172821\n```\n\n\n:::\n:::\n\n\nHere, the residuals suggest that asthma rates are higher than expected among women and lower than expected among men.\n\n::: callout-note\n## Your turn 3\n\nCheck the residuals from your inference of whether diabetes medication is associated with cardiovascular problems. See if you can explain any inferred association.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check residuals from your inference above; what explains the association?\n```\n:::\n\n:::\n\n#### Measuring association by a difference in proportions\n\nOnce you've inferred an association between two categorical variables, it's helpful to be able to provide a quantitative measure. \n\nA difference in proportions is one potential measure, though not always possible to compute (*e.g.*, for outcome-based sampling). Here, since data are a random sample from the target population (U.S. adults), we can estimate the difference in the proportion of individuals with asthma between men and women:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use prop.test to get estimates and confidence interval\ntable(asthma$sex, asthma$asthma) |>\n  prop.test(conf.level = 0.90)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  table(asthma$sex, asthma$asthma)\nX-squared = 3.6217, df = 1, p-value = 0.05703\nalternative hypothesis: two.sided\n90 percent confidence interval:\n 0.002841347 0.040137075\nsample estimates:\n    prop 1     prop 2 \n0.05903614 0.03754693 \n```\n\n\n:::\n:::\n\n\nFor a report, we'd combine this with the inferred association as follows:\n\n> The data provide suggestive but insufficient evidence at the 5% significance level that sex and asthma prevalence are associated ($\\chi^2$ = 3.62 on 1 degree of freedom, *p* = 0.057). With 90% confidence, asthma prevalence is estimated to be between 0.28 and 4.01 percentage points higher among women compared with men, with a point estimate of 2.15 percentage points.\n\n(A 90% interval is reported, not consistent with the significance level of the test, to point to the direction of possible association.)\n\n::: callout-note\n## Your turn 4\n\nProvide point and interval estimates for the difference in proportions of patients experiencing cardiovascular problems on each diabetes medication as a measure of association. \n\n(Unlike the example above, your confidence level for the interval should match the significance level of your test, as usual.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# estimate the difference in proportions of patients experiencing cardiovascular problems\n```\n:::\n\n\n:::\n\n### Inference for $I \\times J$ tables\n\nThe implementation of the $\\chi^2$ test is identical for larger tables, as are the means of obtaining expected counts and residuals from the test. The only difference is the check on assumptions. For $I\\times J$ tables, the following two conditions should be met:\n\n1. All expected counts are at least 1\n2. Roughly 80% or more of expected counts are at least 5\n\nThe commands below illustrate the implementation, assumption check, and residual analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# perform test\nfamuss.rslt <- table(famuss$race, famuss$genotype) |>\n  chisq.test()\n\n# check expected counts to assess assumptions\nfamuss.rslt$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            \n                     CC        CT         TT\n  African Am   7.850420  11.84370   7.305882\n  Asian       15.991597  24.12605  14.882353\n  Caucasian  135.783193 204.85210 126.364706\n  Hispanic     6.687395  10.08908   6.223529\n  Other        6.687395  10.08908   6.223529\n```\n\n\n:::\n\n```{.r .cell-code}\n# interpret test result\nfamuss.rslt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table(famuss$race, famuss$genotype)\nX-squared = 19.4, df = 8, p-value = 0.01286\n```\n\n\n:::\n\n```{.r .cell-code}\n# residual analysis\nfamuss.rslt$residuals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            \n                      CC          CT          TT\n  African Am  2.90863193 -1.69802497 -0.85310170\n  Asian       1.25242978 -1.24720387  0.28971360\n  Caucasian  -0.92538910  0.77888407 -0.03244366\n  Hispanic   -1.03920927 -0.02804356  1.11294757\n  Other       0.12088363  0.28678513 -0.49045147\n```\n\n\n:::\n:::\n\n\nThe interpretation of this result would be:\n\n> The data provide moderate evidence of an association between genotype and race for the ACTN3 gene ($\\chi^2$ = 19.4 on 8 degrees of freedom, *p* = 0.01286). \n\nWhile there isn't a standard style or language for the residual analysis, and appropriate interpretation would be:\n\n> The data further suggest that African American and Asian populations have higher-than-expected and lower-than-expected CC and CT genotype frequencies, respectively; and Hispanic populations have higher-than-expected and lower-than-expected TT and CC genotype frequencies, respectively.\n\nAs an aside, measures of association are trickier for $I\\times J$ tables; typically one would calculate a *set* of measures that capture pairwise comparisons.\n\n::: callout-note\n## Your turn 5\n\nTest for an association between genotype and sex.\n\n- check the test assumptions\n- assuming they are met, interpret the test \n- if the test is significant, carry out a residual analysis to explain the inferred association\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# perform test\n\n# check expected counts to assess assumptions\n\n# interpret test result\n\n# residual analysis\n```\n:::\n\n\n:::\n\n### Practice problems\n\n1. [L7] The `mammogram` dataset contains observations from a 30-year study to investigate the effectiveness of mammograms versus a standard non-mammogram breast cancer exam on survival. The study was conducted in Canada with 89,835 female participants: during a 5-year screening period, each woman was randomized to either receive annual mammograms or standard physical exams for breast cancer; the study recorded the number of breast cancer deaths during a 25-year follow-up period in each group. \n\n    a. Explain the hypotheses for the Chi-square test of association in words.\n    b. Check assumptions for the test.\n    c. If assumptions are met, test for association at the 5% significance level and report the result; if the test is significant, perform a residual analysis to explain the inferred association.\n    \n\n\n\n\n\n2. [L7] The `smoking` dataset contains observations from a retrospective case-control study in which smoking status was recorded for 86 lung cancer patients and 86 healthy patients.\n\n    a. Construct a contingency table of the data.\n    b. Which proportions are possible to estimate using data from this study?\n    c. Check assumptions for the $\\chi^2$ test of association.\n    d. If assumptions are met, perform the test at the 5% level. Interpret the result in the usual narrative style.\n    e. (Extra credit) Make a plot of the residuals that allows you to identify which group/outcome combinations differ from expectations under independence.\n    \n\n\n\n\n3. [L6] The `gss` data contains several demographic measurements for a random sample of 500 U.S. adults.\n\n    a. Provide a point estimate for the proportion of U.S. adults with a college degree.\n    b. Provide a 99% confidence interval for the proportion. Interpret the interval in context.\n    c. Test whether at least three in ten U.S. adults have a college degree at the 5% significance level. If the result is significant, provide a corresponding lower confidence bound.\n\n\n\n\n\n4. [LX] (Extra credit) Again using the `gss` data, test whether political party is associated with socioeconomic class.\n\n    a. Check assumptions for the test.\n    b. If appropriate, perform the test at the 1% significance level. Interpret the result in context, and if a significant association is found, perform a residual analysis to explain the inferred association.\n\n\n",
    "supporting": [
      "lab12-association_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}