{
  "hash": "b3c26db5887fd592bf8a89a4aac7abda",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 4: Point and interval estimation for a population mean\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  message: false\nformat: \n  html:\n    toc: true\n  docx:\n    toc: false\nprefer-html: true\nembed-resources: true\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload('data/nhanes.RData')\nload('data/temps.RData')\n```\n:::\n\n\nThe goal of this lab is to learn to compute a point estimate, standard error, and interval estimate for a population mean \"by hand\" by performing the arithmetic directly in R. You will have an opportunity to practice interpreting these quantities as you go.\n\nWe will also use this lab for a short class activity to explore how often the interval estimate we introduced is \"correct\".\n\n### Point estimation\n\n#### Estimate for the population mean\n\nSince the point estimate for the population mean of a numeric variable is the sample mean, you already know how to perform the calculation in R. We'll store this for later use:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# retrieve total cholesterol variable\ntotchol <- nhanes$totchol\n\n# compute and store sample mean\ntotchol.mean <- mean(totchol)\ntotchol.mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.042938\n```\n\n\n:::\n:::\n\n\nThe only novelty here is that we now interpret this as a point estimate of the population mean total cholesterol:\n\n> The mean total cholesterol of U.S. adults is estimated to be 5.043 mmol/L.\n\nThis is in contrast to the interpretation as a descriptive summary:\n\n> The average total cholesterol among the respondents in the NHANES survey was 5.043 mmol/L.\n\nBoth interpretations are valid; just different. By interpreting the sample mean as a point estimate, we are implicitly assuming that the data are a random sample from the U.S. adult population.\n\n::: callout-note\n## Your turn\n\nUse the `temps` data to estimate mean body temperature.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# retrieve variable of interest\n\n# compute and store sample mean\n```\n:::\n\n\n*Check your understanding:*\n\n- interpret the result as a descriptive summary\n- interpret the result as a point estimate\n\n:::\n\n#### Standard error for the sample mean\n\nA standard error is a measure of the sampling variability of a point estimate. Technically, it's an estimate of the point estimate's standard deviation across all possible random samples of a fixed size.\n\nThe standard error for the sample mean is calculated according to the formula:\n$$SE(\\bar{x}) = \\frac{s_x}{\\sqrt{n}}$$\nWhere:\n\n- $s_x$ is the sample standard deviation\n- $n$ is the sample size\n\nTo calculate this in R, we perform the arithmetic by hand (for now):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# store sample sd and sample size\ntotchol.sd <- sd(totchol)\ntotchol.n <- length(totchol)\n\n# compute standard error\ntotchol.se <- totchol.sd/sqrt(totchol.n)\ntotchol.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01906042\n```\n\n\n:::\n:::\n\n\nThis result is interpreted as follows:\n\n> The root average deviation of the sample mean from the population mean is estimated to be 0.0191 mmol/L.\n\n::: callout-note\n## Your turn\n\nCalculate and interpret the standard error for the sample mean of the body temperature variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# store sample sd and sample size\n\n# compute standard error\n```\n:::\n\n:::\n\n### Interval estimation\n\n#### Interval estimate for the mean\n\nA common interval for the population mean is:\n\n$$\\bar{x} \\pm \\underbrace{2\\times SE(\\bar{x})}_{\\text{margin of error}}$$\n\nFor now, we'll calculate this by directly performing the arithmetic. Later, you'll use commands that return interval estimates by default.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add/subtract two standard errors from the mean\ntotchol.mean + c(-2, 2)*totchol.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.004817 5.081059\n```\n\n\n:::\n:::\n\n\nWe'll talk more about the exact interpretation later; for now, you should think of this as a range of plausible values for the population mean.\n\n::: callout-note\n## Your turn\n\nCalculate an interval estimate for the mean body temperature using the body temperature data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# interval estimate for mean body temp\n```\n:::\n\n:::\n\n#### How often is the interval correct?\n\nAn interval \"covers\" the population mean if the true value is between the interval endpoints. \n\nWe can explore how often the interval covers the parameter by having everyone in the class simulate their own sample from a population with a known mean and check whether the interval they obtain from the sample covers the population mean or not.\n\nThe commands below simulate a sample and then compute an interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# function to simulate body temp data from a population with mean 98.6\nsample.bodytemps <- function(n){\n  rnorm(n, mean = 98.6, sd = 1)\n}\n\n# simulate a sample of body temperatures\nbodytemp <- sample.bodytemps(n = 150)\n\n# compute interval 'ingredients'\nbodytemp.mean <- mean(bodytemp)\nbodytemp.sd <- sd(bodytemp)\nbodytemp.n <- length(bodytemp)\nbodytemp.se <- bodytemp.sd/sqrt(bodytemp.n)\n\n# compute interval estimate\nbodytemp.mean + c(-2, 2)*bodytemp.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 98.37830 98.73712\n```\n\n\n:::\n\n```{.r .cell-code}\n# margin of error\n2*bodytemp.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1794082\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Your turn\n\nUse the example above to generate a sample of size 20 and compute an interval estimate for the mean body temperature. \n\nThen:\n\n1. Determine whether your interval covers the population mean.\n2. Compute the margin of error used in your interval ($2\\times SE(\\bar{x})$).\n\n\nRepeat with $n = 150$. Then fill out [this form](https://forms.office.com/r/dGtfLzavM6).\n:::\n\n### Practice problems\n\n1. Vu and Harrington exercise 4.1. Additionally:\n\n    e. Compute an interval estimate for the mean BGC of nests.\n    f. Supposing a sample of 30 nests returned exactly the same summary statistics, recompute your interval in (e). Is the margin of error smaller or larger?\n\n\n::: {.cell}\n\n:::\n\n\n2. The `brfss` dataset contains a measurement of body weight, `weight`, as well as a variable, `wtdesire`, that is the desired weight reported by respondents. \n\n    a. Estimate the mean difference between actual and desired weight. Report the point estimate and standard error.\n    b. Does the point estimate suggest that the average U.S. adult would prefer to lose or gain weight?\n    c. Compute an interval estimate for the mean difference between actual and desired weight.\n\n\n::: {.cell}\n\n:::",
    "supporting": [
      "lab4-estimation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}