project:
  type: website
  output-dir: docs
  resources: 
    - CNAME

website:
  title: "STAT218"
  google-analytics: "G-H3YKZX4J88"
  page-footer: "\u00a9 2023 Trevor Ruiz"
  navbar:
    background: dark
    foreground: light
    search: true
    left:
      - content/syllabus.qmd
      - materials.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto