---
title: "Applied Statistics for Life Sciences"
date: today
published-title: 'Updated'
format: 
  html:
    toc: true
  docx:
    toc: false
prefer-html: true
embed-resources: true
---

::: callout-note
## Announcements

Final grades posted; have a great summer!

:::

### Course information

Read the \[[course syllabus](content/syllabus.qmd)\] for detailed information on content, materials, learning outcomes, assessments, and course policies.

**Instructor:** Trevor Ruiz (he/him/his) \[[email](mailto:truiz01@calpoly.edu)\]

**Class meetings:**

-   \[Section 05\] 12:10pm — 2:00pm MW Construction Innovations Center Room C100
-   \[Section 06\] 2:10pm — 4:00pm MW Construction Innovations Center Room C100

**Office hours:** 8:10am — 11:00am Mondays 25-236 or Zoom \[[by appointment](https://calendly.com/tdruiz/office-hour)\]

**Preparing for class meetings:**

1.  Check the course website for posted reading, materials, and assignments.
2.  Complete readings *in advance* of the class meetings for which they are listed.
3.  Write down one question you have about the reading and bring it to class.
4.  Download and/or print a copy of the posted course notes (slides) for you to annotate and bring them to class.

**Completing assignments:**

One set of practice problems is included at the end of each lab; these problem sets are your homework assignments. You will often have some time to work on them during class, and they will be due by the following class period. To complete these assignments:

1.  Review the prompts included with the lab.
2.  Do your work (calculations, making plots, etc.) in the lab script provided in Posit Cloud.
3.  Follow the link that appears as \[[problem set N]{style="color:blue"}\] with the class meeting outline for the period in which the problem set was assigned. This will direct you to a form where you'll fill out select answers. Refer to your work in Posit Cloud as you complete the form.

Some general remarks:

-   problem sets are due one hour before the next class meeting
-   late submissions are accepted until 5pm two days after the due date
-   score summaries will be posted once all deadlines pass
-   once scores are posted, you can see your individual responses using the link that you used to access the form

### Week 1 (4/1/24)

*Academic holiday 4/1/24*

*Introduction to statistical thinking and study designs*

***Wednesday class meeting***

-   \[reading\] Vu and Harrington 1.1
-   \[[lecture](content/week1-studies.qmd)\] course introduction; study designs
-   \[[activity](content/week1-activity-studydesigns.qmd)\] distinguishing types of studies
-   \[[problem set 1](https://forms.office.com/r/Dx84ZpQRj8)\] due Monday 4/8; late submissions until Wednesday 4/10 5pm
-   \[[problem set 1 corrections](https://forms.office.com/r/w9zT40gg0g)\] due by 5pm Friday 4/12

Response summary \[[PS1](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=Ls9MDkAdjEwov16Rhl5hC6g8qYc2kNye&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUNjhQUEwxNDUwTlI4QTZXUVRDR0ZTQ1Y2Ti4u)\] \[[PS1 corrections](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=R5lQ4BfrgZtLcY64A3Upay0e1TUB9Vf8&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUQk9HUjlGWjNPRTNVUDVXTjVUQ0RRM1pZSC4u)\]

### Week 2 (4/8/24)

*Data types and descriptive statistics*

***Monday class meeting***

-   reading quiz \[[12pm section](https://forms.office.com/r/wf75D6mp8N)\] \[[2pm section](https://forms.office.com/r/RvZeF8pHq5)\]
-   \[reading\] Vu and Harrington 1.2
-   \[[lecture](content/week2-datatypes.qmd)\] data types
-   \[[lab](content/lab1-rbasics.qmd)\] R basics
-   \[[problem set 2](https://forms.office.com/r/B3rki1eexc)\] due Wednesday 4/10; late submissions until Friday 4/12 5pm

Response summary \[[PS2](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=gIw2RyBFskdA3YcQL8X8OydyYiJc3zzt&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUNDlBN1RKUlNZTlZSSVcwUTRYMk02TVlBRS4u)\]

***Wednesday class meeting***

-   \[reading\] Vu and Harrington 1.4 - 1.5
-   \[[lecture](content/week2-descriptive.qmd)\] descriptive statistics
-   \[[lab](content/lab2-descriptive.qmd)\] descriptive statistics in R
-   \[[problem set 3](https://forms.office.com/r/SPrm6BsYmH)\] due Monday 4/15; late submissions until Wednesday 4/17 5pm

Response summary \[[PS3](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=uj2KuL0OkeyQb3vNCdNs0Yh74aX20K7g&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUMjg4RTJVQjA5R0NPVU03UTJOR1dQRllLRi4u)\]

### Week 3 (4/15/24)

*Descriptive statistics and graphical summaries*

***Monday class meeting***

-   \[[reading quiz](https://forms.office.com/r/WtbJpaLeF6)\] Vu and Harrington 1.6
-   \[[lecture](content/week3-bivariate.qmd)\] descriptive statistics for relationships between two variables
-   \[[lab](content/lab3-bivariate.qmd)\] bivariate summaries in R
-   \[[problem set 4](https://forms.office.com/r/nhkHSubQya)\] due Wednesday 4/17; late submissions until Friday 4/19 5pm

Response summary \[[PS4](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=eChGDBUbsnnIQMmqnZyTbApHFbeiPva2&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUNUlINFVJVFc2WlM2M0xJSDBWMkpRNEo1SS4u)\]

***Wednesday class meeting***

-   \[reading\] review course notes and PS1, PS2, PS3 in detail
-   \[[review](content/week3-review.qmd)\] recap and Q&A
-   \[[test 1 practice problems](content/test1-practice.qmd)\] in groups with short solution presentations
-   \[[R cheatsheet](content/r-cheatsheet.qmd)\] for easy reference

**Test 1** available Wednesday 4/17 5pm and due Friday 4/19 5:00pm PDT \[[prompts](content/test1.qmd)\] \[[submission](https://forms.office.com/r/MSsz35jkyk)\] \[[upload R script](https://cpslo-my.sharepoint.com/:f:/g/personal/truiz01_calpoly_edu/En0PZq0Nx9VCsKlZfHnHuWwBCX_GqLPfm25qFnD-v1skKQ)\]

### Week 4 (4/22/24)

*Foundations for inference*

**Monday class meeting**

-   \[reading\] Vu and Harrington 4.1
-   \[[lecture](content/week4-inference.qmd)\] point estimation, sampling variability, and interval estimation
-   \[[lab](content/lab4-estimation.qmd)\] point and interval estimation for a population mean
-   \[[problem set 5](https://forms.office.com/r/PCFv67h4N2)\] due Wednesday 4/24; late submissions until Friday 4/26 5pm

Response summary \[[PS5](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=QVcRfRBN6S2KgKhuLttFRyDPQOYB5UX1&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUQ0w4QVJJMTFYMVFWSEFYUFdXQlk5RE05Vy4u)\]

***Wednesday class meeting***

-   \[[reading quiz](https://forms.office.com/r/0p39JMNVXv)\] Vu and Harrington 3.3.1, 3.3.2, and 3.3.3; and 4.2
-   \[[lecture](content/week4-intervals.qmd)\] constructing and interpreting confidence intervals
-   \[[lab](content/lab5-intervals.qmd)\] computing confidence intervals

**Test 1 corrections** due Friday 4/26 5pm \[[submit corrections](https://forms.office.com/r/W7Z7z0zBe3)\]

### Week 5 (4/29/24)

*One-sample inference for numerical data*

***Monday class meeting*** 

-   \[reading\] Vu and Harrington 4.3.1 & 4.3.2
-   \[[lecture](content/week5-hypothesis.qmd)\] the $t$-test for a population mean
-   \[[lab](content/lab6-hypothesis.qmd)\] computing test statistics, critical values, and $p$-values
-   \[[problem set 6](https://forms.office.com/r/kRQXphHZvf)\] due Wednesday 5/1; late submissions until Friday 5/3 5pm

Response summary \[[PS6](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=SP4bWIqcd8ErxkPhArkhqRmjHBsR26LU&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUMkZWNFVPSzk5RTlVUTNUNDRHMEFFNzBIRi4u)\]

***Wednesday class meeting***

-   \[reading\] Vu and Harrington 4.3.3 & 4.3.4
-   \[[lecture](content/week5-directional.qmd)\] directional tests
-   \[[lab](content/lab7-directional.qmd)\] directional tests
-   \[[problem set 7](https://forms.office.com/r/yJUqiKxMB4)\] due Monday 5/6; late submissions until Wednesday 5/8 5pm

Response summary \[[PS7](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=fOTcCJw2uloFlsCwZsHFr79jKLoe2KnC&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUOUFKMTRWMFMxRUU2WUlUOUJUSzA1SllBRC4u)\]

### Week 6 (5/6/24)

*Two-sample inference for numerical data*

Please complete this short \[[midquarter feedback survey](https://forms.office.com/r/Q1bVRsyRdW)\] by Friday 5/10. Responses are anonymous.

***Monday class meeting***

-   \[reading\] Vu and Harrington 5.3
-   \[[lecture](content/week6-twosample.qmd)\] two-sample inference
-   \[[lab](content/lab8-twosample.qmd)\] two-sample *t* tests in R
-   \[[problem set 8](https://forms.office.com/r/1Ng8ZivYQr)\] due Wednesday 5/8; late submissions until Friday 5/10

Response summary \[[PS8](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=SUI1bDv0qCPbd7eHHhT9yGstkXzXLO8H&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JURFMxSVMzNzNYQ1JBRVExSFVCM1RBQlMwUC4u)\]

***Wednesday class meeting*** 

-   \[reading\] Vu and Harrington 5.4
-   \[[lecture](content/week6-power.qmd)\] decision errors; statistical power
-   \[[test 2 practice problems](content/test2-practice.qmd)\] test 2 prep
-  \[[R cheatsheet](content/r-cheatsheet.qmd)\] for easy reference

**Test 2** available Wednesday 5/8 5pm and **due Friday 5/10 5pm** \[[prompts](content/test2.qmd)\] \[[submission form](https://forms.office.com/r/CRwzpweBj3)\] \[[upload R script](https://cpslo-my.sharepoint.com/:f:/g/personal/truiz01_calpoly_edu/EmSk3Moe44lOlP40RSzplMsBUuThnHBe_QnW89dbeC6Sgw)\] \[[submit corrections](https://forms.office.com/r/pegkk8F7Ky)\]

### Week 7 (5/13/24)

*Analysis of variance*

***Monday class meeting*** 

-   \[reading\] Vu and Harrington 5.5.1 & 5.5.2
-   \[[lecture](content/week7-anova.qmd)\] Introduction to analysis of variance
-   \[[lab](content/lab9-anova.qmd)\] fitting ANOVA models in R

***NO Wednesday class meeting***

-   \[reading\] van Belle *et al.* 8.4 and 8.5 up to 8.5.4
-   \[[self-paced activity](content/week7-activity-nonparametric.qmd)\] nonparametric inferences for one- and two-sample problems
-   \[[problem set 9](https://forms.office.com/r/mwb8DCkjAH)\] due Monday 5/20; late submissions until Wednesday 5/22 5pm

Response summary \[[PS9](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=99Gk18qGZyH7amO75sdNmG5EA7XOTHC4&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUOTNCQVNLRkZLN0U1Wkw4VTJVS0FNWVVZSS4u)\]

### Week 8 (5/20/24)

*Post hoc inference in ANOVA; inference for a population proportion*

***Monday class meeting***

-   \[reading\] Vu and Harrington 5.5.3 & 5.5.4
-   \[[lecture](content/week8-posthoc.qmd)\] post hoc inference in ANOVA
-   \[[lab](content/lab10-posthoc.qmd)\] pairwise comparisons in R
-   \[[problem set 10](https://forms.office.com/r/9aNk6EdFH3)\] due Wednesday 5/22; late submissions until Friday 5/24 5pm

Response summary \[[PS10](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=t6uf4scBfMi73nO9R1Mik8HcyOB6Ec2p&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUMFVWM0FVTUlYTFdMOUNZVzI1QUQxSTlPRS4u)\]

***Wednesday class meeting***

-   \[reading\] Vu and Harrington 8.1 & 8.2
-   \[[lecture](content/week8-proportions.qmd)\] inference for population proportions
-   \[[lab](content/lab11-proportions.qmd)\] tests and intervals for proportions in R

**Test 3** available Wednesday 5/22 5pm PDT and due Friday 5/24 5:00pm PDT \[[prompts](content/test3.qmd)\] \[[submission](https://forms.office.com/r/ZPv3rH7ApW)\] \[[upload R script](https://cpslo-my.sharepoint.com/:f:/g/personal/truiz01_calpoly_edu/EmXT2uLj-BdIhi6xGpcEzsQBEl-SLY_YJbpM1opHddTDow)\] \[[submit corrections](https://forms.office.com/r/Jm0zGxTJ1v)\]

### Week 9 (5/27/24)

*Academic holiday 5/27/24; Tuesday follows Monday schedule*

*Analysis of two-way contingency tables*

***Tuesday class meeting*** 

- [reading] Vu and Harrington 8.3 (excluding 8.3.5)
- \[[lecture](content/week9-association.qmd)\] tests of association in two-way tables
- \[[lab](content/lab12-association.qmd)\] $\chi^2$ tests in R
- \[[problem set 11](https://forms.office.com/r/M4mrCXPPNV)\] due Wednesday 5/29; late submissions until Friday 5/31 5pm 

Response summary \[[PS11](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=kknTw8zMRFaZSr9ZZYk6rRORNi5zFPrH&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUOENCR0hKWk82QlZQNVFURkZHTTlNTDRSRy4u)\]

***Wednesday class meeting*** 

- [reading] Vu and Harrington 8.5
- \[[lecture](content/week9-measures.qmd)\] inference for odds ratios and relative risk
- \[[lab](content/lab13-measures.qmd)\] measures of association in R
- \[[problem set 12](https://forms.office.com/r/8Mj9aZczeh)\] due Monday 6/3; late submissions until Wednesday 6/5 5pm

Response summary \[[PS12](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=4BtgT8kF1FMCz0nLYYBHaYaPWCWvxirO&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUOUFOWUJKMjRINUtHUVBERFpVODZGOFFEVy4u)\]

### Week 10 (6/3/24)

*Simple linear regression*

**NO Monday class meeting** 

- [reading] Vu and Harrington 6.1 & 6.2
- \[[activity](content/week10-activity-linefitting.qmd)\] warm-up for simple linear regression: line fitting
- \[[problem set 13](https://forms.office.com/r/RjGTLNs4E8)\] due Wednesday 6/5; late submissions until Friday 6/7 5pm

**Wednesday class meeting** 

- [reading] Vu and Harrington 6.4
- \[[lecture](content/week10-slr.qmd)\] inference in simple linear regression
- \[[lab](content/lab14-slr.qmd)\] estimating the age of the universe
- [miscellany] scheduling oral exam times; course evals

**Test 4** due Friday 6/7 5:00pm PDT \[[prompts](content/test4.qmd)\] \[[submission form](https://forms.office.com/r/7YK3995ZMW)\] \[upload R script\]

### Finals week (6/10/24)

*Oral exams to be held during scheduled exam time*

Scheduled exam times:

-   \[12pm section\] Wednesday 6/12 10:10am -- 1:00pm
-   \[2pm section\] Monday 6/10 1:10pm -- 4:00pm

\[[project guidelines](content/project-guidelines.qmd)\] \[[schedule](https://cpslo-my.sharepoint.com/:x:/g/personal/truiz01_calpoly_edu/EdV0eGagGR1InmT9Ii34eugBJYzySTgWxrQ0n1a45uZLgw?e=k41wBc)\] \[[upload deliverable](https://cpslo-my.sharepoint.com/:f:/g/personal/truiz01_calpoly_edu/EhaExyR2xtFKqVLlJm2dy6cB1hTx5xIkRCWRwF2f_CPBSA)\]
