---
title: "Materials"
title-block-style: none
---

Refer to this page for a detailed schedule of coursework and links to all materials. This information is organized by week, and you should check this page on a weekly basis for updates as the quarter progresses.

I will aim to post/update outlines for class meetings at the beginning of each week (Monday), and update with links to relevant materials as the week progresses. So, you should look at the beginning of the week to see what's ahead, and check back for newly posted materials before and after class meetings.

### Preparing for class meetings

-   Complete readings *in advance* of the class meetings for which they are listed. Take notes or make annotations, and bring your notes to class.
-   Download and/or print copies of posted slides and handouts and bring these to class.
-   If a lab is indicated, it is recommended that you bring your laptop/tablet. While these are group activities and it is an option to share, you will not have direct access to your groupmates' work after the class meeting.

### Week 1 (1/8/24)

*Introduction to statistical thinking and study designs*

***Tuesday class meeting*** \[[slides](content/week1-welcome.qmd)\]

-   \[lecture/discussion\] course introduction and syllabus review
-   \[activity\] working groups and icebreakers
-   \[activity\] orientation to posit.cloud

***Thursday class meeting***: \[[slides](content/week1-studydesigns.qmd)\] \[[handout](content/week1-handout-designs.qmd)\]

-   \[reading\] van Belle *et al.* 2.1 - 2.5; Vu and Harrington 1.1
-   \[lecture/discussion\] study designs
-   \[activity\] distinguishing types of studies
-   \[case study\] preventing peanut allergies

Reading quiz responses: \[[2pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=BRavUuC3mcIkNNXdgJplZoGVfDzDldyL&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JURDJZTzI2QlNDQU45Q0lZUkpXVDUyVTVKNi4u)\] \[[4pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=MM7Fxw3jbMjsKyEUlWTgwQIIAJctozRV&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUOEhLR0U2Mjg1MEFTWjcyOFFNMTFNMVE1Ti4u)\]

**Assignment**: \[[HW1](content/hw/hw1.qmd)\] due Thursday 1/18 11:59pm PST \[L1, L2\]

### Week 2 (1/15/24)

*Academic holiday 1/15/24 and Monday class schedule on 1/16/24*

*Introduction to data and data types*

***Thursday class meeting*** \[[slides](content/week2-datatypes.qmd)\] \[[lab](content/labs/lab1-rbasics.qmd)\]

-   \[reading\] Vu and Harrington 1.2; Douglas *et al.* 3.1 - 3.2
-   \[lecture/discussion\] data types and data structures
-   \[activity\] distinguishing data types in practice
-   \[lab\] R basics and data in R

Reading quiz responses: \[[2pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=pi0hBvCi1pUbJUaKT4AdEuFnc0s2ZmmU&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JURVoxMEVUV05HM1VYQVhHSERVM01HSFhNVi4u)\] \[[4pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=V1rv4HOREiKHtDUfkdPCyKBF3VVmefvn&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUNktRTE4zRVlXWTJHUTFYVjc2VzJTNk1ZNS4u)\]

**No assignment this week**

### Week 3 (1/22/24)

*Descriptive statistics and graphical summaries*

***Tuesday class meeting*** \[[slides](content/week3-descriptive.qmd)\] \[[lab](content/labs/lab2-descriptive.qmd)\]

-   \[reading\] Vu and Harrington 1.4 - 1.5; van Belle *et al.* 3.4
-   \[lecture/discussion\] descriptive statistics for numerical and categorical data
-   \[lab\] descriptive statistics in R; robustness
-   \[case study\] functional SNPs associated with muscle strength and size (FAMuSS)

***Thursday class meeting*** \[[slides](content/week3-multivariate.qmd)\] \[[lab](content/labs/lab3-multivariate.qmd)\]

-   \[reading\] Vu and Harrington 1.6
-   \[lecture/discussion\] descriptive statistics for relationships between two variables
-   \[lab\] bivariate summaries in R
-   \[case study\] FAMUSS

Reading quiz responses: \[[2pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=ScewzsvfXG3Z23dXhkvoa5xXc9Ssyj3b&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUNDg0NTBRMU4zVVdHS0pCRFJMMFgyTkNaSy4u)\] \[[4pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=uRZDIjUtNk5kVIAH34siEo2jna1OaPzm&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUNlpYSlJXS0dNWEFOTVhMMlczVVdTMEZWNy4u)\]

**Assignment**: extended to next week

### Week 4 (1/29/24)

*Foundations for inference*

**Tuesday class meeting** \[[slides](content/week4-sampling.qmd)\] \[[lab](content/labs/lab4-sampling.qmd)\]

-   \[reading\] Vu and Harrington 4.1
-   \[lecture/discussion\] sampling and sampling distributions
-   \[lab\] exploring sampling variability
-   \[case study\] National health and nutrition examination survey (NHANES)

Reading quiz responses: \[[2pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=abJbRahZT6EfbMRDZPqu7vKMtMhz64jw&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUQUdNOVJDRTE3RDFENUQ4VDgzSlo3WjRRRy4u)\] \[[4pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=1I0Xu6SsqUefvaNvNJNJL1kMjVXpZj0a&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUQ05HSjU1SENHUlFLM0cxME9GTFdTS0lKVS4u)\]

***Thursday class meeting*** \[[slides](content/week4-intervals.qmd)\] \[[lab](content/labs/lab5-intervals.qmd)\]

-   \[reading\] Vu and Harrington 3.3.1, 3.3.2, and 3.3.3; and 4.2
-   \[lecture/discussion\] interval estimation for a population mean
-   \[lab\] computing confidence intervals in R
-   \[case study\] NHANES

**Assignment**: \[[HW2](content/hw/hw2.qmd)\] due Thursday 2/8 11:59pm PST \[L3, L4\]

### Week 5 (2/5/24)

*One-sample inference for numerical data*

***Tuesday class meeting*** \[[slides](content/week5-hypothesis.qmd)\] \[[lab](content/labs/lab6-hypotesting.qmd)\]

-   \[reading\] Vu and Harrington 4.3
-   \[lecture/discussion\] hypothesis tests for a population mean
-   \[lab\] one-sample $t$ tests <!--# simulation -->
-   \[case study\] DDT in kale <!--# MASS::DDT -->

Reading quiz responses: \[[2pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=ZjeI3hXRae1NmTtS5xx1laWP4ptsrgMo&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUMjk4WkQwQ1ZRTUE1OVpHNjI1UkdEVVM4NC4u)\] \[[4pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=Pmk0kXjNRYNodZ8Yr1ykJ5ZcDLgKpdDN&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUM1ZQWEM1U0xPRlIzRTZMOFBXT1lWVFNSUS4u)\]

***Thursday class meeting*** \[[slides](content/week5-moretests.qmd)\] \[[lab](content/labs/lab7-moretests.qmd)\]

-   \[reading\] Vu and Harrington 5.1
-   \[lecture/discussion\] interpreting hypothesis tests and understanding decision errors
-   \[lab\] exploring decision errors
-   \[case study\] is true body temperature 98.6F?

Reading quiz responses: \[[2pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=P3sAMZD9qKiC1QD4UfnAqyvvtHU4CDVI&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUQjJCQk84M0I5SFRUMzhLVFNPMThRTTVNTy4u)\] \[[4pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=ESjim0JqIuyPuDeYUKbYVsz3PVmaabEz&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUME5DSE5YM1BDQU5aOEVWRVhSWUNYTk41MS4u)\]

**Assignment**: \[[Test 1](content/tests/test1.qmd)\] due Saturday 2/10 11:59pm PST \[L1, L2, L3\]

### Week 6 (2/12/24)

*Two-sample inference for numerical data*

***Tuesday class meeting*** \[[slides](content/week6-twosample.qmd)\] \[[lab](content/labs/lab8-twosample.qmd)\]

-   \[reading\] Vu and Harrington 5.2 and 5.3
-   \[lecture/discussion\] two-sample *t* tests and intervals for paired and independent data
-   \[lab\] two-sample *t* tests <!--# cloud seeding, case0301; oibiostat::swim -->
-   \[case study\] evolution of Darwin's finches <!--# Sleuth3::case0201, bio -->

Reading quiz responses: \[[2pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=MRuvcxt3UnzYCaESALCQ0HxfqwSiQeWQ&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUNjZBSEJIU1g2TDMwTThUNlM0MTBMTUM3WS4u)\] \[[4pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=aIDjE9mM0bJJymQk4KhQpTJp1x801yE3&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUQUFLWVJURjBJUEFJNVdCVUdKVlNHNkUzRS4u)\]

**Thursday class meeting** \[[slides](content/week6-power.qmd)\] \[[lab](content/labs/lab9-power.qmd)\]

-   \[reading\] Vu and Harrington 5.4; van Belle *et al.* 8.4 and 8.5 up to 8.5.4
-   \[lecture/discussion\] statistical power calculations for two-sample inference
-   \[lab\] post hoc and study design power analyses in R

Reading quiz responses: \[[2pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=soTSWsPn7c8kBRKEbKmPsVqQoCrl9BBS&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUMDVBMFZHWVJOTUZEQU5BQU05VFhKMldENS4u)\] \[[4pm section](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=tB7L1tfZDA41fw1YCaEmqTpSemcNRRO4&id=2wING578lUSVNx03nMoq5-gaHVrHunBOktETcNXub2JUM1ZOWDBLSVJFRzZMWjk0TFZWMUJMWUE3Ty4u)\]

***Assignment***: \[[HW3](content/hw/hw3.qmd)\] due Thursday 2/22 11:59pm PST \[L4, L5\]

### Week 7 (2/19/24)

*Nonparametric tests; analysis of variance*

*Academic holiday 2/19/24*

**Tuesday class meeting** \[[slides](content/week7-nonparametric.qmd)\] \[[lab](content/labs/lab10-nonparametric.qmd)\]

-   \[reading\] van Belle *et al.* 8.4 and 8.5 up to 8.5.4
-   \[lecture/discussion\] nonparametric inferences for one- and two-sample problems
-   \[lab\] three case studies
- Please complete feedback survey by Thursday 2/22 \[[2pm section](https://forms.office.com/r/TaS2EPd6yX)\] \[[4pm section](https://forms.office.com/r/Fw7a8CYQZP)\]



**Thursday class meeting** 

-   \[reading\] Vu and Harrington 5.5
-   \[lecture/discussion\] analysis of variance
-   \[lab\] grouped summaries; ANOVA in R

***Assignment***: HW4 due Thursday 2/29 11:59pm PST \[L9\]

<!--# anorexia on body weights (MASS); case0501; -->

### Week 8 (2/26/24)

*Inference for categorical data*

***Assignment***: Test 2 due Friday 3/1 11:59pm PST \[L4, L5, L9\]

<!--# smoking and lung cancer case1802 case1803 -->

### Week 9 (3/4/24)

*Simple linear regression*

<!--# big bang -->

***Assignment***: HW5 due Thursday 3/14 11:59pm PST \[L6, L7, L8\]

### Week 10 (3/11/24)

*Simple linear regression*

<!--# big bang -->

***Assignment***: Test 3 due Friday 3/15 11:59pm PST \[L6, L7, L8, L10\]

### Finals week (3/18/24)

*Oral exams to be held during scheduled exam time*
