{
  "hash": "13feb2165187c97cf20bfd2b6be75f26",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 9: Analysis of variance\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  echo: true\n  eval: true\n  message: false\n  warning: false\n  results: 'markup'\nformat: html\n---\n\n\n\nThe goal of this lab is to learn how to implement analysis of variance (ANOVA) in R. In its most basic form, this comprises three steps: a visual check of the data, fitting a model and generating the ANOVA table, and interpreting results.\n\nRemember throughout that the first goal of an analysis of variance is to test the hypothesis of no difference in means (interpreted as no effect in the case of an experiment with random treatment allocation). In notation:\n\n$$\n\\begin{cases}\nH_0: &\\mu_1 = \\mu_2 = \\cdots = \\mu_k \\\\\nH_A: &\\mu_i \\neq \\mu_j \\text{ for some } i \\neq j\n\\end{cases}\n$$\n\nThis is essentially an extension of the two-sample $t$ test to arbitrarily many means. We'll use the `chicks` dataset to illustrate these steps and you'll reproduce using the `anorexia` dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload('data/chicks-20d.RData')\nanorexia <- read_csv('data/anorexia.csv')\n```\n:::\n\n\n\n### Preliminaries\n\nAnalysis of variance should start with a brief descriptive analysis: calculation of groupwise summary statistics and visualization of the data by group. The following choices for summary statistics and visualization are standard:\n\n- means, standard deviations, and sample sizes, since inference in ANOVA is based on these statistics\n- boxplots, since in an ANOVA there will be more than two groups\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# groupwise summaries: mean, sd, and n\nchicks |>\n  group_by(diet) |>\n  summarize(mean = mean(weight),\n            sd = sd(weight),\n            n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  diet   mean    sd     n\n  <fct> <dbl> <dbl> <int>\n1 1      170.  55.4    17\n2 2      206.  70.3    10\n3 3      259.  65.2    10\n4 4      234.  37.6     9\n```\n\n\n:::\n\n```{.r .cell-code}\n# boxplots by group\nboxplot(weight ~ diet, data = chicks)\n```\n\n::: {.cell-output-display}\n![](lab9-anova_files/figure-html/descriptive analysis prior to ANOVA-1.png){width=672}\n:::\n:::\n\n\nWhile descriptive analysis is useful in and of itself for summarizing the data -- here you can see that chicks on diet 3 grew most, and the average weight in this group was 258.9 grams -- it also provides a means for assessing ANOVA model assumptions:\n\n- symmetry and unimodality within each group\n- similar variation (standard deviation or variance) across groups\n\nGreater departures are tolerable for larger sample sizes. In this instance, sample sizes are modest (9-17), so we should expect both that (a) plots and summary statistics will be tricky to assess and (b) some departure from assumptions is okay.\n\nMost of the time, you'll only be looking for major departures, so try not to be too sensitive to unequal standard deviations or skewness in boxplots.\n\n::: callout-note\n## Your turn 1\n\nProduce descriptive summaries -- boxplots and summary statistics -- for the `change` variable in the `anorexia` dataset. (This is the difference between pre-treatment and post-treatment weight, computed as post - pre.) Discuss whether assumptions for ANOVA are plausible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# groupwise summaries: mean, sd, and n\n\n# boxplots by group\n```\n:::\n\n:::\n\n### Fitting ANOVA models with `aov(...)`\n\nFitting an ANOVA model is fairly straightforward in R. The call is:\n\n```aov(formula = <RESPONSE> ~ <GROUP>, data = <DATAFRAME>)```\n\nWhere `<RESPONSE>` is the name of the variable of interest in `<DATAFRAME>` and `<GROUP>` is the name of the grouping variable. These should match exactly the syntax you use to make your boxplot.\n\nWhen you run the example lines below, make sure to inspect the output at each stage. Look specifically to identify the parts of the analysis of variance we discussed in class:\n\n- the fitted ANOVA model displays only sums of squares, degrees of freedom, and a pooled estimate of the standard deviation of data values about the group means (\"residual standard error\")\n- the output of `summary(...)` is required to obtain mean squares, the $F$ statistic, and the $p$-value for the test\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit anova model\nfit <- aov(formula = weight ~ diet, data = chicks)\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\n   aov(formula = weight ~ diet, data = chicks)\n\nTerms:\n                     diet Residuals\nSum of Squares   55881.02 143190.31\nDeg. of Freedom         3        42\n\nResidual standard error: 58.38915\nEstimated effects may be unbalanced\n```\n\n\n:::\n\n```{.r .cell-code}\n# construct anova table\nsummary.aov(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \ndiet         3  55881   18627   5.464 0.00291 **\nResiduals   42 143190    3409                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\nThis is all that is needed to report the result of the test. At the 1% level, the test is significant (null hypothesis rejected) since $p < 0.01$, so the result is:\n\n> The data provide evidence that diet has an effect on mean weight among chicks (*F* = 5.46 on 3 and 42 degrees of freedom, *p* = 0.00291).\n\n::: callout-note\n## Your turn 2\n\nTest for an effect of therapeutic treatment on mean weight change among anorexia patients. Fit the ANOVA model using `aov(...)` and generate the ANOVA table using `summary.aov(...)`. Interpret the result in context.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit anova model\n\n# construct anova table\n```\n:::\n\n:::\n\n### Computing the $p$-value directly\n\nOccasionally you'll have sums of squares provided to you and will need to complete an ANOVA test \"by hand\". In this case you'll need to refer to the layout of the table to remember the following:\n\n- $\\text{mean square} = \\frac{\\text{sum square}}{\\text{df}}$\n- $F = \\frac{\\text{mean square for groups/treatment}}{\\text{mean square error}}$\n- $p\\text{-value} = P(F_{k - 1, n - k} > F)$\n\nThe calculations would look something like what is shown below. You'll have to imagine that in place of extracting sums of squares and degrees of freedom from a fitted ANOVA model, you'd plug them in directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# view ss and df\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\n   aov(formula = weight ~ diet, data = chicks)\n\nTerms:\n                     diet Residuals\nSum of Squares   55881.02 143190.31\nDeg. of Freedom         3        42\n\nResidual standard error: 58.38915\nEstimated effects may be unbalanced\n```\n\n\n:::\n\n```{.r .cell-code}\n# run but ignore -- this extracts sums of squares and degrees of freedom\nfit.ss <- summary.aov(fit)[[1]]$`Sum Sq`\nfit.df <- summary.aov(fit)[[1]]$Df\nnames(fit.df) <- names(fit.ss) <- c('treatment', 'error')\n\n# mean squares\nfit.ms <- fit.ss/fit.df\nfit.ms\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntreatment     error \n18627.007  3409.293 \n```\n\n\n:::\n\n```{.r .cell-code}\n# f statistic\nfstat <- fit.ms['treatment']/fit.ms['error']\nfstat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntreatment \n 5.463598 \n```\n\n\n:::\n\n```{.r .cell-code}\n# p value\npf(fstat, df1 = fit.df['treatment'], df2 = fit.df['error'], lower.tail = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  treatment \n0.002909054 \n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Your turn 3\n\nCompute the $F$ statistic and $p$-value manually for the test you performed above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plug in the sums of squares and degrees of freedom from your fitted model above\nfit.ss <- c(614.644, 3910.742)\nfit.df <- c(1, 1) # REPLACE\nnames(fit.df) <- names(fit.ss) <- c('treatment', 'error')\n\n# mean squares\n\n# f statistic\n\n# p value\n```\n:::\n\n\n:::\n\n### Practice problems\n\nIn a study[^1], female mice were randomly assigned to six treatment groups to investigate whether restricting dietary intake increases life expectancy:\n\n[^1]: Weindruch, R., Walford, R.L., Fligiel, S. and Guthrie D. (1986). The Retardation of Aging in Mice by Dietary Restriction: Longevity, Cancer, Immunity and Lifetime Energy Intake, Journal of Nutrition 116(4):641–54.\n\n-   \\[NP\\] mice ate unlimited amount of nonpurified, standard diet\n\n-   \\[N/N85\\] normal diet before weaning and normal diet after weaning (85 kcal/wk)\n\n-   \\[N/R50\\] normal diet before weaning and reduced calorie diet after weaning (50 kcal/wk)\n\n-   \\[N/R40\\] normal diet before weaning and reduced diet after weaning (40 Kcal/wk)\n\n1. [L3, L4, L9] The `longevity` dataset contains observations of lifetime in months for 237 mice for the study above. In this problem you'll test whether diet restriction has an effect on longevity.\n\n    a.  [L3] Make a boxplot of the data, orienting the boxes vertically, and compute summary statistics (mean, standard deviation, and sample size) for each treatement group. Do assumptions for inference using ANOVA seem met? \n    b.  [L4] Compute point estimates and standard errors for the mean lifetime in each group.\n    c.  [L9] Test for an effect of diet restriction. Provide the $F$ statistic, numerator and denominator degrees of freedom for the $F$ model, and $p$-value.\n    d.  [L9] Interpret the result of the test in context following the narrative format from class.\n\n\n\n\n\n2. [L9] A study investigating physiological differences among species of predatory crabs recorded measurements of propodus height of the claws of crabs from three predatory species. The output below shows the result of an ANOVA model fitted to this data. \n\n    a. Construct the ANOVA table to test the hypothesis that mean weight loss does not differ among the three diets. (*Hint:* the $p$-value from an F model can be computed as `pf(fstat, num.df, denom.df, lower.tail = F)`.)\n    b. Report the result of the test in context following the narrative style from class.\n    \n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\n   aov(formula = height ~ species, data = crab)\n\nTerms:\n                  species Residuals\nSum of Squares   46.22818 137.15524\nDeg. of Freedom         2        35\n\nResidual standard error: 1.979576\nEstimated effects may be unbalanced\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab9-anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}