{
  "hash": "87ae29d36b4bf9cecd6b3e5685091d93",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Confidence intervals\"\nsubtitle: \"Constructing interval estimates to attain a specified coverage rate\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    mermaid:\n      theme: neutral\nexecute: \n  echo: false\n  warning: false\n  message: false\n---\n\n::: {.cell}\n\n:::\n\n\n## Today's agenda\n\n- [lecture] $t$ confidence intervals for the mean\n- [lab] computing and interpreting confidence intervals\n\n## From last time\n\n::: {.columns}\n\n::: {.column}\nUnder simple random sampling:\n\n- the sample mean $\\bar{x}$ provides a good point estimate of the population mean $\\mu$\n- its estimated sampling variability is given by the standard error $SE(\\bar{x}) = \\frac{s_x}{\\sqrt{n}} = \\frac{\\text{sample SD}}{\\sqrt{\\text{sample size}}}$\n<!-- - an interval estimate (range of plausible values) is $\\bar{x} \\pm 2\\times SE(\\bar{x})$ -->\n::: \n\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n\n--------------------------------\n mean     sd      n       se    \n------- ------- ------ ---------\n 5.043   1.075   3179   0.01906 \n--------------------------------\n\n\n:::\n\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n:::\n\n:::\n\n> The mean total HDL cholesterol among the U.S. adult population is estimated to be 5.043 mmol/L (SE 0.0191).\n\n## Interval estimation\n\nA common interval estimate for the population mean is:\n$$\\bar{x} \\pm 2\\times SE(\\bar{x}) \\qquad\\text{where}\\quad SE(\\bar{x}) = \\left(\\frac{s_x}{\\sqrt{n}}\\right)$$\n\n> A range of plausible values for the mean total cholesterol among U.S. adults is 5.005 to 5.081 mmol/L.\n\nTwo related questions:\n\n1. What do we mean by \"plausible\"?\n2. Where did the number 2 come from?\n\n## The $t$ model\n\n::: {.columns}\n\n::: {.column}\nConsider the statistic:\n\n$$\nT = \\frac{\\bar{x} - \\mu}{s_x/\\sqrt{n}}\n\\qquad\\left(\\frac{\\text{estimation error}}{\\text{standard error}}\\right)\n$$ \n\nThe sampling distribution of $T$ is well-approximated by a $t_{n - 1}$ model whenever either:\n\n(a) the population model is symmetric and unimodal\n\nOR\n\n(b) the sample size is not too small\n    \n:::\n\n::: {.column}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n:::\n\n## $t$ model interpretation\n\n> The *area under the density curve* between any two values $(a, b)$ gives the proportion of random samples for which $a < T < b$.\n\n$$(\\text{proportion of area between } a, b) = (\\text{proportion of samples where } a < T < b)$$\n\n::: {.columns}\n\n::: {.column}\nFor example:\n\n- for 50% of samples, $T < 0$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# area less than 0\npt(0, df = 20 - 1) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5\n```\n\n\n:::\n:::\n\n\n- written as $P(T < 0) = 0.5$\n\n:::\n\n::: {.column}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=624}\n:::\n:::\n\n:::\n\n:::\n\n## $t$ model interpretation\n\n> The *area under the density curve* between any two values $(a, b)$ gives the proportion of random samples for which $a < T < b$.\n\n$$(\\text{proportion of area between } a, b) = (\\text{proportion of samples where } a < T < b)$$\n\n::: {.columns}\n\n::: {.column}\nFor example:\n\n- for 83.5% of samples, $T < 1$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# area less than 1\npt(1, df = 20 - 1) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8350616\n```\n\n\n:::\n:::\n\n\n- written as $P(T < 1) = 0.835$\n\n:::\n\n::: {.column}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=624}\n:::\n:::\n\n:::\n\n:::\n\n## $t$ model interpretation\n\n> The *area under the density curve* between any two values $(a, b)$ gives the proportion of random samples for which $a < T < b$.\n\n$$(\\text{proportion of area between } a, b) = (\\text{proportion of samples where } a < T < b)$$\n\n::: {.columns}\n\n::: {.column}\nFor example:\n\n- for 97% of samples, $T < 2$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# area less than 2\npt(2, df = 20 - 1) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.969999\n```\n\n\n:::\n:::\n\n\n- written as $P(T < 2) = 0.97$\n\n:::\n\n::: {.column}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=624}\n:::\n:::\n\n:::\n\n:::\n\n## $t$ model interpretation\n\n> The *area under the density curve* between any two values $(a, b)$ gives the proportion of random samples for which $a < T < b$.\n\n$$(\\text{proportion of area between } a, b) = (\\text{proportion of samples where } a < T < b)$$\n\n::: {.columns}\n\n::: {.column}\nFor example:\n\n- for 3% of samples, $T > 2$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# area greater than 2\npt(2, df = 20 - 1, lower.tail = F) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03000102\n```\n\n\n:::\n:::\n\n\n- notice: \n$$\n\\begin{align*}\nP(T > 2) &= 1 - P(T < 2) \\\\\n(0.03) &= 1 - (0.97)\n\\end{align*}\n$$\n:::\n\n::: {.column}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=624}\n:::\n:::\n\n:::\n\n:::\n\n## $t$ model interpretation\n\n> The *area under the density curve* between any two values $(a, b)$ gives the proportion of random samples for which $a < T < b$.\n\n$$(\\text{proportion of area between } a, b) = (\\text{proportion of samples where } a < T < b)$$\n\n::: {.columns}\n\n::: {.column}\nFor example:\n\n- for 13.5% of samples, $1 < T < 2$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# area between 1 and 2\npt(2, df = 20 - 1) - pt(1, df = 20 - 1) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1349374\n```\n\n\n:::\n:::\n\n\n- notice:\n$$\n\\begin{align*}\nP(1 < T < 2) &= P(T < 2) - P(T < 1) \\\\\n(0.135) &= (0.97) - (0.835)\n\\end{align*}\n$$\n\n:::\n\n::: {.column}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=624}\n:::\n:::\n\n:::\n\n:::\n\n## $t$ model interpretation\n\n> The *area under the density curve* between any two values $(a, b)$ gives the proportion of random samples for which $a < T < b$.\n\n$$(\\text{proportion of area between } a, b) = (\\text{proportion of samples where } a < T < b)$$\n\n::: {.columns}\n\n::: {.column}\nFor example:\n\n- for 94% of samples, $-2 < T < 2$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# area between 1 and 2\npt(2, df = 20 - 1) - pt(-2, df = 20 - 1) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.939998\n```\n\n\n:::\n:::\n\n\n- written $P(-2 < T < 2) = 0.94$\n\n:::\n\n::: {.column}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=624}\n:::\n:::\n\n:::\n\n:::\n\n## A closer look at interval construction\n\nSo where did that 2 come from in the margin of error for our interval estimate?\n\n$$\n\\bar{x} \\pm \\color{blue}{2}\\times SE(\\bar{x})\n$$\n\nWell:\n\n::: {.columns}\n\n::: {.column width=\"70%\"}\n\n$$\n\\begin{align*}\n0.94 &= P(-\\color{blue}{2} < T < \\color{blue}{2}) \\\\\n&= P\\left(-\\color{blue}{2} < \\frac{\\bar{x} - \\mu}{s_x/\\sqrt{n}} < \\color{blue}{2}\\right) \\\\\n&= P(\\underbrace{\\bar{x} - \\color{blue}{2}\\times SE(\\bar{x}) < \\mu < \\bar{x} + \\color{blue}{2}\\times SE(\\bar{x})}_{\\text{interval covers population mean}})\n\\end{align*}\n$$\n:::\n\n::: {.column width=\"30%\"}\n> For 94% of all random samples, the interval covers the population mean.\n:::\n\n:::\n\nSo the number 2 determines the proportion of samples for which the interval covers the mean, known as its **coverage**.\n\n\n## Effect of sample size\n\n> The sample size determines the exact shape of the $t$ model through its 'degrees of freedom' $n - 1$. This changes the areas slightly.\n\nThe exact coverage quickly converges to just over 95% as the sample size increases.\n\n::: {.columns}\n\n::: {.column}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n----------------\n  n    coverage \n----- ----------\n  4     0.8607  \n\n  8     0.9144  \n\n 16     0.9361  \n\n 32     0.9457  \n\n 64     0.9502  \n\n 128    0.9524  \n\n 256    0.9534  \n----------------\n\n\n:::\n:::\n\n\n:::\n\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-17-1.png){width=480}\n:::\n:::\n\n:::\n\n:::\n\n## Changing the coverage\n\nConsider a slightly more general expression for an interval for the mean:\n\n$$\n\\bar{x} \\pm c\\times SE(\\bar{x})\n$$\n\nThe number $c$ is called a **critical value**. It determines the coverage.\n\n- larger $c$ $\\longrightarrow$ higher coverage\n- smaller $c$ $\\longrightarrow$ lower coverage\n\nThe so-called \"empirical rule\" is that:\n\n- $c = 1 \\longrightarrow$ approximately 68% coverage\n- $c = 2 \\longrightarrow$ approximately 95% coverage\n- $c = 3 \\longrightarrow$ approximately 99.7% coverage\n\n## Interpreting critical values\n\n::: {.columns}\n\n::: {.column}\n$$\nP(\\color{#FF6459}{-2 < T < 2}) = 1 - 2\\times P(\\color{blue}{T > 2})\n$$\n\nLook at how the areas add up so that:\n$$\nP(\\color{blue}{T > 2}) = 0.03\n$$\nMoreover:\n$$\nP(T < 2) = 1 - 0.03 = 0.97\n$$\n:::\n\n::: {.column}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=672}\n:::\n:::\n\n:::\n\n:::\n\n*So the critical value 2 is actually the 97th percentile of the sampling distribution of $T$.*\n\n- also called the 0.97 \"quantile\"\n- (percentiles expressed in proportions are called quantiles)\n\n## Exact coverage using $t$ quantiles\n\nTo engineer an interval with a specific coverage, use the $p$th quantile where:\n\n$$p = \\left[1 - \\left(\\frac{1 - \\text{coverage}}{2}\\right)\\right]$$\nIn R:\n\n::: {.cell}\n\n```{.r .cell-code}\n# coverage 95% using t quantile\ncoverage <- 0.95\nq.val <- 1 - (1 - coverage)/2\ncrit.val <- qt(q.val, df = 20 - 1)\ncrit.val\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.093024\n```\n\n\n:::\n:::\n\n\nThe effect of increasing/decreasing coverage on the quantile is:\n\n- increase coverage $\\longrightarrow$ larger quantile $\\longrightarrow$ wider interval\n- decrease coverage $\\longrightarrow$ smaller quantile $\\longrightarrow$ narrower interval\n\n## Contrasting coverage with precision\n\n> **Precision** refers to how wide or narrow the interval is.\n\nPrecision depends on every component of the margin of error:\n\n- critical value used\n- sample size\n- variability of values\n\nBy contrast, coverage depends only on the critical value used.\n\n## Confidence intervals\n\nInterval estimates constructed to achieve a specified coverage are called \"confidence intervals\"; the coverage is interpreted and reported as a \"confidence level\".\n\n::: {.columns}\n\n::: {.column width=\"60%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# ingredients\ncholesterol.mean <- mean(cholesterol)\ncholesterol.sd <- sd(cholesterol)\ncholesterol.n <- length(cholesterol)\ncholesterol.se <- cholesterol.sd/sqrt(cholesterol.n)\ncrit.val <- qt(1 - (1 - 0.95)/2, df = cholesterol.n - 1)\n\n# interval\ncholesterol.mean + c(-1, 1)*crit.val*cholesterol.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.005566 5.080310\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"40%\"}\n> With 95% confidence, the mean total cholesterol among U.S. adults is estimated to be between 5.0056 and 5.0803 mmol/L.\n\n:::\n\n:::\n\nThe general formula for a confidence interval for the population mean is\n\n$$\n\\bar{x} \\pm c\\times SE(\\bar{x})\n$$\n\nwhere $c$ is a critical value, obtained as a quantile of the $t_{n - 1}$ model and chosen to ensure a specific coverage.\n\n## Recap\n\nThe \"common\" interval estimate for the mean is actually an approximate 95% confidence interval:\n\n$$\n\\bar{x} \\pm 2 \\times SE(\\bar{x})\n$$\n\n- captures the population mean $\\mu$ for roughly 95% of random samples\n- replacing 2 with a $t_{n - 1}$ quantile allows the analyst to adjust coverage\n- the $t_{n - 1}$ model is an approximation for the sampling distribution of $\\frac{\\bar{x} - \\mu}{SE(\\bar{x})}$\n\n    + approximation improves with increasing sample size or symmetry\n    + usually good quality except in \"extreme\" situations\n\nInterval interpretation:\n\n> With [XX]% confidence, the mean [population parameter] is estimated to be between [lower bound] and [upper bound] [units].\n\n# Extras\n\n## Simulation of coverage\n\n\n::: {.cell}\n\n:::\n\n\n::: {.columns}\n\n::: {.column width=\"65%\"}\nArtificially simulating a large number of intervals provides an empirical approximation of coverage. \n\n- at right, 200 intervals\n- 94% cover the population mean (vertical dashed line)\n- pretty close to nominal coverage level 95%\n\nThis is also a handy way to remember the proper interpretation:\n\n> If I made a lot of intervals from independent samples, 95% of them would 'get it right'.\n\n:::\n\n::: {.column width=\"35%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week4-intervals_files/figure-revealjs/unnamed-chunk-22-1.png){width=384}\n:::\n:::\n\n:::\n\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}