{
  "hash": "286dc125b531e5cb9de50e3bfc99a26e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Two sample inference\"\nsubtitle: \"Hypothesis tests and intervals for comparing two population means\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    mermaid:\n      theme: neutral\nexecute: \n  eval: true\n  echo: false\n  warning: false\n  message: false\n---\n\n::: {.cell}\n\n:::\n\n\n## Today's agenda\n\n1. [lecture] two sample inference for means\n2. [lab] two-sample $t$ tests in R\n3. [test prep] practice problems\n\n## From last time\n\nPractice problem: *test whether actual body weight exceeds desired body weight*.\n\n::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n-----------------------------------------\n subject   actual   desired   difference \n--------- -------- --------- ------------\n    1       265       225         40     \n\n    2       150       150         0      \n\n    3       137       150        -13     \n\n    4       159       125         34     \n\n    5       145       125         20     \n-----------------------------------------\n\n\n:::\n:::\n\n::: \n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nweight.diffs <- brfss$weight - brfss$wtdesire\nt.test(weight.diffs, \n       mu = 0, \n       alternative = 'greater')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  weight.diffs\nt = 4.2172, df = 59, p-value = 4.311e-05\nalternative hypothesis: true mean is greater than 0\n95 percent confidence interval:\n 10.99824      Inf\nsample estimates:\nmean of x \n 18.21667 \n```\n\n\n:::\n:::\n\n:::\n:::\n\n> The data provide very strong evidence that the average U.S. adult's actual weight exceeds their desired weight (*T* = 4.2172 on 59 degrees of freedom, *p* < 0.0001).\n\nInference is on the mean difference: $H_0: \\delta = 0$ vs. $H_A: \\delta > 0$.\n\n*Can we also do inference on a difference in means?*\n\n## Evolution of Darwin's finches\n\n::: columns\n::: {.column width=\"70%\"}\nPeter and Rosemary Grant caught and measured birds from more than 20 generations of finches on Daphne Major.\n\n-   severe drought in 1977 limited food to large tough seeds\n\n-   selection pressure favoring larger and stronger beaks\n\n-   hypothesis: beak depth increased in 1978 relative to 1976\n\n:::\n\n::: {.column width=\"30%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n--------------\n year   depth \n------ -------\n 1976   10.8  \n\n 1976    7.4  \n\n 1978   11.4  \n\n 1978   10.6  \n--------------\n\n\n:::\n:::\n\n:::\n:::\n\nTo answer this, we need to test a hypothesis involving two means:\n\n$$\n\\begin{cases}\nH_0: &\\mu_{1976} = \\mu_{1978} \\\\\nH_A: &\\mu_{1976} < \\mu_{1978}\n\\end{cases}\n$$\n\n- can't do inference on a mean difference here (no pairing of observations)\n- treat each year as an independent sample\n\n## Two-sample inference\n\n\n::: {.cell}\n\n:::\n\n\nIf $x_1, \\dots, x_{58}$ are the 1976 observations and $y_1, \\dots, y_{65}$ are the 1978 observations:\n\n- $\\bar{x}$ is a point estimate for $\\mu_{1976}$ with standard error $SE(\\bar{x}) = \\frac{s_x}{\\sqrt{n}}$\n- $\\bar{y}$ is a point estimate for $\\mu_{1978}$ with standard error $SE(\\bar{y}) = \\frac{s_y}{\\sqrt{n}}$\n\n::: {.columns}\n\n::: {.column}\n\nInference uses a new $T$ statistic:\n\n$$\nT = \\frac{\\bar{x} - \\bar{y} - \\delta_0}{SE(\\bar{x} - \\bar{y})}\n$$\n\n- $\\delta_0$ is the hypothesized difference in means\n-   $SE(\\bar{x} - \\bar{y}) = \\sqrt{SE(\\bar{x})^2 + SE(\\bar{y})^2}$\n-   $t_\\nu$ model approximates the sampling distribution when each sample meets assumptions for one-sample inference\n\n:::\n\n::: {.column}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week6-twosample_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=624}\n:::\n:::\n\n\n:::\n\n:::\n\n## Checking assumptions\n\n> The two-sample test is appropriate whenever two one-sample tests would be.\n\n::: {.columns}\n\n::: {.column}\nIn other words, the test assumes that *both* samples are either:\n\n- sufficiently large; or\n- have little skew and few outliers\n\nTo check, simply inspect each histogram.\n\n- both distributions unimodal\n- both a bit left skewed \n- no extreme outliers\n- large sample sizes (58, 65)\n:::\n\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week6-twosample_files/figure-revealjs/unnamed-chunk-7-1.png){width=480}\n:::\n:::\n\n:::\n\n:::\n\n\n## Checking assumptions (alternative)\n\n> The two-sample test is appropriate whenever two one-sample tests would be.\n\n::: {.columns}\n\n::: {.column}\nIn other words, the test assumes that *both* samples are either:\n\n- sufficiently large; or\n- have little skew and few outliers\n\nCould also check side-by-side boxplots for:\n\n- approximate symmetry of boxes\n- outliers far from whiskers\n\nThis is also a nice visualization of differences between samples.\n:::\n\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week6-twosample_files/figure-revealjs/unnamed-chunk-8-1.png){width=480}\n:::\n:::\n\n:::\n\n:::\n\n## Interpreting outputs and results\n\n::: columns\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(depth ~ year, data = finch,\n       mu = 0, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  depth by year\nt = -4.5727, df = 111.79, p-value = 6.255e-06\nalternative hypothesis: true difference in means between group 1976 and group 1978 is less than 0\n95 percent confidence interval:\n       -Inf -0.4698812\nsample estimates:\nmean in group 1976 mean in group 1978 \n          9.453448          10.190769 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"55%\"}\n> The data provide very strong evidence that mean beak depth increased following the drought (*T* = -4.5727 on 111.79 degrees of freedom, *p* < 0.0001). With 95% confidence, the mean increase is estimated to be at least 0.4699 mm, with a point estimate of 0.7373 (SE 0.1612).\n:::\n:::\n\nHighly similar, but notice:\n\n- input is a formula `depth ~ year` (\"depth depends on year\") and data frame `finch`\n- `mu` now indicates hypothesized difference in means\n- decimal degrees of freedom\n- alternative is relative to the order in which groups appear\n\n## Cloud data\n\n> Does seeding clouds with silver iodide increase mean rainfall?\n\n::: columns\n::: {.column width=\"60%\"}\nData are rainfall measurements in a target area from 26 days when clouds were seeded and 26 days when clouds were not seeded.\n\n-   `rainfall` gives volume of rainfall in acre-feet\n-   `treatment` indicates whether clouds were seeded\n\nHypotheses to test: \n$$\n\\begin{cases}\nH_0: &\\mu_\\text{seeded} = \\mu_\\text{unseeded} \\\\\nH_A: &\\mu_\\text{seeded} > \\mu_\\text{unseeded}\n\\end{cases}\n$$\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n----------------------\n rainfall   treatment \n---------- -----------\n  334.1      seeded   \n\n  489.1      seeded   \n\n  200.7      seeded   \n\n   40.6      seeded   \n\n   21.7     unseeded  \n\n   17.3     unseeded  \n\n   68.5     unseeded  \n\n  830.1     unseeded  \n----------------------\n\n\n:::\n:::\n\n:::\n:::\n\n## Cloud data: which alternative?\n\n> Does seeding clouds with silver iodide increase mean rainfall?\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(rainfall ~ treatment, data = cloud, \n       mu = 0, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  rainfall by treatment\nt = 1.9982, df = 33.855, p-value = 0.9731\nalternative hypothesis: true difference in means between group seeded and group unseeded is less than 0\n95 percent confidence interval:\n     -Inf 512.1582\nsample estimates:\n  mean in group seeded mean in group unseeded \n              441.9846               164.5885 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(rainfall ~ treatment, data = cloud, \n       mu = 0, alternative = 'greater')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  rainfall by treatment\nt = 1.9982, df = 33.855, p-value = 0.02689\nalternative hypothesis: true difference in means between group seeded and group unseeded is greater than 0\n95 percent confidence interval:\n 42.63408      Inf\nsample estimates:\n  mean in group seeded mean in group unseeded \n              441.9846               164.5885 \n```\n\n\n:::\n:::\n\n:::\n\n:::\n\nYou can tell which group R considers first based on which estimate is printed first.\n\n\n- `'greater'` is interpreted as [FIRST GROUP] > [SECOND GROUP]\n- `'less'` is interpreted as [FIRST GROUP] < [SECOND GROUP]\n\n## Cloud data: interpretation\n\n> Does seeding clouds with silver iodide increase mean rainfall?\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(rainfall ~ treatment, data = cloud, \n       mu = 0, alternative = 'greater')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  rainfall by treatment\nt = 1.9982, df = 33.855, p-value = 0.02689\nalternative hypothesis: true difference in means between group seeded and group unseeded is greater than 0\n95 percent confidence interval:\n 42.63408      Inf\nsample estimates:\n  mean in group seeded mean in group unseeded \n              441.9846               164.5885 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n> The data provide moderate evidence that cloud seeding increases mean rainfall (*T* = 1.9982 on 33.855 degrees of freedom, *p* = 0.02689). With 95% confidence, seeding is estimated to increase mean rainfall by at least 42.63 acre-feet, with a point estimate of 277.4 (SE 138.8199).\n:::\n\n:::\n\n## Body temperatures (again)\n\n> Does mean body temperature differ between men and women?\n\n\n::: {.cell}\n\n:::\n\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week6-twosample_files/figure-revealjs/unnamed-chunk-15-1.png){width=480}\n:::\n:::\n\n:::\n\n::: {.column}\nTest $H_0: \\mu_F = \\mu_M$ against $H_A: \\mu_F \\neq \\mu_M$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(body.temp ~ sex, data = temps, \n       mu = 0, alternative = 'two.sided')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  body.temp by sex\nt = 1.7118, df = 34.329, p-value = 0.09595\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -0.09204497  1.07783444\nsample estimates:\nmean in group female   mean in group male \n            98.65789             98.16500 \n```\n\n\n:::\n:::\n\n:::\n\n:::\n\nSuggestive but insufficient evidence that mean body temperature differs by sex.\n\nNotice: estimated difference (F - M) is 0.493 °F (SE 0.2879)\n\n## What if we had more data?\n\n\n::: {.cell}\n\n:::\n\n\nHere are estimates from two larger samples of 65 individuals each (compared with 19, 20):\n\n::: {.cell}\n::: {.cell-output-display}\n\n-----------------------------------\n  sex     mean.temp     se      n  \n-------- ----------- --------- ----\n female     98.39     0.09222   65 \n\n  male      98.1      0.08667   65 \n-----------------------------------\n\n\n:::\n:::\n\n\n- estimated difference (F - M) is smaller 0.2892 °F\n- but so is the standard error SE 0.1266 (recall more data $\\longleftrightarrow$ better precision)\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(body.temp ~ sex, data = temps.aug, \n       mu = 0, alternative = 'two.sided')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  body.temp by sex\nt = 2.2854, df = 127.51, p-value = 0.02394\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n 0.03881298 0.53964856\nsample estimates:\nmean in group female   mean in group male \n            98.39385             98.10462 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n> The data provide moderate evidence that mean body temperature differs by sex (*T* = 2.29 on 127.51 degrees of freedom, *p* = 0.02394).\n:::\n\n:::\n\n## Power calculations\n\n> How much data do you need to collect in order to detect a difference of $\\delta$?\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\nThe statistical **power** of a test captures how often it detects a specified alternative.\n\n- measures how often the test correctly rejects (proportion of samples)\n- value depends on...\n\n    a. magnitude of difference between null value and true value of parameter\n    b. significance level\n    c. sample size\n\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npower.t.test(power = 0.95, \n             delta = 0.5, \n             sig.level = 0.05, \n             type = 'two.sample',\n             alternative = 'two.sided')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 104.928\n          delta = 0.5\n             sd = 1\n      sig.level = 0.05\n          power = 0.95\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n$\\Rightarrow$ need 105 observations in each group to detect a difference of 0.5 standard deviations for 95% of samples with a 5% significance level test\n:::\n\n:::\n\n## A statistical trap\n\n> If you collect enough data, you can detect an arbitrarily small difference in means almost always.\n\n::: {.columns}\n\n::: {.column width=\"70%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week6-twosample_files/figure-revealjs/unnamed-chunk-21-1.png){width=768}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\nSo keep in mind:\n\n- statistical significance $\\neq$ practical significance\n- always check your point estimates\n:::\n\n:::\n\n# Extras\n\n## The equal-variance $t$-test\n\nIf it is reasonable to assume the (population) standard deviations are the same in each group, one can gain a bit of power by using a different standard error:\n\n$$SE_\\text{pooled}(\\bar{x} - \\bar{y}) = \\sqrt{\\frac{\\color{red}{s_p^2}}{n_x} + \\frac{\\color{red}{s_p^2}}{n_y}}\n\\quad\\text{where}\\quad \\color{red}{s_p} = \\underbrace{\\sqrt{\\frac{(n_x - 1)s_x^2 + (n_y - 1)s_y^2}{n_x + n_y - 2}}}_{\\text{weighted average of } s_x^2 \\;\\&\\; s_y^2}$$\n\nImplement by adding `var.equal = T` as an argument to `t.test()`.\n\n- larger df is used, hence more frequent rejections\n- avoid unless you have a small sample\n\n",
    "supporting": [
      "week6-twosample_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}