{
  "hash": "e89da5f2b02570bed4955a33d82f64f9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Measures of association\"\nsubtitle: \"Inference for relative risk and odds ratios from 2x2 contingency tables\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    tbl-colwidths: [40, 40, 40]\n    mermaid:\n      theme: neutral\nexecute: \n  echo: false\n  warning: false\n  message: false\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n::: {.cell}\n\n:::\n\n\n## Today's agenda\n\n1. [lecture] relative risk and odds ratios\n2. [lab] using `epitools` to estimate risk and odds ratios in R\n3. [discussion] final project guidelines\n\n## From last time: smoking\n\n::: {.columns}\n\n::: {.column}\nResearchers sampled 86 lung cancer patients (cases) and 86 healthy individuals (controls) and recorded smoking status:\n\n::: {.cell}\n::: {.cell-output-display}\n\n------------------------------------\n   &nbsp;      Smokers   NonSmokers \n------------- --------- ------------\n **cancer**      83          3      \n\n **control**     72          14     \n------------------------------------\n\n\n:::\n:::\n\n\nAt the 5% level, association is significant:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmoking.tbl <- table(smoking$group, \n                     smoking$smoking) \nsmoking.tbl |> chisq.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  smoking.tbl\nX-squared = 6.5275, df = 1, p-value = 0.01062\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column}\nBut there is a difficulty for measuring the association:\n\n- data are really *two* independent samples\n- so can't estimate cancer prevalence\n\n:::\n\n:::\n\n## Case-control studies\n\n> Outcome-based sampling limits which proportions are estimable\n\n![](img/casecontrol.png)\n\n- cases and controls are two independent samples\n- exposure prevalence is estimable (within case and control populations)\n- case prevalence is **not** estimable\n\n## Smoking example\n\n::: {.columns}\n\n::: {.column}\nSo due to study design, the only estimable difference in proportions is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmoking.prop.test <- smoking.tbl |> prop.test()\nsmoking.prop.test$conf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.029149 0.226665\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n\n> With 95% confidence, the proportion of smokers among cancer patients is estimated to be betwteen 2.9 and 22.7 percentage points higher than among controls.\n\n:::\n\n:::\n\nThis makes for an awkward conclusion:\n\n- we really want to know how smoking affects cancer risk\n- ...not how cancer affects smoking risk\n\nSo for this kind of study, we need a different measure of association: ***odds ratios***.\n\n## Odds \n\n> The odds of an outcome measure its relative likelihood\n\nIf $p$ is the true cancer prevalence (a population proportion), then the **odds** of cancer are defined as the ratio:\n$$\n\\text{odds} = \\frac{p}{1 - p}\n$$\nThe odds represent the factor by which cancer is more likely than not, *e.g.*:\n\n- $\\text{odds} = 2$ indicates the outcome (cancer) is twice as likely as not\n- $\\text{odds} = 1/2$ indicates the outcome (cancer) is half as likely as not\n\n## Odds ratios\n\n> An odds ratio compares the relative likelihood of an outcome between two groups\n\n::: {.columns}\n\n::: {.column width=\"60%\"}\nIf $a, b, c, d$ are population proportions:\n\n$\\;$ | outcome 1 (O1) | outcome 2 (O2)\n---|:---:|:---:\ngroup 1 (G1) | [a]{style=\"color:red\"} | [b]{style=\"color:blue\"} \ngroup 2 (G2) | [c]{style=\"color:orange\"} | [d]{style=\"color:purple\"}\n\n\n- the odds of outcome 1 in group 1 is $\\frac{\\textcolor{red}{a}}{\\textcolor{blue}{b}}$\n- the odds of outcome 1 in group 2 is $\\frac{\\textcolor{orange}{c}}{\\textcolor{purple}{d}}$\n\n\n:::\n\n::: {.column width=\"40%\"}\nThe **odds ratio** of outcome 1 comparing group 1 with group 2 is:\n\n$$\n\\frac{\\text{odds}_{G1}(O1)}{\\text{odds}_{G2}(O1)}\n= \\frac{\\textcolor{red}{a}/\\textcolor{blue}{b}}{\\textcolor{orange}{c}/\\textcolor{purple}{d}}\n= \\frac{\\textcolor{red}{a}\\textcolor{purple}{d}}{\\textcolor{blue}{b}\\textcolor{orange}{c}}\n$$\nA surprising algebraic fact is that:\n\n$$\n\\frac{\\text{odds}_{G1}(O1)}{\\text{odds}_{G2}(O1)} \n=\\frac{\\text{odds}_{O1}(G1)}{\\text{odds}_{O2}(G1)}\n$$\n\n:::\n\n:::\n\n*This means that the ratio of odds of cancer between smokers and nonsmokers can be estimated from the ratio of odds of smoking between cases and controls.*\n\n## Estimating odds ratios\n\n::: {.columns}\n\n::: {.column width=\"60%\"}\nFor notation let:\n\n- $\\hat{p}_\\text{case}$ : proportion of smokers among cases\n- $\\hat{p}_\\text{control}$ : proportion of smokers among controls\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n------------------------------------\n   &nbsp;      Smokers   NonSmokers \n------------- --------- ------------\n **cancer**      83          3      \n\n **control**     72          14     \n------------------------------------\n\n\n:::\n:::\n\n:::\n\n:::\n\nAn estimate of ratio of odds of cancer among smokers compared with nonsmokers ($\\omega$) is the estimated ratio of odds of smoking among cancer patients compared with controls:\n$$\n\\hat{\\omega} \n=\\left(\\frac{\\hat{p}_\\text{case}}{1 - \\hat{p}_\\text{case}}\\right)\\Bigg/\\left(\\frac{\\hat{p}_\\text{control}}{1 - \\hat{p}_\\text{control}}\\right)\n= \\frac{83/3}{72/14} = 5.38\n$$\n\n> It is estimated that the odds of lung cancer are 5.38 times greater for smokers compared with nonsmokers.\n\n## Confidence intervals for odds ratios\n\nThe sampling distribution of the log odds ratio can be approximated by a normal model.\n\n$$\n\\log\\left(\\hat{\\omega}\\right) \\pm c \\times SE\\left(\\log\\left(\\hat{\\omega}\\right)\\right) \n\\quad\\text{where}\\quad\nSE\\left(\\log\\left(\\hat{\\omega}\\right)\\right) = \\sqrt{\\frac{1}{n_{11}} + \\frac{1}{n_{12}} + \\frac{1}{n_{21}} + \\frac{1}{n_{22}}}\n$$\n\n\n::: {.columns}\n\n::: {.column}\nThe `oddsratio(...)` function in the `epitools` package will compute and back-transform the interval for you.\n\n::: {.cell}\n\n```{.r .cell-code}\noddsratio(smoking.tbl, rev = 'both', \n          method = 'wald', correction = T)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n         odds ratio with 95% C.I.\n          estimate    lower    upper\n  control  1.00000       NA       NA\n  cancer   5.37963 1.486376 19.47045\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column}\n- critical value $c$ from the normal model\n- exponentiate to obtain an interval for $\\omega$\n\n> With 95% confidence, the odds of lung cancer are estimated to be between 1.49 and 19.47 times greater for smokers compared with nonsmokers.\n:::\n\n:::\n\n## Implementation details\n\n::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\noddsratio(smoking.tbl, rev = 'both',\n          method = 'wald', correction = T)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n         \n          NonSmokers Smokers Total\n  control         14      72    86\n  cancer           3      83    86\n  Total           17     155   172\n\n$measure\n         odds ratio with 95% C.I.\n          estimate    lower    upper\n  control  1.00000       NA       NA\n  cancer   5.37963 1.486376 19.47045\n\n$p.value\n         two-sided\n           midp.exact fisher.exact chi.square\n  control          NA           NA         NA\n  cancer  0.005116319  0.008822805 0.01062183\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"55%\"}\n\n`oddsratio` is picky about data inputs:\n\n- outcome of interest should be *second* column\n- group of interest should be *second* row\n- the `rev` argument will reverse orders\n    \n    + `rev = neither` keeps original orientation (default)\n    + `rev = rows` reverses order of rows\n    + `rev = columns` reverses order of columns\n    + `rev = both` reverses both\n\n:::\n\n:::\n\n## Interpretation\n\n::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\noddsratio(smoking.tbl, rev = 'both',\n          method = 'wald', correction = T)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n         \n          NonSmokers Smokers Total\n  control         14      72    86\n  cancer           3      83    86\n  Total           17     155   172\n\n$measure\n         odds ratio with 95% C.I.\n          estimate    lower    upper\n  control  1.00000       NA       NA\n  cancer   5.37963 1.486376 19.47045\n\n$p.value\n         two-sided\n           midp.exact fisher.exact chi.square\n  control          NA           NA         NA\n  cancer  0.005116319  0.008822805 0.01062183\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"55%\"}\nFirst report the test result, then the measure of association:\n\n> The data provide evidence of an association between smoking and lung cancer ($\\chi^2$ = 6.53 on 1 degree of freedom, *p* = 0.1062). With 95% confidence, the odds of cancer are estimated to be between 1.49 amd 19.47 times greater among smokers compared with nonsmokers, with a point estimate of 5.38.\n\n\n:::\n\n:::\n\nComments:\n\n- the `chi.square` $p$-value is from the test of association/independence\n- if assumptions aren't met, can use the `fisher.exact` instead (see V&H 8.3.5)\n\n## Asthma data\n\n::: {.columns}\n\n::: {.column}\nConsider estimating the difference in proportions:\n\n::: {.cell}\n::: {.cell-output-display}\n\n---------------------------------\n   &nbsp;     asthma   no asthma \n------------ -------- -----------\n **female**     49        781    \n\n  **male**      30        769    \n---------------------------------\n\n\n:::\n:::\n\n\n:::\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nasthma.tbl <- table(asthma$sex, asthma$asthma)\nprop.test(asthma.tbl, conf.level = 0.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  asthma.tbl\nX-squared = 3.6217, df = 1, p-value = 0.05703\nalternative hypothesis: two.sided\n90 percent confidence interval:\n 0.002841347 0.040137075\nsample estimates:\n    prop 1     prop 2 \n0.05903614 0.03754693 \n```\n\n\n:::\n:::\n\n:::\n\n:::\n\n> With 90% confidence, asthma prevalence is estimated to be between 0.28 and 4.01 percentage points higher among women than among men.\n\nIs a difference of up to 4 percentage points practically meaningful? Well, it depends:\n\n- yes if prevalence is very low\n- no if prevalence is very high\n\n\n## Relative risk\n\nIf $p_F, p_M$ are the (population) proportions of women and men with asthma, then the **relative risk** of asthma among women compared with men is defined as:\n\n$$\nRR = \\frac{p_F}{p_M}\n\\qquad\n\\left(\\frac{\\text{risk among women}}{\\text{risk among men}}\\right)\n$$\n\nAn estimate of the relative risk is simply the ratio of estimated proportions. For the asthma data, an estimate is:\n$$\n\\widehat{RR} = \\frac{\\hat{p}_F}{\\hat{p}_M} = \\frac{0.059}{0.038} = 1.57 \n$$\n\n> It is estimated that the risk of asthma among women is 1.57 times greater than among men.\n\n## Confidence intervals for relative risk\n\nA normal model can be used to approximate the sampling distribution of $\\log(RR)$ and construct a confidence interval. If $\\hat{p}_1$ and $\\hat{p}_2$ are the two estimated proportions:\n\n$$\\log\\left(\\widehat{RR}\\right) \\pm c \\times SE\\left(\\log\\left(\\widehat{RR}\\right)\\right)\n\\quad\\text{where}\\quad SE\\left(\\log\\left(\\widehat{RR}\\right)\\right) = \\sqrt{\\frac{1 - p_1}{p_1n_1} + \\frac{1 - p_2}{p_2n_2}}$$\n\n::: {.columns}\n\n::: {.column width=\"50%\"}\nThe `riskratio(...)` function from the `epitools` package will compute and back-transform the interval for you:\n\n::: {.cell}\n\n```{.r .cell-code}\nriskratio(asthma.tbl, \n          rev = 'both', conf.level = 0.9,\n          method = 'wald', correction = T)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n        risk ratio with 90% C.I.\n         estimate    lower    upper\n  male   1.000000       NA       NA\n  female 1.572329 1.083353 2.282007\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n- critical value $c$ from normal model\n- exponentiate for an interval for $RR$\n\n> With 90% confidence, the risk of asthma is estimated to be betwen 1.08 and 2.28 times greater for women than for men, with a point estimate of 1.57.\n:::\n\n:::\n\n\n## Implementation details\n\n::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nriskratio(asthma.tbl, \n          rev = 'both', conf.level = 0.9,\n          method = 'wald', correction = T)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n        \n         no asthma asthma Total\n  male         769     30   799\n  female       781     49   830\n  Total       1550     79  1629\n\n$measure\n        risk ratio with 90% C.I.\n         estimate    lower    upper\n  male   1.000000       NA       NA\n  female 1.572329 1.083353 2.282007\n\n$p.value\n        two-sided\n         midp.exact fisher.exact chi.square\n  male           NA           NA         NA\n  female 0.04412095   0.04961711 0.05703135\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"55%\"}\n\nImplementation is identical to `oddsratio`:\n\n- outcome of interest should be *second* column\n- group of interest should be *second* row\n- rearrange the input data using `rev`\n\nAlso similarly:\n\n- `chi.square` gives the $p$-value for the $\\chi^2$ test of association\n- `fisher.exact` gives an exact p-value you can use if assumptions aren't met\n\n:::\n\n:::\n\n## Interpretation\n\n::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nriskratio(asthma.tbl, \n          rev = 'both', conf.level = 0.9,\n          method = 'wald', correction = T)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n        \n         no asthma asthma Total\n  male         769     30   799\n  female       781     49   830\n  Total       1550     79  1629\n\n$measure\n        risk ratio with 90% C.I.\n         estimate    lower    upper\n  male   1.000000       NA       NA\n  female 1.572329 1.083353 2.282007\n\n$p.value\n        two-sided\n         midp.exact fisher.exact chi.square\n  male           NA           NA         NA\n  female 0.04412095   0.04961711 0.05703135\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"55%\"}\nFirst report the test result, then the measure of association:\n\n> The data provide evidence at the 10% significance level of an association between asthma and sex ($\\chi^2$ = 3.62 on 1 degree of freedom, *p* = 0.057). With 90% confidence, the risk of asthma is estimated to be betwen 1.08 and 2.28 times greater for women than for men, with a point estimate of 1.57.\n\n\n:::\n\n:::\n\nComments:\n\n- the `chi.square` $p$-value is from the test of association/independence\n- if assumptions aren't met, can use the `fisher.exact` instead\n\n## Further examples: cyclosporiasis {.scrollable}\n\n::: {.columns}\n\n::: {.column}\nAn outbreak of cyclosporiasis was detected among residents of New Jersey. In a case-control study, investigators found that 21 of 30 case-patients and 4 of 60 controls had eaten raspberries.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n--------------------------------------------\n   &nbsp;      raspberries   no raspberries \n------------- ------------- ----------------\n  **case**         21              9        \n\n **control**        4              56       \n--------------------------------------------\n\n\n:::\n:::\n\n\n- outcome-based sampling\n- odds ratio should be used\n\n:::\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# check test assumptions\nchisq.test(cyclo.tbl)$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                cyclosporiasis\nraspberries           case  control\n  raspberries     8.333333 16.66667\n  no raspberries 21.666667 43.33333\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute measure of association and p value\noddsratio(cyclo.tbl, rev = 'both',\n          method = 'wald', correction = T)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n$measure\n                odds ratio with 95% C.I.\nraspberries      estimate    lower    upper\n  no raspberries  1.00000       NA       NA\n  raspberries    32.66667 9.081425 117.5048\n\n$p.value\n                two-sided\nraspberries        midp.exact fisher.exact   chi.square\n  no raspberries           NA           NA           NA\n  raspberries    6.358611e-10 6.183017e-10 1.247883e-09\n```\n\n\n:::\n:::\n\n\n\n:::\n\n:::\n\n> The data provide very strong evidence of an association between eating raspberries during the outbreak and case incidence ($\\chi^2$ = 36.89 on 1 degree of freedom, *p* < 0.0001). With 95% confidence, the odds of indcidence are estimated to be between 9.08 and 117.5 times higher among NJ residents who ate raspberries during the outbreak.\n\n## Further examples: smoking and CHD\n\n::: {.columns}\n\n::: {.column}\nA cohort study of 3,000 smokers and 5,000 nonsmokers investigated the link between smoking and the development of coronary heart disease (CHD) over 1 year.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n------------------------------\n    &nbsp;       CHD   no CHD \n--------------- ----- --------\n  **smoker**     84     2916  \n\n **nonsmoker**   87     4913  \n------------------------------\n\n\n:::\n:::\n\n\n- two independent samples, but **not** outcome-based sampling\n:::\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# check test assumptions\nchisq.test(chd.tbl)$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           chd\nsmoker          CHD   no CHD\n  smoker     64.125 2935.875\n  nonsmoker 106.875 4893.125\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nriskratio(chd.tbl, rev = 'both',\n          method = 'wald', correction = T)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n$measure\n           risk ratio with 95% C.I.\nsmoker      estimate    lower    upper\n  nonsmoker 1.000000       NA       NA\n  smoker    1.609195 1.196452 2.164325\n\n$p.value\n           two-sided\nsmoker       midp.exact fisher.exact  chi.square\n  nonsmoker          NA           NA          NA\n  smoker    0.001799736  0.001800482 0.001976694\n```\n\n\n:::\n:::\n\n:::\n\n:::\n\n> The data provide very strong evidence that smoking is associated with coronary heart disease ($\\chi^2$ = 9.5711 on 1 degree of freedom, *p* = 0.00198). With 95% confidence, the risk of CHD is estimated to be between 1.196 and 2.164 times greater among smokers compared with nonsmokers, with a point estimate of 1.609.\n\n## Further examples: malaria vaccine {.scrollable}\n\n::: {.columns}\n\n::: {.column}\nIn a randomized trial for a malaria vaccine, 20 individuals were randomly allocated to receive a dose of the vaccine or a placebo.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n----------------------------------------\n   &nbsp;      infection   no infection \n------------- ----------- --------------\n **placebo**       6            0       \n\n **vaccine**       5            9       \n----------------------------------------\n\n\n:::\n:::\n\n\n- small sample size, so expected counts are likely too small to meet $\\chi^2$ test assumptions\n:::\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# check test assumptions\nchisq.test(malaria.tbl)$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         outcome\ntreatment infection no infection\n  placebo       3.3          2.7\n  vaccine       7.7          6.3\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nriskratio(malaria.tbl, rev = 'columns',\n          method = 'wald', correction = T)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n$measure\n         risk ratio with 95% C.I.\ntreatment  estimate     lower     upper\n  placebo 1.0000000        NA        NA\n  vaccine 0.3571429 0.1768593 0.7212006\n\n$p.value\n         two-sided\ntreatment midp.exact fisher.exact chi.square\n  placebo         NA           NA         NA\n  vaccine  0.0119195   0.01408669 0.03094368\n```\n\n\n:::\n:::\n\n:::\n\n:::\n\n> The data provide moderate evidence that the malaria vaccine is effective (Fisher's exact test, *p* = 0.0141). \n\nA twist: how to interpret the CI? Answer: $\\text{efficacy = 1 - RR}$\n\n> With 95% confidence, the risk of infection is estimated to be between 27.88% and 82.31% lower among vaccinated individuals, with a point estimate of 64.29% efficacy.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}