---
title: "Chapter 6: Inference for a Single Numerical Variable"
format: 
  revealjs:
    auto-stretch: false
    theme: simple
embed-resources: true
---

## Monday, October 30th
### Today we will...

+ Review Central Limit Theorem
+ Introduce t-test
+ Example 6.2 (in groups)

## To do:
  
+ **Homework 6: What is the current average body temperature?**
  + Due Thursday 11/2 at 11:59pm

::: callout-warning
Don't forget to take the Canvas Quiz **AND** submit your completed assignment.
:::

## Tuesday, October 31st
### Today we will...

+ Happy Halloween! Take some candy!
+ Confidence Intervals for Single Numeric Variables
+ Exit Ticket: Confidence Interval Interpretation

##

::: callout-note
## Exit Ticket
In a recent survey, 1,200 households planned to spend an average of \$75 on Halloween candy, with a 95% confidence interval of \$72 to \$78. 

1. Interpret the 95\% confidence interval in context of the scenario.

2. Explain what it means when we say we are 95\% confident in this context of this scenario.
:::
  

## To do:

+ **Homework 6: What is the average body temperature?**
  + Due Thursday 11/2 at 11:59pm
  
+ **Study for Quiz 3: Inference for a Single Numerical Variables**
  + In class Friday, 11/3

::: callout-warning
Don't forget to take the Canvas Quiz **AND** submit your completed assignment.
:::

## Thursday, November 2nd
### Today we will...

+ Lab 6: Hours worked

## To do:
  
+ **Homework 6: What is the average body temperature?**
  + Due Thursday 11/2 at 11:59pm
  
+ **Lab 6: Hours worked**
  + Due Monday 11/6 at 11:59pm
  
+ **Study for Quiz 3: Inference for a Single Numerical Variables**
  + In class Friday, 11/3
  
+ **Print Chapter 7 Notes for class Monday**
  
## Friday, November 3rd
### Today we will...

+ Quiz 3: Inference for a Single Numerical Variable
+ Introduce Final Group Project

## To do:
  
+ **Lab 6: Hours worked**
  + Due Monday 11/6 at 11:59pm
  
+ **Print Chapter 7 Notes for class Monday**

+ **Group Project Check-point 0: Group Contract**
  + Due Friday 11/10 at 11:59pm


  
