---
title: "Chapter 9: Simple Linear Regression"
format: 
  revealjs:
    auto-stretch: false
    theme: simple
embed-resources: true
---

## Monday, November 27th
### Today we will...

+ Ch. 9 Notes: EDA for two numeric variables
  
::: callout-warning
### MONDAY OFFICE HOURS 
Now 2pm - 3pm
:::

## To do:
  
+ **Homework 8: Squirrel Size**
  + Due Thursday 11/30 at 11:59pm
  
+ **Project Checkpoint 2 (Histograms + Scatterplot?)**
  + Due Friday 12/1 at 11:59pm

::: callout-warning
### MONDAY OFFICE HOURS
Now 2pm - 3pm.
:::

## Tuesday, November 28th
### Today we will...

+ Ch. 9 Notes: Introduce Simple Linear Regression

## To do:

+ **Homework 8: Squirrel Size**
  + Due Thursday 11/30 at 11:59pm
  
+ **Project Checkpoint 2 (Histograms + Scatterplot?)**
  + Due Friday 12/1 at 11:59pm
  
+ **Study for Quiz 4: ANOVA**
  + In class, Friday 12/1

## Thursday, November 30th
### Today we will...

+ Lab 8: Soil Moisture and Early Growth Biomass for Strawberries

## To do:

+ **Homework 8: Squirrel Size**
  + Due Thursday 11/30 at 11:59pm
  
+ **Lab 8: Soil Moisture and Early Growth Biomass for Strawberries**
  + Due Monday 12/4 at 11:59pm
  
+ **Project Checkpoint 2 (Histograms + Scatterplot?)**
  + Due Friday 12/1 at 11:59pm
  
+ **Study for Quiz 4: ANOVA**
  + In class, Friday 12/1


## Friday, December 1st
### Today we will...

+ Quiz 4: ANOVA (~20 minutes)
+ Project work time
  
## To do:
  
+ **Lab 8: Soil Moisture and Early Growth Biomass for Strawberries**
  + Due Monday 12/4 at 11:59pm
  
+ **Project Checkpoint 2 (Histograms + Scatterplot?)**
  + Due Friday 12/1 at 11:59pm

+ **Homework 9: Golf Driving Distances**
  + Optional for Practice on Linear Regression
