{
  "hash": "8e551d974b9b81bd2c163f25d3dffbba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Post-hoc inference in ANOVA\"\nsubtitle: \"Estimating group means and contrasts\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    tbl-colwidths: [50, 30, 30, 50]\n    mermaid:\n      theme: neutral\nexecute: \n  echo: false\n  warning: false\n  message: false\n---\n\n::: {.cell}\n\n:::\n\n\n## Today's agenda\n\n1. [lecture] inference on group means and contrasts after performing ANOVA\n2. [lab] estimates, tests, and intervals using `emmeans`\n\n## From before: diet restriction\n\n::: {.cell}\n\n:::\n\n\n::: {.columns}\n\n::: {.column width=\"40%\"}\n**Data summaries**:\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-posthoc_files/figure-revealjs/unnamed-chunk-3-1.png){width=528}\n:::\n\n::: {.cell-output-display}\n\n----------------------------\n diet    mean     sd     n  \n------- ------- ------- ----\n  NP     27.4    6.134   49 \n\n N/N85   32.69   5.125   57 \n\n N/R50   42.3    7.768   71 \n\n N/R40   45.12   6.703   60 \n----------------------------\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"60%\"}\n**Inference using ANOVA**:\n\n$$\n\\begin{align*}\n&H_0: \\mu_\\text{NP} = \\mu_\\text{N/N85} = \\mu_\\text{N/R50} = \\mu_\\text{N/R40} \\\\\n&H_A: \\text{at least two means differ}\n\\end{align*}\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- aov(lifetime ~ diet, data = longevity)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \ndiet          3  11426    3809   87.41 <2e-16 ***\nResiduals   233  10152      44                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n> The data provide strong evidence that diet restriction has an effect on mean lifetime among mice (*F = 87.41* on *3* and *233* degrees of freedom, *p < 0.0001*).\n:::\n\n:::\n\n## Follow-up questions\n\nThe ANOVA tells us there's evidence of an effect of diet restriction on lifespan. \n\nSo now we'd want to know:\n\n1. What are the mean lifespans for each level of restriction?\n2. For which levels of dietary restriction do mean lifespans differ?\n3. What are the gains in mean lifespan for each level of restriction relative to an unrestricted diet?\n4. For which levels of restriction are gains in mean lifespan significant?\n\nAnswers require *post-hoc* inferences (done after-the-fact) on:\n\n- group means $\\mu_i$ (question 1)\n- \"contrasts\" $\\mu_i - \\mu_j$ (questions 2-4)\n\n## Estimates for group means\n\n> Interval estimates for group means in ANOVA use a model-based standard error.\n\n::: {.columns}\n\n::: {.column width=\"60%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(object = fit, spec = ~ diet) |> \n  confint(level = 0.95)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n--------------------------------------------\n diet    estimate     SE         95% CI     \n------- ---------- -------- ----------------\n  NP       27.4     0.943    (25.54, 29.26) \n\n N/N85    32.69     0.8743   (30.97, 34.41) \n\n N/R50     42.3     0.7834   (40.75, 43.84) \n\n N/R40    45.12     0.8522   (43.44, 46.8)  \n--------------------------------------------\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"40%\"}\nInterval estimates use a \"pooled\" standard deviation:\n\n$$SE_i = \\frac{s_\\text{pooled}}{\\sqrt{n_i}} = \\frac{\\sqrt{MSE}}{\\sqrt{n_i}}$$\n\nOtherwise identical to $t_{n - k}$ confidence intervals.\n:::\n\n:::\n\nRationale: \n\n- the ANOVA model assumes equal variability (standard deviations) across groups\n- better precision (for variability estimates, not means) when assumption holds\n\n## Bonferroni adjustment\n\n> Problem: several 95% intervals don't have simultaneous 95% coverage.\n\n- *individual* coverage: how often *one* interval covers the population mean\n- *simultaneous* coverage: how often *all* intervals cover population means *at the same time*\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-posthoc_files/figure-revealjs/unnamed-chunk-7-1.png){width=576}\n:::\n:::\n\n:::\n\n::: {.column}\nThe **Bonferroni correction** for $k$ intervals consists in changing the individual coverage level to $\\left(1 - \\frac{\\alpha}{k}\\right)\\%$.\n\n- Effectively a width increase\n- Guarantees joint coverage $(1 - \\alpha)\\%$\n- Tends to be over conservative with many means (large $k$)\n:::\n\n:::\n\n## Implementation in R\n\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# table\nemmeans(object = fit, spec = ~ diet) |>\n  confint(level = 0.95, adjust = 'bonferroni')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n diet  emmean    SE  df lower.CL upper.CL\n NP      27.4 0.943 233     25.0     29.8\n N/N85   32.7 0.874 233     30.5     34.9\n N/R50   42.3 0.783 233     40.3     44.3\n N/R40   45.1 0.852 233     43.0     47.3\n\nConfidence level used: 0.95 \nConf-level adjustment: bonferroni method for 4 estimates \n```\n\n\n:::\n:::\n\n\n- note Bonferroni adjustment\n- these are model-based estimates that depend on the fitted ANOVA model\n\n:::\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# visualization\nemmeans(object = fit, spec = ~ diet) |>\n  confint(level = 0.95, adjust = 'bonferroni') |>\n  plot(xlab = 'mean lifespan (months)', \n       ylab = 'diet')\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-posthoc_files/figure-revealjs/unnamed-chunk-10-1.png){width=480}\n:::\n:::\n\n\n:::\n\n:::\n\n*Caution: these intervals do NOT indicate which means differ significantly.*\n\n## Pairwise comparisons\n\n> Pairwise comparisons are inferences made on \"contrasts\" between pairs of means.\n\nThe difference $\\mu_{NP} - \\mu_{N/N85}$ is an example of a contrast. It is common to perform inference on all pairwise contrasts to determine which means differ and by how much.\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(object = fit, specs = ~ diet) |> \n  contrast('pairwise')\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n    difference       estimate    SE   \n------------------- ---------- -------\n   NP - (N/N85)       -5.289    1.286 \n   NP - (N/R50)       -14.9     1.226 \n   NP - (N/R40)       -17.71    1.271 \n (N/N85) - (N/R50)    -9.606    1.174 \n (N/N85) - (N/R40)    -12.43    1.221 \n (N/R50) - (N/R40)    -2.819    1.158 \n\n\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"45%\"}\n\n- estimates are $\\bar{x}_i - \\bar{x}_j$\n- $SE_{ij} = SE(\\bar{x}_i - \\bar{x}_j) = s_\\text{pooled}\\sqrt{\\frac{1}{n_i} + \\frac{1}{n_j}}$\n- inference based on a $t_{n - k}$ model\n    \n    + degrees of freedom: $n - k$\n    + tests: $T_{ij} = \\frac{\\bar{x}_i - \\bar{x}_j}{SE_{ij}}$\n    + intervals: $\\bar{x}_i - \\bar{x}_j \\pm c\\times SE_{ij}$\n:::\n\n:::\n\n*Multiplicity corrections must adjust for the number of contrasts (6), not means (4).*\n\n\n## Pairwise comparisons: tests\n\n> Which means differ significantly? All except R50 and R40.\n\n::: {.columns}\n\n::: {.column}\n`emmeans` *then* `contrast` *then* `test`:\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(object = fit, specs = ~ diet) |>\n  contrast('pairwise') |>\n  test(adjust = 'bonferroni')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate   SE  df t.ratio p.value\n NP - (N/N85)         -5.29 1.29 233  -4.113  0.0003\n NP - (N/R50)        -14.90 1.23 233 -12.150  <.0001\n NP - (N/R40)        -17.71 1.27 233 -13.938  <.0001\n (N/N85) - (N/R50)    -9.61 1.17 233  -8.183  <.0001\n (N/N85) - (N/R40)   -12.43 1.22 233 -10.177  <.0001\n (N/R50) - (N/R40)    -2.82 1.16 233  -2.436  0.0937\n\nP value adjustment: bonferroni method for 6 tests \n```\n\n\n:::\n:::\n\n- *p*-values are adjusted for multiplicity\n- reject if *adjusted* *p*-value is below the significance threshold\n:::\n\n::: {.column}\nHypotheses for pairwise tests:\n\n$$\\begin{cases} H_0: \\mu_i - \\mu_j = 0 \\\\ H_A: \\mu_i - \\mu_j \\neq 0 \\end{cases}$$\nTest statistic:\n\n$$T_{ij} = \\frac{\\bar{x}_i - \\bar{x}_j}{SE_{ij}}$$\n\n$p$-values are obtained from a $t_{n - k}$ model for the sampling distribution of $T_{ij}$.\n\n:::\n\n:::\n\n## Pairwise comparisons: tests\n\n> Which means differ significantly? All except R50 and R40.\n\n::: {.columns}\n\n::: {.column}\n`emmeans` *then* `contrast` *then* `test`:\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(object = fit, specs = ~ diet) |>\n  contrast('pairwise') |>\n  test(adjust = 'bonferroni')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate   SE  df t.ratio p.value\n NP - (N/N85)         -5.29 1.29 233  -4.113  0.0003\n NP - (N/R50)        -14.90 1.23 233 -12.150  <.0001\n NP - (N/R40)        -17.71 1.27 233 -13.938  <.0001\n (N/N85) - (N/R50)    -9.61 1.17 233  -8.183  <.0001\n (N/N85) - (N/R40)   -12.43 1.22 233 -10.177  <.0001\n (N/R50) - (N/R40)    -2.82 1.16 233  -2.436  0.0937\n\nP value adjustment: bonferroni method for 6 tests \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\nInterpretation:\n\n> The data provide evidence at the 5% significance level that mean lifespan differs among all levels of diet restriction except the N/R40 and N/R50 groups (*p* = 0.0937), for which the evidence is suggestive but inconclusive.\n:::\n\n:::\n\n## Multiple testing correction matters\n\n> Using unadjusted $p$-values will inflate type I error rates.\n\n::: {.columns}\n\n::: {.column}\nsetting `adjust = 'none'`:\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(object = fit, specs = ~ diet) |>\n  contrast('pairwise') |>\n  test(adjust = 'none')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate   SE  df t.ratio p.value\n NP - (N/N85)         -5.29 1.29 233  -4.113  0.0001\n NP - (N/R50)        -14.90 1.23 233 -12.150  <.0001\n NP - (N/R40)        -17.71 1.27 233 -13.938  <.0001\n (N/N85) - (N/R50)    -9.61 1.17 233  -8.183  <.0001\n (N/N85) - (N/R40)   -12.43 1.22 233 -10.177  <.0001\n (N/R50) - (N/R40)    -2.82 1.16 233  -2.436  0.0156\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\nFailure to adjust for multiple inferences leads to a different conclusion:\n\n> The data provide evidence at the 5% significance levelthat mean lifespan differs among all levels of diet restriction.\n\n:::\n\n:::\n\nThis is *incorrect*, because the joint significance level is not 5%.\n\nWithout adjustment, type I error could be as high as $k\\times\\alpha = 6\\times 0.05 = 0.3$!\n\n## Pairwise comparisons: intervals\n\n> How much do means differ? Anywhere from 2 - 21 months, depending.\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\n`emmeans` *then* `contrast` *then* `confint`:\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(object = fit, specs = ~ diet) |> \n  contrast('pairwise') |>\n  confint(level = 0.95, adjust = 'bonferroni')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate   SE  df lower.CL upper.CL\n NP - (N/N85)         -5.29 1.29 233    -8.71   -1.867\n NP - (N/R50)        -14.90 1.23 233   -18.16  -11.633\n NP - (N/R40)        -17.71 1.27 233   -21.10  -14.333\n (N/N85) - (N/R50)    -9.61 1.17 233   -12.73   -6.482\n (N/N85) - (N/R40)   -12.43 1.22 233   -15.67   -9.177\n (N/R50) - (N/R40)    -2.82 1.16 233    -5.90    0.261\n\nConfidence level used: 0.95 \nConf-level adjustment: bonferroni method for 6 estimates \n```\n\n\n:::\n:::\n\n\n- `level` specifies *joint* coverage after adjustment\n:::\n\n::: {.column width=\"45%\"}\nIntervals are for the parameter $\\mu_i - \\mu_j$:\n\n$$\\bar{x}_i - \\bar{x}_j \\pm c\\times SE_{ij}$$\n\nThe critical value $c$ is obtained from the $t_{n - k}$ model.\n\nFor a $(1 - \\alpha)\\times 100\\%$ confidence interval with Bonferroni correction: \n\n$$c = \\left(1 - \\frac{\\alpha}{2k}\\right) \\;\\text{quantile}$$\n\n:::\n\n:::\n\n## Pairwise comparisons: intervals\n\n> How much do means differ? Anywhere from 2 - 21 months, depending.\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\n`emmeans` *then* `contrast` *then* `confint`:\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(object = fit, specs = ~ diet) |> \n  contrast('pairwise') |>\n  confint(level = 0.95, adjust = 'bonferroni')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate   SE  df lower.CL upper.CL\n NP - (N/N85)         -5.29 1.29 233    -8.71   -1.867\n NP - (N/R50)        -14.90 1.23 233   -18.16  -11.633\n NP - (N/R40)        -17.71 1.27 233   -21.10  -14.333\n (N/N85) - (N/R50)    -9.61 1.17 233   -12.73   -6.482\n (N/N85) - (N/R40)   -12.43 1.22 233   -15.67   -9.177\n (N/R50) - (N/R40)    -2.82 1.16 233    -5.90    0.261\n\nConfidence level used: 0.95 \nConf-level adjustment: bonferroni method for 6 estimates \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"45%\"}\nInterpretations are the same as usual:\n\n> With 95% confidence, mean lifespan on a normal diet is estimated to exceed mean lifespan on an unrestricted diet by between 1.87 and 8.71 months, with a point estimate of 5.29 months difference (SE 1.29).\n:::\n\n:::\n\n## Pairwise comparisons: visualizations\n\n::: {.columns}\n\n::: {.column width=\"45%\"}\nAnother option is to visualize the pairwise comparison inferences by displaying simultaneous 95% intervals.\n\nEasy to spot significant contrasts:\n\n- intervals exclude 0 $\\Leftrightarrow$ tests reject\n:::\n\n::: {.column width=\"55%\"}\n`emmeans` *then* `contrast` *then* `confint` *then* `plot`:\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(object = fit, specs = ~ diet) |>\n  contrast('pairwise') |>\n  confint(level = 0.95, adjust = 'bonferroni') |>\n  plot(xlab = 'difference in mean lifetime (months)', \n       ylab = 'contrast')\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](week8-posthoc_files/figure-revealjs/unnamed-chunk-20-1.png){width=576}\n:::\n:::\n\n\n:::\n\n\n:::\n\n\n\n## Comparisons with a control\n\n> Does diet restriction increase mean lifespan, and if so by how much?\n\n::: {.columns}\n\n::: {.column width=\"60%\"}\nSpecify `contrast('trt.vs.ctrl')`:\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(object = fit, specs = ~ diet) |> \n  contrast('trt.vs.ctrl') |>\n  confint(level = 0.95, adjust = 'dunnett')\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n   contrast     estimate    SE         95% CI     \n-------------- ---------- ------- ----------------\n (N/N85) - NP    5.289     1.286    (2.23, 8.34)  \n (N/R50) - NP     14.9     1.226   (11.98, 17.81) \n (N/R40) - NP    17.71     1.271   (14.7, 20.73)  \n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"40%\"}\n\n- Multiple inference adjustment uses Dunnett's method \n    \n    + specialized correction for comparisons with a control\n    + `adjust = 'dunnett'`\n    \n- Comparisons will be relative to first group in R\n:::\n\n:::\n\nWith 95% confidence, relative to an unrestricted diet...\n\n- a 85kcal/day diet increases lifespan by an estimated 2.23 to 8.34 months\n- a 50kcal/day diet increases lifespan by an estimated 11.98 to 17.81 months\n- a 40kcal/day diet increases lifespan by an estimated 14.70 to 20.73 months\n\n\n# Extras\n\n## Log contrasts: relative change\n\n> Can we instead estimate a *percent change* in lifespan relative to the control?\n\n::: {.columns}\n\n::: {.column width=\"44%\"}\nThe contrast in log-lifetimes would be:\n\n$$\n\\log(\\mu_{N85}) - \\log(\\mu_{NP}) = \\log\\left(\\frac{\\mu_{N85}}{\\mu_{NP}}\\right)\n$$\nSo to answer the question:\n\n1. refit the ANOVA model with *log* lifetimes\n2. compute contrasts with control group using Dunnett's method\n3. exponentiate estimates to obtain ratios (and hence percentages)\n:::\n\n::: {.column width=\"56%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.log <- aov(log(lifetime) ~ diet, data = longevity)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n  contrast    estimate      95% CI    \n------------ ---------- --------------\n (N/R50)/NP    1.572     (1.42, 1.73) \n (N/R40)/NP    1.688     (1.52, 1.87) \n\n\n:::\n:::\n\n\nFact: mean log lifetime = log median lifetime.\n\n> With 95% confidence, diet restriction to 40kcal (a 52.9% reduction) is estimated to increase median lifespan in mice by 52% to 87%, with a point estimate of 68.8%.\n\n*Extra credit: work out and interpret the interval estimate for the contrast not shown above.*\n:::\n\n:::\n\n\n## Power calculations for ANOVA\n\n> How much data should we collect to detect a difference in mean lifespan of 1 month?\n\n::: {.columns}\n\n::: {.column}\nTo perform sample size power calculations, one needs:\n\n- number of groups\n- target significance level ($\\alpha$)\n- target power level\n- guess or prior estimate of variance ratio $\\frac{\\text{group variation}}{\\text{error variation}}$\n\n\n::: {.cell}\n\n:::\n\n\nFrom the existing study, $\\sqrt{MSE} = 6.6$\n:::\n\n::: {.column}\nSo to detect effects on the order of one month at 90% power:\n\n::: {.cell}\n\n```{.r .cell-code}\npower.anova.test(groups = 4, \n                 sig.level = 0.05, \n                 power = 0.9, \n                 within.var = 6.633, \n                 between.var = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Balanced one-way analysis of variance power calculation \n\n         groups = 4\n              n = 32.32851\n    between.var = 1\n     within.var = 6.633\n      sig.level = 0.05\n          power = 0.9\n\nNOTE: n is number in each group\n```\n\n\n:::\n:::\n\n... we need 33 mice per treatment group.\n:::\n\n:::",
    "supporting": [
      "week8-posthoc_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}