---
title: "Review session 1"
subtitle: "Weeks 1-3 [L1, L2, L3]: study design, data semantics, and descriptive statistics"
format: 
  revealjs:
    logo: img/poly-logo-2.jpg
    footer: "STAT218"
    smaller: true
    mermaid:
      theme: neutral
execute: 
  echo: false
  warning: false
  message: false
---

```{r}
library(oibiostat)
library(tidyverse)
library(pander)
```

## Outcomes

-   \[L1\] design a data collection scheme based on simple random sampling or simple experimental designs

-   \[L2\] distinguish between observational studies and experiments and understand the limitations (practical and consequential) of each

-   \[L3\] summarize data using graphical and numerical techniques

## Lecture/lab recap

Week/day | Lecture | Lab
---|---|---
1/W | Experiments and observational studies | Reading abstracts
2/M | Data vocabulary, proportions and means, common notation | Loading data, extracting variables, computing means and proportions
2/W | Measures of location/center and spread, simple graphics | Histograms, barplots, summary statistics
3/M | Graphics and tables for two variables, interpreting relationships, correlation | Stacked bar plots, side-by-side boxplots, scatterplots

: {tbl-colwidths="[20,80]"}

## Assignment recap

Problem set | Topics
---|---
PS1 | Interpreting study descriptions
PS2 | Summary statistics (mean, proportion) for one variable; identifying variable types
PS3 | Measures of location and spread for one variable; visualizing frequency distributions
PS4 | Visualizing relationships between two variables (C/C, C/N, N/N)

: {tbl-colwidths="[20,80]"}

## Questions: [L1, L2] study design

- Experiment or observational study?
- Describe the population
- Describe the sample
- Identify the outcomes
- Identify variable types

## Questions: [L3] descriptive statistics

- Compute/interpret mean/median/percentiles/IQR/variance/SD
- Compute/interpret a grouped summary with one or more of the above measures
- Determine appropriate measures of location/center/spread
- Make/interpret a table of proportions for values of a categorical variable
- Make/interpret a contingency table
- Make/interpret a histogram
- Make/interpret two-way tables of proportions
- Make/interpret stacked bar plots representing proportions
- Make/interpret side-by-side boxplots
- Make/interpret scatterplots
- Compute/interpret correlations

## Commonly missed question types

Identifying appropriate measures of center/spread (*i.e.*, understanding robustness)
Grouped summaries (getting syntax right)
Determining 

## Key concepts

- [L1, L2] Experiments and observational studies
- [L1, L2] Samples and populations
- [L2] Variable types: categorical (nominal/ordinal) and numeric (discrete/continuous)
- [L3] Summary statistics: mean, median, percentile, IQR, SD, variance, correlation
- [L3] Distribution properties: skewness, outliers, modes
- [L3] Robustness of common summary statistics
- [L3] Relationships: positive/negative; linear/nonlinear

## About the test

- 4-5 questions
- Expect one challenge part, but otherwise very similar to homework problems and practice questions
- 48 hours, open book, open note
- Posit cloud project + fillable form
- Revisions will be allowed to earn back credit
- No collaboration
- Do your own analysis/writing (no AI plagiarism)