{
  "hash": "fc650a6e0705e3e4bcd817d30bc37348",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 7: Directional $t$-tests\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  eval: true\n  echo: true\n  message: false\n  warning: false\nformat: \n  html:\n    toc: true\n  docx:\n    toc: false\nprefer-html: true\nembed-resources: true\n---\n\n\n\nThis lab has two objectives:\n\n1.  Learn to use the `t.test(...)` function\n2.  Learn to discern the appropriate direction for a $t$ test\n\nWe'll use two familiar datasets: body temperature and heart rate measurements for 39 individuals; and data on birth weights and weeks at birth for a sample of 100 births in North Carolina in 2004.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload('data/temps.RData')\nload('data/nhanes.RData')\nncbirths <- read_csv('data/ncbirths.csv')\n```\n:::\n\n\n\n### The `t.test(...)` function\n\nThe `t.test(...)` function produces both a hypothesis test and an confidence interval, and can be used to obtain either or both in practice.\n\nLet's demonstrate with the practice problem you completed most recently: inference on the mean nightly hours of sleep among U.S. adults based on NHANES data.\n\nThe default behavior of `t.test(...)` if given no arguments besides a vector of data is to test $H_0: \\mu = 0$ against a two-sided alternative ($H_A: \\mu \\neq 0$) and provide a 95% confidence interval. There are three key arguments that allow you to adjust this behavior:\n\n-   `mu = ...` adjusts the value for the mean in the null hypothesis $H_0$\n\n    -   default `mu = 0`\n\n-   `alternative = ...` adjusts the direction of the alternative, with options\n\n    -   `'less'` for a lower-sided alternative\n    -   `'greater'` for an upper-sided alternative\n    -   `'two.sided'` (default) for a two-sided alternative\n\n-   `conf.level = ...` adjusts the confidence level for the interval estimate\n\n    -   default `conf.level = 0.95`\n\nThe examples below illustrate this usage. Run each command and **look at the output closely to determine what changes**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract sleep variable\nsleep <- nhanes$sleephrsnight\n\n# default behavior (these are equivalent)\nt.test(sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sleep\nt = 284.36, df = 3178, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 6.911123 7.007090\nsample estimates:\nmean of x \n 6.959107 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(sleep, mu = 0, alternative = 'two.sided', conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sleep\nt = 284.36, df = 3178, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 6.911123 7.007090\nsample estimates:\nmean of x \n 6.959107 \n```\n\n\n:::\n\n```{.r .cell-code}\n# change null value to 7 hours of sleep\nt.test(sleep, mu = 7, alternative = 'two.sided', conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sleep\nt = -1.671, df = 3178, p-value = 0.09482\nalternative hypothesis: true mean is not equal to 7\n95 percent confidence interval:\n 6.911123 7.007090\nsample estimates:\nmean of x \n 6.959107 \n```\n\n\n:::\n\n```{.r .cell-code}\n# change the confidence level\nt.test(sleep, mu = 7, alternative = 'two.sided', conf.level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sleep\nt = -1.671, df = 3178, p-value = 0.09482\nalternative hypothesis: true mean is not equal to 7\n99 percent confidence interval:\n 6.896032 7.022182\nsample estimates:\nmean of x \n 6.959107 \n```\n\n\n:::\n\n```{.r .cell-code}\n# change the direction of the alternative\nt.test(sleep, mu = 7, alternative = 'less', conf.level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sleep\nt = -1.671, df = 3178, p-value = 0.04741\nalternative hypothesis: true mean is less than 7\n99 percent confidence interval:\n     -Inf 7.016067\nsample estimates:\nmean of x \n 6.959107 \n```\n\n\n:::\n:::\n\n\n\nFocus for a moment on the last example. In detail, this tests, at the 1% significance level, the hypotheses:\n\n$$\n\\begin{cases}\nH_0: &\\mu = 7 \\\\\nH_A: &\\mu < 7\n\\end{cases}\n$$\n\nWhile the `conf.level` argument doesn't affect the $p$-value, it does imply a significance level -- in this case, $\\alpha = 0.01$. So, even though the $p$-value is less than the conventional level ($p < 0.05$), it is not less than the implied significance level (here $p > 0.01$), so **the test output implies we'd fail to reject the hypothesis that adults sleep less than 7 hours**.\n\nIn general, it's important to set the confidence level to correspond to the significance level of the test you wish to perform, so that the test interpretation and interval provided match.\n\n::: callout-note\n## Your turn 1\n\nAdjust the arguments of the `t.test(...)` function to achieve the following:\n\n-   find a 90% CI for the mean\n-   test whether mean sleep is 6.9 at the 5% level\n-   test whether mean sleep is 6.9 at the 1% level\n-   test whether mean sleep exceeds 6.9 at the 5% level\n-   test whether mean sleep exceeds 6.9 at the 1% level\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# obtain a 90% confidence interval for the mean hours of sleep\n\n# test whether mean sleep is 6.9 at the 5% level\n\n# test whether mean sleep is 6.9 at the 1% level\n\n# test whether mean sleep exceeds 6.9 at the 5% level\n\n# test whether mean sleep exceeds 6.9 at the 1% level\n```\n:::\n\n\n\nFor extra practice, write a short interpretation of the results of each test following the style introduced in class.\n:::\n\n### Distinguishing directional alternatives\n\nHere we'll use the temperature/heartrate data to illustrate a variety of directional tests based on questions of interest.\n\nAs you're looking over the examples, focus on the correspondence between the questions and the direction of the alternative.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract body temperature variable\nbodytemps <- temps$body.temp\n\n# is mean temperature different from 98.6 at the 5% significance level?\nt.test(bodytemps, mu = 98.6, alternative = 'two.sided', conf.level = 0.95)\n\n# is mean temperature less than 98.6 at the 5% significance level?\nt.test(bodytemps, mu = 98.6, alternative = 'less', conf.level = 0.95)\n\n# is mean temperature greater than 98.1 at the 5% significance level?\nt.test(bodytemps, mu = 98.1, alternative = 'greater', conf.level = 0.95)\n\n# is mean temperature greater than 98.1 at the 1% significance level?\nt.test(bodytemps, mu = 98.1, alternative = 'greater', conf.level = 0.99)\n\n# is mean temperature less than 98.9 at the 5% significance level?\nt.test(bodytemps, mu = 98.9, alternative = 'less', conf.level = 0.95)\n```\n:::\n\n\n\nAs an aside (but an important one!), performing all of these tests together is only meant to illustrate how the function works, **not how to perform an analysis**. Trying out many tests until you obtain significant results is known as \"$p$ hacking\", and is not an acceptable practice.\n\n::: callout-note\n## Your turn 2\n\nUsing the `heart.rate` variable, test the following hypotheses:\n\n-   Is mean heart rate 65bpm at the 5% level?\n-   Is mean heart rate 70bpm at the 1% level?\n-   Is mean heart rate greater than 70bpm at the 1% level?\n-   Is mean heart rate less than 75bpm at the 10% level?\n-   Is mean heart rate greater than 75bpm at the 10% level?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract heart rate variable\n\n# is mean heart rate 65bpm at the 5% level?\n\n# is mean heart rate 70bpm at the 1% level?\n\n# is mean heart rate greater than 70bpm at the 1% level?\n\n# is mean heart rate less than 75bpm at the 10% level?\n\n# is mean heart rate greater than 75bpm at the 10% level?\n```\n:::\n\n\n:::\n\n### A brief analysis\n\nNow that you're familiar with using the `t.test(...)` function, let's do something a bit more realistic. Suppose that, using the `ncbirths` data, you want to perform inference on the number of weeks at birth. We're told that 40 weeks is typical.\n\n#### Advance decisions\n\nIn advance of looking at the data (or perhaps even having data) we should determine:\n\n1.  the hypotheses to test\n2.  the level at which we'll perform the test\n\nTo make these choices, first note that there's no obvious directional question to ask here. So, we'll test whether the mean number of weeks at birth is 40. A 5% significance level is conventional, so we'll stick with that.\n\n#### Assessing assumptions\n\nBefore going ahead, let's inspect the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract variable of interest\nweeks <- ncbirths$weeks\n\n# inspect distribution\nhist(weeks, breaks = 15)\n```\n\n::: {.cell-output-display}\n![](lab7-directional_files/figure-docx/analysis example- checking assumptions-1.png)\n:::\n:::\n\n\n\nThis is an interesting case, because we do have a left-skewed distribution *and* there are a few outliers below 30 weeks. However, the sample size is large ($n = 100$), so the test should still work well regardless.\n\n#### Performing the test\n\nFor inference we'll want to report a test result and interval estimate. Both of these are obtained using `t.test(...)` as above, but of course we only perform *one* test/interval calculation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# inference\nt.test(weeks, mu = 40, alternative = 'two.sided', conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  weeks\nt = -5.0421, df = 99, p-value = 2.084e-06\nalternative hypothesis: true mean is not equal to 40\n95 percent confidence interval:\n 37.97938 39.12062\nsample estimates:\nmean of x \n    38.55 \n```\n\n\n:::\n:::\n\n\n\nTake a moment to inspect the results.\n\n#### Interpreting results\n\nFollowing the format in class, a report of the results should interpret the test and interval in context, providing supporting statistics parenthetically:\n\n> Data from North Carolina in 2004 provide strong evidence that the mean number of weeks at birth differs from 40 (*T* = -5.0421 on 99 degrees of freedom, *p* \\< 0.0001). With 95% confidence, the mean number of weeks at birth is estimated to be between 37.98 and 39.12 weeks, with a point estimate of 38.55 weeks (SE 0.289).\n\n### Practice problems\n\n1.  Perform and interpret the results of inference on the mean birth weight to investigate the claim that the typical birth weight is at least 7 lbs. Carry out inference at the 5% significance level.\n\n    a.  Determine your hypotheses.\n    b.  Check test assumptions.\n    c.  Perform the calculations.\n    d.  Write a short report of the results.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n2.  \\[[REVISED]{style=\"color:red\"}\\] Using the BRFSS data, test whether [actual body weight exceeds desired body weight]{style=\"color:red\"} and estimate the difference. Perform the test at the 1% level.\n\n\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "lab7-directional_files/figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}