---
title: "Homework 2: Can Marine sniff out cancer?"
subtitle: "Inference and Confidence Intervals for a Single Categorical Variable"
embed-resources: true
format:
  html:
    toc: true
  pdf:
    keep-tex: false
    include-in-header:
      text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}
          \fancyhead[R]{Homework 2: Can Marine sniff out cancer?}
          \fancyfoot[C]{\thepage}
  docx:
    toc: false
# format: html
# format: docx
# format: revealjs
execute:
  echo: false
  warning: false
  message: false
---

Can dogs sniff out cancer? In 2011, an article published by the medical journal *Gut - An International Journal of Gastroenterology and Hepatology* (Sonoda et al.) reported the results of a study conducted in Japan in which a dog was tested to see whether she could detect colorectal cancer. The dog used was an eight-year-old black Labrador named Marine. (As her name might suggest, she was originally trained for water rescues.) The study was designed so that the dog first smelled a bag that had been breathed into by a patient with colorectal cancer. This was the standard that the dog would use to judge the other bags. Marine then smelled the breath in five different bags from five different patients, only one of which contained breath from a colorectal cancer patient (not the same as the original patient); the others contained breath from noncancer patients. The dog was then trained to sit next to the bag which she thought contained breath from a cancer patient (i.e., had the cancer scent). If she sat down next to the correct bag, she was rewarded with a tennis ball.

Marine completed 33 attempts of this experimental procedure, with a different set of five patients each time: four noncancer patients and one cancer patient. And, each time, the researchers recorded whether or not she correctly identified the bag with the breath of the cancer patient.

In the 33 attempts, Marine chose the correct bag 14 times.

**Research Question** Is there statistical evidence that Marine correctly identifies the bag with the breath of the cancer patient more often than chance?

**Setup**

1.  Identify the following in context of the scenario:

-   Population of interest:

\vspace{0.5in}

-   Sample of interest:

\vspace{0.5in}

-   Variable of interest (and data type):

\vspace{0.5in}

-   Parameter of interest (assign a symbol):

\vspace{0.8in}

-   Statistic of interest (assign a symbol and value):

\vspace{0.5in}

**Carry out the formal hypothesis test to address the research question.**

2.  Write (first in words, and then using symbols) the null hypothesis and the alternative hypothesis.

-   Null hypothesis

\vspace{0.8in}

-   Alternative hypothesis

\vspace{0.8in}

3.  Carry out a simulation study with 1000 replicated simulations to investigate the research question (sketch or paste your simulation results here).

\vspace{0.8in}

\hfill Use the simulation results to estimate the p-value: \_\_\_\_\_\_\_\_

4.  Interpret the p-value.

\vspace{0.8in}

5.  Based on the p-value, state a conclusion about this study in context of the problem.

\vspace{0.8in}

6.  Is it *possible* that, in general, Marine just randomly picks a bag from the five bags, and the observed proportion of trials she picked the correct bag was by chance (i.e. luck) alone?

> **Choose one:** \hspace{0.2in} Yes \hspace{0.2in} No

\vspace{0.8in}

**Interval Estimate of Marine's Proportion of Success**

8.  What is the *point estimate* (or "best guess") for the proportion of times Marine accurately identifies the bag with the breath of the cancer patient? (assign a symbol)

\vspace{0.5in}

9.  Calculate the *standard error* (using Normal Approximation Method) associated with this point estimate.

\vspace{0.8in}

10. Calculate the *margin of error* for a 95% confidence interval.

\vspace{0.8in}

11. Find the *endpoints* of the 95% confidence interval. Interpret the interval.

\vspace{0.8in}

Sketch the following values for our example on the normal curve shown below:

-   the point estimate
-   the lower and upper endpoints
-   the margin of error.

```{r}
#| fig-pos: "H"
#| echo: false
library(tidyverse)
phat = 14/33
n = 33
x_norm <- tibble("x" = seq(0,1, 0.001),
                           "dnorm" = dnorm(x, 
                                           mean = phat, 
                                           sd = sqrt((phat*(1-phat))/n)
                                           )* (1 / n)
                           )
x_norm |> 
  ggplot(aes(x = x, y = dnorm)) +
  geom_line(color = "steelblue",
            size = 1
            ) +
  labs(x = "Proportion of trials that Marine correctly identifies",
       y = "Binomial Probability") +
  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.1)) +
  theme_bw() +
  theme(aspect.ratio = 0.4)
```

12. Where does the proportion of times Marine accurately identifies the bag with the breath of the cancer patient *under* the assumption that Marine is just "randomly picking" a bag (i.e., null value) fall within the 95% confidence interval?

\vspace{0.2in}

> Sketch this value on the plot in Question 11.

> Why does this make sense?

\vspace{0.8in}

13. Suppose instead, Marine completes 99 attempts and chooses the correct bag 42 times.

\vspace{1in}

-   What parts of your 95% confidence interval calculation changed?

> **Select all that apply:**

> Point Estimate \hspace{0.1in} Standard Error \hspace{0.1in} Multiplier for the Margin of Error

-   What happens to your 95% confidence interval compared to the original confidence interval based on 33 trials? The confidence interval:

> **Choose one:** \hspace{0.2in} Narrows \hspace{0.2in} Stays the same \hspace{0.2in} Widens

> Why does this make sense?

\vspace{0.8in}

14. Suppose instead of calculating a 95% confidence interval, scientists want to report a 99% confidence interval for the original 33 trials.

\vspace{1in}

-   What parts of your confidence interval calculation changed?

> **Select all that apply:**

> Point Estimate \hspace{0.1in} Standard Error \hspace{0.1in} Multiplier for the Margin of Error

-   What happens to your confidence interval compared to the original 95% confidence interval based on 33 trials? The confidence interval:

> **Choose one:** \hspace{0.2in} Narrows \hspace{0.2in} Stays the same \hspace{0.2in} Widens

> Why does this make sense?

\vspace{0.8in}

15. Check the conditions necessary to use Normal Approximation of binomial probabilities to calculate a confidence interval (i.e., Wald interval) for the proportion of times Marine accurately identifies the bag with the breath of the cancer patient.

\vspace{0.5in}

> Does the Wald interval seem to be appropriate for the original 33 trials?

\vspace{0.5in}

::: callout-caution
## Canvas Quiz

Make sure to complete the Homework Quiz on Canvas.
:::
