---
title: "Homework 3: Which cow breeds have mastitis?"
subtitle: "Inference for a Categorical Variable with More than Two Categories"
embed-resources: true
format:
  html:
    toc: true
  pdf:
    keep-tex: false
    include-in-header:
      text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}
          \fancyhead[R]{Homework 3: XXXX}
          \fancyfoot[C]{\thepage}
  docx:
    toc: false
# format: html
# format: docx
# format: revealjs
execute:
  echo: false
  warning: false
  message: false
---


Mastitis is xxxx 

Data has been collected for dairy farmer Selberg's herd of cows, which is in Southwestern Minnesota.

The following data was obtained from the Minnesota Department of Education website.  



Dairy Farmer Selberg's herd

**Research Question:** Is there evidence to suggest that the breed pattern of cows with mastitis deviates from breed patterns in dairy farmer Selberg's herd?


1. Identify the following for this scenario:

+ Observation
+ Sample
+ 

2. State the parameters (Hint: there are 4 of them)

3. Write your hypotheses.

Consider the following table. The first row of this table contains the Observed Outcomes for Grade 6 students from Fillmore County (male and female tallies were combined). The second row contains the Expected Outcome (under the null hypothesis) for each of the possible survey responses.

4. The value in the first row and second column is 9 (i.e. Observed count in the Slight Risk category).  Explain where this number came from.  What does this value represent?

5.	What does the Total value for the Observed row represent?

6. How did we get ???

7. Fill in the rest of the expected counts in the chart above. 

8. Calculate chi square

9. Visit <> for the data and carry out a simulation of 1000 replications.

\vspace{0.5in}

::: callout-caution
## Canvas Quiz

Make sure to complete the Homework Quiz on Canvas.
:::

