{
  "hash": "a9710fb042efeefdc09701cb84e6cfa1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 8: Two-sample inference\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  eval: true\n  echo: true\n  message: false\n  warning: false\nformat: html\n---\n\n::: {.cell}\n\n:::\n\n\nThis lab focuses on two-sample inference for differences in population means. The main objectives are:\n\n1. Learn to implement two-sample $t$ tests in R\n2. Practice distinguishing directional and nondirectional tests and providing appropriate specifications to the `t.test(...)` function in R\n\n\nThe lab uses several datasets for which we will consider two-sample comparisons:\n\n- `finch`: mean finch beak depths in generations before and after a drought on Daphne Major\n- `temps`: body temperatures and heart rates for men and women\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload('data/finch.RData')\nload('data/temps2.RData')\n```\n:::\n\n\nExamples will utilize the `finch` data; you'll practice using the `temps` data. Here are the summary statistics for the `finch` data for reference:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinch |>\n  group_by(year) |>\n  summarize(depth.mean = mean(depth),\n            depth.sd = sd(depth),\n            n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n   year depth.mean depth.sd     n\n  <int>      <dbl>    <dbl> <int>\n1  1976       9.45    0.962    58\n2  1978      10.2     0.807    65\n```\n\n\n:::\n:::\n\n\n### Checking assumptions for two-sample tests\n\nA two-sample $t$ test can be used whenever two one-sample tests are appropriate. So, to check assumptions, we need to inspect the frequency distributions of the variable of interest in *both* samples.\n\n#### Option A: two histograms\n\nOne way to do this is to make two separate histograms. To do that, we'll need to separate the samples. This can be done by 'filtering' observations according to whether year is 1978 or 1976.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# separate samples\nfinch.1978 <- finch |> filter(year == 1978)\nfinch.1976 <- finch |> filter(year == 1976)\n\n# extract depths\ndepth.1978 <- finch.1978$depth\ndepth.1976 <- finch.1976$depth\n\n# make histograms\nhist(depth.1978)\n```\n\n::: {.cell-output-display}\n![](lab8-twosample_files/figure-html/checking assumptions option A-1.png){width=384}\n:::\n\n```{.r .cell-code}\nhist(depth.1976)\n```\n\n::: {.cell-output-display}\n![](lab8-twosample_files/figure-html/checking assumptions option A-2.png){width=384}\n:::\n:::\n\n\nBoth distributions are a bit left-skewed, but each sample is large enough that this isn't a problem for performing the test.\n\n::: callout-note\n## Your turn 1\n\nFilter the `temps` data by sex to separate the samples, and make histograms of the heart rates. Comment on whether assumptions seem to be met.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# separate samples\n\n# extract heart rates\n\n# make histograms\n```\n:::\n\n:::\n\n#### Option B: side-by-side boxplots\n\nA slightly more efficient alternative is to make side-by-side boxplots. This doesn't involve filtering the data, and will produce just a single graphic. \n\nHowever, some details of the distribution (such as multiple modes) may not be evident from the boxplots, so it's not a perfect substitute for checking histograms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# side-by-side boxplots\nboxplot(depth ~ year, data = finch, horizontal = T)\n```\n\n::: {.cell-output-display}\n![](lab8-twosample_files/figure-html/checking assumptions option B-1.png){width=384}\n:::\n:::\n\n\nHere we want to see two things:\n\n- approximate symmetry of boxes\n- few to no large outliers\n\nWhile there is a bit of left skewness, the sample sizes are large enough that it's not a concern.\n\n::: callout-note\n## Your turn 2\n\nMake side-by-side boxplots for heart rate and reassess test assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# side-by-side boxplots for heart rate\n```\n:::\n\n\n:::\n\n\n### Two-sample $t$-tests\n\nGiven that assumptions seem plausible (both samples show little skew and few outliers, and are sufficiently large), we can go ahead with the test. To test whether the drought imposed selection pressure on the finch population, we want to know whether finch beak depth increased after the drought.\n\nObserve, first, which sample appears first in the dataset: 1976. R will treat this as the first sample; to keep track of directions, we'll want to formulate the hypotheses as a comparison between 1976 (first sample) and 1978 (second sample).\n\nWe want to test whether the mean of the first sample is less than the mean of the second:\n\n$$\n\\begin{cases}\nH_0: &\\mu_{1976} = \\mu_{1978} \\\\\nH_A: &\\mu_{1976} < \\mu_{1978} \n\\end{cases}\n$$\nLet's carry out the test at the 5% significance level. The inputs to `t.test(...)` that implement this test are:\n\n- a formula `<VARIABLE> ~ <SAMPLE>` as the first argument: `formula = depth ~ year`\n- a data frame containing the variable names mentioned in the formula: `data = finch`\n- a null value for the difference: `mu = 0`\n- an alternative: `alternative = 'less'`\n- a confidence level to complement the significance level of the test: `conf.level = 0.95`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# perform t test (notice which group comes first)\nt.test(formula = depth ~ year, data = finch, mu = 0, alternative = 'less', conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  depth by year\nt = -4.5727, df = 111.79, p-value = 6.255e-06\nalternative hypothesis: true difference in means between group 1976 and group 1978 is less than 0\n95 percent confidence interval:\n       -Inf -0.4698812\nsample estimates:\nmean in group 1976 mean in group 1978 \n          9.453448          10.190769 \n```\n\n\n:::\n:::\n\n\nTake a moment to inspect the output and identify each number appearing. We'd report the test result as follows:\n\n> The data provide very strong evidence that mean beak depth increased in the generation of finches following the drought (*T* = -4.5727 on 111.79 degrees of freedom, *p* < 0.0001). With 95% confidence, the mean beak depth is estimated to have increased by at least 0.4699 mm, with a point estiamte of 0.7373 mm (SE 0.1612).\n\nThe point estimate and standard error can be retrieved by storing the output of `t.test(...)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# store t test result\ntt.rslt <- t.test(formula = depth ~ year, data = finch, mu = 0, alternative = 'less', conf.level = 0.95)\n\n# estimates\ntt.rslt$estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean in group 1976 mean in group 1978 \n          9.453448          10.190769 \n```\n\n\n:::\n\n```{.r .cell-code}\n# estimate for difference in means\ntt.rslt$estimate |> diff()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean in group 1978 \n          0.737321 \n```\n\n\n:::\n\n```{.r .cell-code}\n# standard error for estimate of difference in means\ntt.rslt$stderr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1612445\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Your turn 3\n\nTest whether mean heart rate differs between men and women at the 1% significance level. Report the test result, confidence interval, and point estimate and standard error for the difference in means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# perform t test\n\n# store t test result\n\n# estimate for difference in means\n\n# standard error\n```\n:::\n\n\n:::\n\n\n### Practice problems\n\n1. Using the `temps2` dataset, test whether mean body temperature is lower for men. \n\n    a. Check the assumptions for the test by making *both* a pair of histograms *and* side-by-side boxplots.\n    b. Perform the test at the 1% significance level. \n    c. Report the test result, confidence interval, and point estimate and standard error for the difference in means.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab8-twosample_files/figure-html/practice problem 1-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](lab8-twosample_files/figure-html/practice problem 1-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](lab8-twosample_files/figure-html/practice problem 1-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  body.temp by sex\nt = 2.2854, df = 127.51, p-value = 0.01197\nalternative hypothesis: true difference in means between group female and group male is greater than 0\n99 percent confidence interval:\n -0.008923783          Inf\nsample estimates:\nmean in group female   mean in group male \n            98.39385             98.10462 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean in group female   mean in group male \n            98.39385             98.10462 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean in group male \n        -0.2892308 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.126554\n```\n\n\n:::\n:::\n\n\n2. Using the `brfss2` data, test whether actual body weight exceeds desired body weight by more for women than for men.\n\n    a. Check the assumptions for the test by making *both* a pair of histograms *and* side-by-side boxplots.\n    b. Perform the test at the 1% significance level. \n    c. Report the test result, confidence interval, and point estimate and standard error for the difference in means.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  sex   weight wtdesire weight.diff\n  <chr>  <dbl>    <dbl>       <dbl>\n1 m        265      225          40\n2 m        150      150           0\n3 m        137      150         -13\n4 f        159      125          34\n5 f        145      125          20\n6 f        125      120           5\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lab8-twosample_files/figure-html/practice problem 2-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](lab8-twosample_files/figure-html/practice problem 2-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](lab8-twosample_files/figure-html/practice problem 2-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  weight.diff by sex\nt = 2.048, df = 38.875, p-value = 0.02368\nalternative hypothesis: true difference in means between group f and group m is greater than 0\n99 percent confidence interval:\n -3.108832       Inf\nsample estimates:\nmean in group f mean in group m \n      26.354839        9.517241 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean in group m \n       -16.8376 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.22135\n```\n\n\n:::\n:::\n",
    "supporting": [
      "lab8-twosample_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}