---
title: "Chapter 4: Inference for Two Categorical Variables"
format: 
  revealjs:
    auto-stretch: false
    theme: simple
embed-resources: true
---

## Monday, October 16th
### Today we will...

+ Review explanatory/response variables
+ Simulation for Example 4.1

## To do:

+ **Lab 3: Chi-square Goodness of Fit Test**
  + Due TONIGHT at 11:59pm
  
+ **Homework 4: Fatal Injuries in the Iliad**
  + Due Thursday 10/19 at 11:59pm

::: callout-warning
Don't forget to take the Canvas Quiz **AND** submit your completed assignment.
:::

## Tuesday, October 17th
### Today we will...

+ Chi-square test for Example 4.1
+ Examples 4.2 & 4.3 (in groups)

::: callout-caution
### Wednesday Office Hours

Moved to 11:30am - 12:20pm. I have a dentist appointment.

*(Original 1:10pm - 2pm)*

:::

## To do:
  
+ **Homework 4: Fatal Injuries in the Iliad**
  + Due Thursday 10/19 at 11:59pm

::: callout-warning
Don't forget to take the Canvas Quiz **AND** submit your completed assignment.
:::
  
  
::: callout-caution
### Wednesday Office Hours

Moved to 11:30am - 12:20pm. I have a dentist appointment.

*(Original 1:10pm - 2pm)*

:::

## Thursday, October 19th
### Today we will...

+ Lab 4: Nightlight use and myopia

## To do:
  
+ **Homework 4: Fatal Injuries in the Iliad**
  + Due Thursday 10/12 at 11:59pm
  
+ **Lab 4: Nightlight use and myopia**
  + Due Monday 10/23 at 11:59pm
  
## Friday, October 20th
### Today we will...

+ Review Examples 4.2 and 4.3
+ Observation vs Experiment
+ Discuss upcoming exam expectations

## To do:
  
+ **Lab 4: Nightlight use and myopia**
  + Due Monday 10/23 at 11:59pm
  
+ **Study for Midterm Exam 1**
  + In-class, Tuesday 10/24
  
