---
title: "Final Review + Project Worktime"
format: 
  revealjs:
    auto-stretch: false
    theme: simple
embed-resources: true
---

## Monday, December 4th
### Today we will...

+ Finish Ch. 9 Notes: Inference for Slope
  
::: callout-warning
### MONDAY OFFICE HOURS 
Now 2pm - 3pm
:::

## To do:
  
+ **Lab 8: Soil Moisture and Early Growth Biomass for Strawberries**
  + Due Monday 12/4 at 11:59pm
  
+ **Homework 9: Golf Driving Distances**
  + Optional for Practice on Linear Regression
  
+ **Final Project Submission**
  + Due Friday 12/8 at 11:59pm
  
+ **Take Course Evaluation** by Friday at 11:59pm
 
::: callout-warning
### MONDAY OFFICE HOURS
Now 2pm - 3pm.
:::

## Tuesday, December 5th
### Today we will...

+ Take Course Evaluation
+ Group project work time!

## To do:

+ **Homework 9: Golf Driving Distances**
  + Optional for Practice on Linear Regression
  
+ **Final Project Submission**
  + Due Friday 12/8 at 11:59pm

+ **Take Course Evaluation** by Friday at 11:59pm

## Thursday, December 7th
### Today we will...

+ KaHoot Review
+ Review/Project work time

## To do:

+ **Homework 9: Golf Driving Distances**
  + Optional for Practice on Linear Regression
  
+ **Final Project Submission**
  + Due Friday 12/8 at 11:59pm
  + Individual Reflection due Monday 12/11
  
+ **Study for Final Exam**
  + 7am: Friday 12/15 at 7:10am
  + 8am: Monday 12/11 at 7:10am

+ **Take Course Evaluation** by Friday at 11:59pm

## Friday, December 8th
### Today we will...

+ Review/Project work time
  
## To do:
  
+ **Homework 9: Golf Driving Distances**
  + Optional for Practice on Linear Regression
  
+ **Final Project Submission**
  + Due Friday 12/8 at 11:59pm
  + Individual Reflection due Monday 12/11
  
+ **Study for Final Exam**
  + 7am: Friday 12/15 at 7:10am
  + 8am: Monday 12/11 at 7:10am

+ **Take Course Evaluation** by Friday at 11:59pm