{
  "hash": "4b7616b5587464c791f93fc1b02d83d5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tests for directional hypotheses\"\nsubtitle: \"\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    mermaid:\n      theme: neutral\nexecute: \n  echo: false\n  warning: false\n  message: false\n---\n\n::: {.cell}\n\n:::\n\n\n## Today's agenda\n\n1. Quick review of decision criteria for the $t$ test\n2. [lecture] test-interval relationship; directional $t$ tests\n3. [lab] upper-sided, lower-sided, and two-sided tests for the population mean\n\n## Recap: decision criteria\n\n> A hypothesis test boils down to deciding whether your estimate is too far from a hypothetical value for that hypothesis to be plausible.\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\nTo test the hypotheses:\n\n$$\n\\begin{cases}\nH_0: &\\mu = \\mu_0 \\\\\nH_A: &\\mu \\neq \\mu_0\n\\end{cases}\n$$\n\nWe use the test statistic:\n\n$$\nT = \\frac{\\bar{x} - \\mu_0}{SE(\\bar{x})}\n\\quad\\left(\\frac{\\text{estimation error under } H_0}{\\text{standard error}}\\right)\n$$\n:::\n\n::: {.column width=\"40%\"}\nWe say $H_0$ is implausible at level $\\alpha$ if either:\n\n- $|T| > q$ for the $\\alpha$-critical value $q$\n\n    + $q$ is the $1 - \\frac{\\alpha}{2}$ quantile of the $t_{n - 1}$ model\n\n- $\\underbrace{P(|T| > |T_\\text{observed}|)}_\\text{p-value} < \\alpha$\n:::\n\n:::\n\nThis procedure controls the error rate $\\alpha$: the proportion of samples for which we'd make a false rejection.\n\n## From last time\n\n*Practice problem: test the hypothesis that the average U.S. adult sleeps 8 hours.*\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-directional_files/figure-revealjs/unnamed-chunk-3-1.png){width=336}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculations\nsleep.mean <- mean(sleep) \nsleep.mean.se <- sd(sleep)/sqrt(length(sleep))\ntstat <- (sleep.mean - 8)/sleep.mean.se \ncrit.val <- qt(0.975, df = 3178) \np.val <- 2*pt(abs(tstat), df = 3178, lower.tail = F)\nci <- sleep.mean + c(-1, 1)*crit.val*sleep.mean.se\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n--------------------------------------------------\n estimate   std.err   tstat    cval       pval    \n---------- --------- -------- ------- ------------\n  6.959     0.02447   -42.53   1.961   2.622e-313 \n--------------------------------------------------\n\n\n:::\n:::\n\n\n95% confidence interval: (6.91, 7.01)\n:::\n\n::: {.column width=\"40%\"}\nA complete narrative summary:\n\n> The data provide evidence that the average U.S. adult does not sleep 8 hours per night (*T* = -42.53 on 3178 degrees of freedom, *p* < 0.0001). With 95% confidence, the mean nightly hours of sleep among U.S. adults is estimated to be between 6.91 and 7.01 hours, with a point estimate of 6.59 hours (SE: 0.0245).\n:::\n\n:::\n\n## Tests and intervals\n\n> Tests and intervals are usually reported together\n\nConsider how the test and interval provide complementary information:\n\n- the test tells you U.S. adults don't sleep 8 hours\n- the interval tells you how much they *do* sleep\n\nIt is reasonable that they should be consistent, and in fact they are.\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculations\nsleep.mean <- mean(sleep) \nsleep.mean.se <- sd(sleep)/sqrt(length(sleep))\ntstat <- (sleep.mean - 8)/sleep.mean.se \ncrit.val <- qt(0.975, df = 3178) \np.val <- 2*pt(abs(tstat), df = 3178, lower.tail = F)\nci <- sleep.mean + c(-1, 1)*crit.val*sleep.mean.se\n```\n:::\n\n:::\n\n::: {.column width=\"45%\"}\n> Notice that the critical value in the 5% significance level test is exactly the same as that used in the 95% confidence interval.\n:::\n\n:::\n\n## Tests and intervals\n\nThe critical value used in a $\\alpha$ significance level test is identical to the critical value used in a $(1 - \\alpha)$ interval. Consequently:\n\n$$\n\\underbrace{\\bar{x} - c\\times SE(\\bar{x}) < \\mu_0 < \\bar{x} + c\\times SE(\\bar{x})}_\\text{hypothesized value is in the interval}\n\\quad\\Longleftrightarrow\\quad\n\\underbrace{-c < \\frac{\\bar{x} - \\mu_{0}}{SE(\\bar{x})} < c}_{|T| < c}\n$$\n\nMeaning: the interval includes exactly those values that the test fails to reject.\n\n- Sensible considering both use the same information: the distance between the point estimate and population mean, relative to the variability of the estimate\n\n## Tests and intervals\n\n> The level-$\\alpha$ test rejects $H_0: \\mu = \\mu_0$ exactly when $\\mu_0$ is outside the $(1 - \\alpha)\\times 100$% confidence interval for $\\mu$.\n\n\n::: {.columns}\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-directional_files/figure-revealjs/unnamed-chunk-7-1.png){width=576}\n:::\n:::\n\n:::\n\n::: {.column}\nLeft, $p$-values for a sequence of tests:\n\n- $p > 0.05$ precisely for $\\mu_0$ in 95% CI\n- $p > 0.01$ precisely for $\\mu_0$ in 99% CI\n\nIn other words:\n\n$$\\text{level $\\alpha$ test rejects} \\Longleftrightarrow \\text{$1 - \\alpha$ CI excludes}$$\n\n::: \n\n:::\n\n\n## The `t.test(...)` function\n\nSince tests and intervals go together, there is a single R function that computes both.\n\n::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(sleep, mu = 8, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sleep\nt = -42.533, df = 3178, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 8\n95 percent confidence interval:\n 6.911123 7.007090\nsample estimates:\nmean of x \n 6.959107 \n```\n\n\n:::\n:::\n\n\n::: \n\n::: {.column width=\"50%\"}\nNo critical value is reported, so you have to make the decision using the $p$ value:\n\n- $p < \\alpha$: reject\n- $p > \\alpha$: fail to reject\n:::\n\n:::\n\nTake a moment to locate each component of the test and estimates from the output.\n\n## Interpreting $p$-values\n\n> $p$-values measure the strength of evidence against $H_0$ and favoring $H_A$: smaller $p$-values indicate stronger evidence; larger $p$-values indicate weaker evidence.\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\nThe mathematical definition is:\n$$p = P(|T| > |T_\\text{observed}|)$$ \n\n- technically, the probability under $H_0$ that $T$ exceeds the observed value in magnitude\n- informally, how unusual/rare your data are\n\n:::\n\n::: {.column width=\"45%\"}\nAs a measure of the strength of evidence favoring the alternative:\n\nvalue | strength of evidence\n---|---\n$p < 0.001$ | very strong\n$0.001 < p < 0.01$ | strong\n$0.01 < p < 0.05$ | moderate\n$0.05 < p < 0.1$ | suggestive\n$0.1 < p$ | no evidence\n:::\n\n:::\n\n## Your turn: interpret these $p$-values\n\n> Don't just match the value to the table; add context, and state the test outcome.\n\n::: {.columns}\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# example 1\nt.test(sleep, mu = 6.8)$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.205865e-11\n```\n\n\n:::\n\n```{.r .cell-code}\n# example 2\nt.test(sleep, mu = 6.9)$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01578191\n```\n\n\n:::\n\n```{.r .cell-code}\n# example 3\nt.test(sleep, mu = 7)$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09482291\n```\n\n\n:::\n\n```{.r .cell-code}\n# example 4\nt.test(sleep, mu = 7.1)$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.366935e-09\n```\n\n\n:::\n\n```{.r .cell-code}\n# example 5\nt.test(sleep, mu = 7.2)$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.532371e-22\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\nvalue | strength of evidence\n---|---\n$p < 0.001$ | very strong\n$0.001 < p < 0.01$ | strong\n$0.01 < p < 0.05$ | moderate\n$0.05 < p < 0.1$ | suggestive\n$0.1 < p$ | no evidence\n:::\n\n:::\n\nExample: \"**the data** [DO/DO NOT] **provide** [STRENGTH] **evidence that** [ALTERNATIVE]\"\n\n## A directional test\n\n> Does the average U.S. adult sleep *less than* 7 hours?\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\nThis example leads to a *directional* test:\n\n$$\n\\begin{cases}\nH_0: &\\mu = 7 \\\\\nH_A: &\\mu < 7\n\\end{cases}\n$$\n\nThe test statistic is the same as before:\n\n$$\nT = \\frac{\\bar{x} - 7}{SE(\\bar{x})} = -1.671\n$$\n:::\n\n::: {.column width=\"45%\"}\nThe *lower-sided* $p$-value is 0.0474:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week5-directional_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=624}\n:::\n:::\n\n\n:::\n\n:::\n\nFor the $p$-value, we look at how often $T$ is larger *in the direction of the alternative*.\n\n- in this case, how often $T$ is smaller (underestimate by more)\n\n## The other direction\n\n> Does the average U.S. adult sleep ***more** than* 7 hours?\n\n::: {.columns}\n\n::: {.column width=\"55%\"}\nNow the alternative is the opposite direction:\n\n$$\n\\begin{cases}\nH_0: &\\mu = 7 \\\\\nH_A: &\\mu > 7\n\\end{cases}\n$$\n\nThe test statistic is the same as before:\n\n$$\nT = \\frac{\\bar{x} - 7}{SE(\\bar{x})} = -1.671\n$$\n:::\n\n::: {.column width=\"45%\"}\nThe ***upper**-sided* $p$-value is 0.9526:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week5-directional_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=624}\n:::\n:::\n\n\n:::\n\n:::\n\nFor the $p$-value, we look at how often $T$ is larger *in the direction of the alternative*.\n\n- in this case, how often $T$ is **larger** (**over**estimate by more)\n\n## Directional hypotheses\n\nTests for the mean can involve directional or non-directional alternatives. We refer to these as one-sided and two-sided tests, respectively.\n\n| Test type   | Alternative      | Direction favoring alternative |\n|-------------|------------------|--------------------|\n| Upper-sided | $\\mu > \\mu_0$    | larger $T$       |\n| Lower-sided | $\\mu < \\mu_0$    | smaller $T$       |\n| Two-sided   | $\\mu \\neq \\mu_0$ | larger $|T|$        |\n\nThe direction of the test affects the $p$-value calculation (and thus decision), but *won't* change the test statistic.\n\nConceptually tricky, but easy in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# upper-sided\nt.test(ddt, mu = mu_0, alternative = 'greater')\n\n# lower-sided\nt.test(ddt, mu = mu_0, alternative = 'less')\n\n# two-sided (default)\nt.test(ddt, mu = mu_0, alternative = 'two.sided')\n```\n:::\n\n\n\n## Three $t$-tests\n\n::: {.columns}\n\n::: {.column width=\"33%\"}\nDo U.S. adults sleep 7 hours per night?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# two sided test\nt.test(sleep, \n       mu = 7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sleep\nt = -1.671, df = 3178, p-value = 0.09482\nalternative hypothesis: true mean is not equal to 7\n95 percent confidence interval:\n 6.911123 7.007090\nsample estimates:\nmean of x \n 6.959107 \n```\n\n\n:::\n:::\n\n\n> Suggestive but insufficient evidence that U.S. adults don't sleep 7 hours\n\n:::\n\n::: {.column width=\"33%\"}\nDo U.S. adults sleep less than 7 hours per night?\n\n::: {.cell}\n\n```{.r .cell-code}\n# lower-sided test\nt.test(sleep, \n       mu = 7, \n       alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sleep\nt = -1.671, df = 3178, p-value = 0.04741\nalternative hypothesis: true mean is less than 7\n95 percent confidence interval:\n     -Inf 6.999372\nsample estimates:\nmean of x \n 6.959107 \n```\n\n\n:::\n:::\n\n\n> Moderate evidence that U.S. adults sleep less than 7 hours\n\n:::\n\n::: {.column width=\"34%\"}\nDo U.S. adults sleep more than 7 hours per night?\n\n::: {.cell}\n\n```{.r .cell-code}\n# upper-sided test\nt.test(sleep, \n       mu = 7, \n       alternative = 'greater')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sleep\nt = -1.671, df = 3178, p-value = 0.9526\nalternative hypothesis: true mean is greater than 7\n95 percent confidence interval:\n 6.918841      Inf\nsample estimates:\nmean of x \n 6.959107 \n```\n\n\n:::\n:::\n\n\n> No evidence that U.S. adults sleep more than 7 hours\n:::\n\n:::\n\n\n## Another example: DDT data\n\nThe following are 15 measurements of the pesticide DDT in kale in parts per million (ppm).\n\n\n::: {.cell}\n::: {.cell-output-display}\n_2.79_, _2.93_, _3.22_, _3.78_, _3.22_, _3.38_, _3.18_, _3.33_, _3.34_, _3.06_, _3.07_, _3.56_, _3.08_, _4.64_ and _3.34_\n:::\n:::\n\n\n> C. E. Finsterwalder (1976) Collaborative study of an extension of the Mills et al method for the determination of pesticide residues in food. J. Off. Anal. Chem. 59, 169–171.\n\nImagine the target level for safety considerations is 3ppm or less, and you want to use this data to determine whether the mean DDT level is within safe limits.\n\n$$\n\\begin{cases}\nH_0: &\\mu = 3 \\quad(\\text{null hypothesis})\\\\\nH_A: &\\mu > 3 \\quad(\\text{alternative hypothesis})\n\\end{cases}\n$$\n\n*We choose this direction because we're concerned with evidence that mean DDT **exceeds** the threshold.* \n\n## Another example: DDT data\n\n::: columns\n::: {.column width=\"45%\"}\n**If in fact $\\mu = 3$**, then according to the $t$ model 0.58% of samples would produce an error of this magnitude or more in the direction of the alternative:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-directional_files/figure-revealjs/unnamed-chunk-17-1.png){width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(ddt, mu = 3, alternative = 'greater')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  ddt\nt = 2.9059, df = 14, p-value = 0.005753\nalternative hypothesis: true mean is greater than 3\n95 percent confidence interval:\n 3.129197      Inf\nsample estimates:\nmean of x \n    3.328 \n```\n\n\n:::\n:::\n\n\n> The data provide strong evidence that mean DDT in kale exceeds 3ppm (*T* = 2.9059 on 14 degrees of freedom, *p* = 0.0058). With 95% confidence, the mean DDT is estimated to be at least 3.129, with a point estimate of 3.32 (SE: 0.1168).\n:::\n:::\n\n*Notice the one-sided interval! (`Inf` = $\\infty$.) This is called a \"lower confidence bound\".*\n\n\n## Your turn: which alternative?\n\n> Write the hypotheses in notation and identify which test (upper/lower/two sided) should be used.\n\nUsing the temperature/heartrate data:\n\n1. Is mean body temperature less than 98.6°F?\n2. Is mean heart rate greater than 60 bpm? \n3. Is mean heart rate 65 bpm?\n\nUsing the NC births data:\n\n1. Is the mean number of weeks at birth 40?\n2. Is the mean birth weight at least 7 lbs?\n3. Is the mean birth weight under 8 lbs?",
    "supporting": [
      "week5-directional_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}