{
  "hash": "58a83fa664a834ec4ce51a280b561d4a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 7 activity: Nonparametric inference\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  echo: true\n  eval: true\n  message: false\n  warning: false\nformat: \n  html:\n    toc: true\n  docx:\n    toc: false\nprefer-html: true\nembed-resources: true\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload('data/brfss.RData')\nload('data/temps.RData')\nddt <- MASS::DDT\n```\n:::\n\n\n\nIn this activity you'll learn about nonparametric alternatives to the $t$ test for one and two means. The activity is organized much like a lab, but with extra narrative. You should read through the narrative at your own pace and try the exercises provided as you go. At the end there are two practice problems that you'll be expected to complete before next class.\n\n### Background: parametric and nonparametric inference\n\nConsider the basis for the inferences developed so far: under certain conditions (typically regularity of the underlying population distribution, assessed by checking histograms for unimodality and approximate symmetry) and with sufficient sample sizes, a model is specified for the sampling distribution of a test statistic. \n\n- inference for one mean: $t_{n - 1}$ model for the sampling distribution of $T = \\frac{\\bar{x} - \\mu}{SE(\\bar{x})}$\n- inference comparing two means: $t_{\\nu}$ model for the sampling distribution of $T = \\frac{\\bar{x} - \\bar{y} - \\delta}{SE(\\bar{x} - \\bar{y})}$\n- inference comparing several means: $F_{k - 1, n - k}$ model for the sampling distribution of $F = \\frac{MSG}{MSE}$\n\nThese are all what are known as *parametric models*, because they are specified through one or two parameters that determine their exact shape. The parameters in this case are the degrees of freedom terms -- $n - 1$ for the one-sample $t$ test, $\\nu$ (usually estimated) for the two-sample $t$ test, and $k - 1$ and $n - k$ for the $F$ test.\n\nAs such, these procedures are examples of *parametric inference* -- inferences that utilize a parametric model for the data and/or test statistic.\n\nWhen assumptions for parametric inference aren't tenable, or when a parametric model is not available, there are so-called **nonparametric** methods of inference: **methods that don't depend on a parametric model** such as the $t$ or $F$ models we've learned about in class.\n\nWe will consider specifically nonparametric procedures based on ranks, *i.e.*, ordering observations from smallest to largest. \n\n### Motivating examples\n\nIn practice, the situation that most often leads an analyst to consider rank-based nonparametric methods is that the assumptions for the $t$ test either don't hold or are difficult to assess.\n\nBelow are two such situations you've already encountered in this class.\n\n#### Small sample sizes\n\nWhen sample sizes are small, it's awkward to assess assumptions for parametric inference, because with few observations histograms can lack any discernible shape. For example, the most we can say about the following data on heart rates for 19 women and 20 men is that there are no evident outliers.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheart.m <- temps |> filter(sex == 'male') |> pull(heart.rate)\nheart.f <- temps |> filter(sex == 'female') |> pull(heart.rate)\n\npar(mfrow = c(1, 2))\nhist(heart.m)\nhist(heart.f)\n```\n\n::: {.cell-output-display}\n![](week7-activity-nonparametric_files/figure-docx/motivation 1- small sample sizes-1.png)\n:::\n:::\n\n\n\nIn practical terms, the $t$ test is likely still fine under these circumstances; however, some may wish to consider an inference for comparing heart rates between groups that doesn't depend on distributional assumptions.\n\n#### Assumptions don't hold\n\nOn occasion you may go to check assumptions and find that they're clearly violated. For example, the pairwise differences between actual and desired weights from BRFSS respondents showed clear skewness and several large outliers. In that case, the sample size was big enough that we overlooked the issue, but it's not hard to imagine a similar situation cropping up with fewer observations.\n\nSuppose you only had 12 observations that showed the same skew and had one big outlier:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(51424)\nweight.diff <- sample(brfss$weight - brfss$wtdesire, 12)\nhist(weight.diff, breaks = 10)\n```\n\n::: {.cell-output-display}\n![](week7-activity-nonparametric_files/figure-docx/motivation 2- assumptions fail-1.png)\n:::\n:::\n\n\n\nHere the $t$ test isn't appropriate, and using it anyway would likely result in a true significance level, coverage, and power quite different from the nominal levels specified in the test, so it would be hard to trust the result. This is a great situation to use a rank-based nonparametric alternative.\n\n### Inference on \"location\" (not mean)\n\nThe usual parametric inferences pertain to the population mean; not so with rank-based nonparametrics. Instead, these inferences pertain simply to \"location\". \n\nOften \"location\" is characterized in terms of the \"center\" of a distribution so that inferences can be interpreted in a manner similar to parametric tests and intervals. \n\nWe will follow this convention and consider the hypotheses to be about the center(s) of the population model(s), denoted $c$. For example, the two-sided test of center would test the hypotheses:\n\n$$\n\\begin{cases}\nH_0: &c = c_0 \\\\\nH_A: &c \\neq c_0\n\\end{cases}\n$$\n\nFor the two-sided test of difference in centers, we will test the hypotheses:\n\n$$\n\\begin{cases}\nH_0: &c_1 = c_2 \\\\\nH_A: &c_1 \\neq c_2\n\\end{cases}\n$$\n\nHowever, you should keep in mind that \"location\" is a more general notion that encompasses all measures of location of a distribution.\n\n### One-sample inference: signed rank test\n\nThe basic premise of this test is that, if the population model is symmetric, its center should evenly divide the data.\n\n::: callout-tip\n\n## Warm up\n\nConsider the following 15 measurements of DDT in kale in ppm in order from smallest to largest:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(ddt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 2.79 2.93 3.06 3.07 3.08 3.18 3.22 3.22 3.33 3.34 3.34 3.38 3.56 3.78 4.64\n```\n\n\n:::\n:::\n\n\n\nSuppose you wish to test whether the center $c$ of the population model is $c_0 = 3$ ppm and assume a symmetric population model.\n\n1.  How many observations would you expect to be smaller than $c_0 = 3$ if 3ppm is in fact the center?\n2.  How many observations are actually smaller than 3 ppm?\n3.  Based on your answers to 1-2, do you think it is likely that in fact $c = 3$?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n\n## Solution\n\nIf the population is symmetric about $c_0$, you'd expect roughly half of observations (7.5) to be smaller than 3ppm.\n\nThe actual number of observations smaller than 3ppm is:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# number of observations below 3\nsum(ddt < 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n\nThis is much less than half, so it seems unlikely that the center is actually 3ppm.\n:::\n\nThe signed rank test is a nonparametric alternative to the one-sample $t$ test applicable to any symmetric population model. The particular form of symmetry and presence of outliers do not affect the test.\n\n#### Hypotheses\n\nThe test can be directional or two-sided, just like the $t$ test. Thus, the possible hypotheses are: \n\n$$\nH_0: c = c_0 \\quad\\text{vs.}\\quad H_A: c \\mathrel{\\substack{<\\\\\\neq\\\\ >}} c_0\n$$ \n\n#### Test procedure\n\nWhile the intuition of the test is that half of observations should be smaller than the true center under population symmetry, the test statistic is not quite as direct as a tally of how many observations are below the hypothetical value. Instead, the procedure is as follows:\n\n1.  \\[center\\] Calculate deviations $d_i = x_i - c_0$\n\n2.  \\[rank\\] Sort and rank the absolute deviations $|d_i|$\n\n    -   average ranks in case of ties\n    -   drop zeros\n\n3.  \\[sum\\] Add up the positive 'signed ranks' $\\sum_{\\text{sign}(d_i) > 0} r_i$\n\nThis produces the test statistic:\n\n$$V = \\sum_{i = 1}^n \\text{sign}(d_i) \\times R_i$$\n\n::: callout-tip\n\n## Check your understanding\n\nTry working out the rank sum procedure manually using the DDT data -- it's small enough that you could jot down the steps on some scratch paper. See if you can calculate $V$.\n\nTo help, here are the deviations sorted smallest to largest:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate deviations\ndi <- ddt - 3\nsort(di)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] -0.21 -0.07  0.06  0.07  0.08  0.18  0.22  0.22  0.33  0.34  0.34  0.38\n[13]  0.56  0.78  1.64\n```\n\n\n:::\n:::\n\n\n\n1. Start by writing the deviations in order of absolute value in a column. \n2. Then rank them 1-15 in an adjacent column. If there is a tie -- *e.g.*, two absolute deviations of 0.05 -- then assign them both the average of the ranks. For example, if 0.05 occurs twice in positions 2 and 3, then give them both rank 2.5.\n3. Write down the sign of the deviation in a new column.\n4. Then write down the \"signed rank\", or product of the sign and the rank, in a fourth column.\n5. Add up the positive signed ranks. This is the signed rank statistic.\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nThis shows the steps in R, but don't worry about the codes; the output is meant to illustrate what you would do on paper to find the rank sum statistic.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# this shows the steps, column by column; focus on output\nddt.srank <- tibble(di = di) |>\n  mutate(abs.di = abs(di), \n         rank = rank(abs.di),\n         sign = sign(di),\n         signed.rank = sign*rank) |>\n  arrange(abs.di)\nddt.srank\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 5\n        di abs.di  rank  sign signed.rank\n     <dbl>  <dbl> <dbl> <dbl>       <dbl>\n 1  0.0600 0.0600   1       1         1  \n 2 -0.0700 0.0700   2.5    -1        -2.5\n 3  0.0700 0.0700   2.5     1         2.5\n 4  0.0800 0.0800   4       1         4  \n 5  0.180  0.180    5       1         5  \n 6 -0.21   0.21     6      -1        -6  \n 7  0.220  0.220    7.5     1         7.5\n 8  0.220  0.220    7.5     1         7.5\n 9  0.33   0.33     9       1         9  \n10  0.34   0.34    10.5     1        10.5\n11  0.34   0.34    10.5     1        10.5\n12  0.38   0.38    12       1        12  \n13  0.56   0.56    13       1        13  \n14  0.78   0.78    14       1        14  \n15  1.64   1.64    15       1        15  \n```\n\n\n:::\n\n```{.r .cell-code}\n# signed rank statistic\nvstat <- ddt.srank |> filter(sign > 0) |> pull(signed.rank) |> sum()\nvstat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 111.5\n```\n\n\n:::\n:::\n\n\n:::\n\n#### $p$-values for the test\n\nJust like other hypothesis tests, the signed rank test rejects if $V$ is sufficiently large in the direction of the alternative. \n\nA sampling distribution for $V$ can be found exactly using combinatorics, or approximated using probability theory. In this caseWe won't go into details about either approach, except to indicate that there is a sampling distribution for $V$ that we can use to obtain $p$-values in the same fashion that the $t_{n - 1}$ model was used to obtain $p$-values for the $t$ test.\n\nIn this case, there are 3.2768\\times 10^{4} possible sign combinations; of these, only about 0.375% give a larger value of $V$. That provides a $p$-value for the test, and since $p = 0.0018 < 0.05$ we would reject $H_0$ at the 5% significance level. This result is interpreted as:\n\n> The data provide strong evidence that the typical DDT concentration in kale is not 3ppm (signed rank statistic *V* = 111.5, *p* = 0.00375).\n\n#### Implementation with `wilcox.test(...)`\n\nThe implementation in R looks and functions much like `t.test`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# signed rank test at 1% level\nwilcox.test(ddt, mu = 3, alternative = 'two.sided', \n            exact = F, conf.int = T, conf.level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  ddt\nV = 111.5, p-value = 0.003751\nalternative hypothesis: true location is not equal to 3\n99 percent confidence interval:\n 3.060070 3.780032\nsample estimates:\n(pseudo)median \n       3.26001 \n```\n\n\n:::\n:::\n\n\n\nSome remarks:\n- `exact = F` produces approximate $p$-values and confidence intervals; you may see warning messages if this is excluded\n-   pseudo-median is a measure of center, but not the same as a median or mean (check!)\n\n::: callout-note\n## Your turn 1\n\nPerform the analogous inference using the $t$ test and compare the results. Do the tests agree at the 1% significance level?\n\n\n\n\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Solution\nThe tests do not agree: the signed rank test rejects at the 1% level, but the $t$ test does not.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# perform t test at 1% level to compare\nt.test(ddt, mu = 3, alternative = 'two.sided', conf.level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  ddt\nt = 2.9059, df = 14, p-value = 0.01151\nalternative hypothesis: true mean is not equal to 3\n99 percent confidence interval:\n 2.991996 3.664004\nsample estimates:\nmean of x \n    3.328 \n```\n\n\n:::\n:::\n\n\n:::\n\n::: callout-note\n## Your turn 2\n\nPerform the signed rank test to determine whether actual weight exceeds desired weight by more than 10lbs at the 5% significance level. Report the result in the usual narrative format. Compare your result with the inference obtained from a $t$ test.\n\n\n\n\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Solution\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use signed rank test to determine whether actual exceeds desired by at least 10lbs\nwilcox.test(weight.diff, mu = 10, alternative = 'greater', \n            exact = F, conf.int = T, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  weight.diff\nV = 61, p-value = 0.04559\nalternative hypothesis: true location is greater than 10\n95 percent confidence interval:\n 10.00003      Inf\nsample estimates:\n(pseudo)median \n       22.8617 \n```\n\n\n:::\n\n```{.r .cell-code}\n# check t test result to compare\nt.test(weight.diff, mu = 10, alternative = 'greater', conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  weight.diff\nt = 1.6127, df = 11, p-value = 0.06755\nalternative hypothesis: true mean is greater than 10\n95 percent confidence interval:\n 7.019188      Inf\nsample estimates:\nmean of x \n    36.25 \n```\n\n\n:::\n:::\n\n\n\nInterpretation of the signed rank test test:\n\n> The data provide evidence that actual weight exceeds desired weight by more than 10lbs (signed rank statistic *V* = 61, *p* = 0.0456).\n\nThe signed rank test finds evidence that actual weight exceeds desired weight by more than 10lbs, where the $t$ test does not.\n:::\n\n### Two-sample inference: rank sum test\n\nThe rank-sum test is a nonparametric alternative to the two-sample $t$ test based on ranks. The key idea for the test is that if observations in both groups come from the same population distribution then they should be exchangeable (*i.e.*, groupings don't matter).\n\nThus, the only assumption for this test is that data are independent. The test can be directional, and thus it is possible to test the following hypotheses comparing centers:\n\n$$\nH_0: c_1 = c_2\\quad\\text{vs}\\quad H_A: c_1 \\mathrel{\\substack{<\\\\\\neq\\\\>}} c_2\n$$\n\n#### The alternative hypothesis\n\nThis test is a bit funny in that the null hypothesis is really that *the distributions are exactly the same*. The alternative to this possibility can come about in a number of ways. The alternative is usually interpreted as a *difference in location*, primarily because this is the situation that the test has power to detect. \n\nSo, it is often said that the test also assumes that the samples differ only in location. In other words, the test is most appropriate when the histograms look \"shifted\", but not fundamentally different, as illustrated below.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week7-activity-nonparametric_files/figure-docx/unnamed-chunk-1-1.png)\n:::\n:::\n\n\n\nIn all of these cases, there is a (true) difference in location, but if shape differs too much, the rank sum test should *not* be used. That said, it can be hard to tell with small samples, so it may not really be practical to to check this assumption.\n\n\n**Example 1.** Out-of-state tuition costs from 26 public and 26 private universities. These data differ primarily in spread, not location; so the rank-sum test might not work well here. \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week7-activity-nonparametric_files/figure-docx/unnamed-chunk-2-1.png)\n:::\n:::\n\n\n\n\n**Example 2.** Deviations from expected cancer rates in CT in years with high and low sunspot activity. The shape is a bit hard to discern here, but it seems plausible that the distribution for high sunspot years is shifted to the right of that for low sunspot years. So, the rank sum test would be appropriate here.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week7-activity-nonparametric_files/figure-docx/unnamed-chunk-3-1.png)\n:::\n:::\n\n\n\n\n\n#### Rank sum test procedure\n\nThe rank sum procedure, though a bit opaque, is rather simple:\n\n1.  \\[pool\\] Combine observations from both groups\n2.  \\[rank\\] Sort and rank pooled observations\n3.  \\[sum\\] Add up ranks in the first group\n4.  \\[adjust\\] Subtract $\\frac{n_1(n_1 + 1)}{2}$, where $n_1$ is the sample size of the first group\n\nThe test rejects if the sum is larger than expected in the direction of the alternative. As in the signed rank test, combinatorics are used to determine a $p$-value for the test.\n\nThe rationale for this procedure is that if the distributions are the same, then the ranks should be evenly distributed among the two groups; this induces a particular sampling distribution on the sum of the ranks in each group. The adjustment facilitates computation of $p$-values.\n\nLet's illustrate using data from an experiment in which participants were randomly assigned to receive a fish oil supplement or a regular oil supplement. For each subject, the reduction in blood pressure was measured after a period of time on the treatments.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load dataset\nfish.oil <- Sleuth3::ex0112 |> rename_with(tolower)\n\n# make boxplot\nboxplot(bp ~ diet, data = fish.oil, horizontal = T)\n```\n\n::: {.cell-output-display}\n![](week7-activity-nonparametric_files/figure-docx/fish oil data-1.png)\n:::\n:::\n\n\n\nThere's a bit of difference in spread, but enough of a shift in location that the rank sum test is reasonable to apply.\n\n::: callout-tip\n## Check your understanding\n\nCarry out the rank sum procedure outlined above and compute the rank sum statistic by summing up the ranks in the fish oil group.\n\nTo facilitate calculations, here are the data in order of increasing blood pressure:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfish.oil |> arrange(bp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   bp       diet\n1  -6 RegularOil\n2  -4 RegularOil\n3  -3 RegularOil\n4   0    FishOil\n5   0    FishOil\n6   0 RegularOil\n7   1 RegularOil\n8   2    FishOil\n9   2 RegularOil\n10  2 RegularOil\n11  8    FishOil\n12 10    FishOil\n13 12    FishOil\n14 14    FishOil\n```\n\n\n:::\n:::\n\n\n\nAdd a column of ranks by hand (or in R if you can figure out how!), averaging ranks for any ties. Then add up the ranks in the `FishOil` group, and subtract $\\frac{n_1(n_1 + 1)}{2} = \\frac{7\\times 8}{2} = 28$ to obtain the rank sum statistic.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nThe output below illustrates the rankings and selection of which ones to add up. Don't worry about the codes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# again, ignore the codes; look at output\nfish.oil.ranksum <- fish.oil |> \n  mutate(rank = rank(bp),\n         ranks.fish = rank*(diet == 'FishOil')) |>\n  arrange(bp)\nfish.oil.ranksum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   bp       diet rank ranks.fish\n1  -6 RegularOil    1          0\n2  -4 RegularOil    2          0\n3  -3 RegularOil    3          0\n4   0    FishOil    5          5\n5   0    FishOil    5          5\n6   0 RegularOil    5          0\n7   1 RegularOil    7          0\n8   2    FishOil    9          9\n9   2 RegularOil    9          0\n10  2 RegularOil    9          0\n11  8    FishOil   11         11\n12 10    FishOil   12         12\n13 12    FishOil   13         13\n14 14    FishOil   14         14\n```\n\n\n:::\n\n```{.r .cell-code}\n# rank sum statistic\nn1 <- count(fish.oil, diet)$n[1]\nsum(fish.oil.ranksum$ranks.fish) - n1*(n1 + 1)/2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 41\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Implementation using `wilcox.test(...)`\n\nThe `wilcox.test` function also implements the rank sum test, using the same syntax as `t.test(...)`. For example, using the fish oil data, we might test at the 1% significance level whether the fish oil supplement caused a greater reduction in blood pressure:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(bp ~ diet, data = fish.oil, \n            mu = 0, alternative = 'greater', \n            exact = F, conf.int = T, conf.level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  bp by diet\nW = 41, p-value = 0.01957\nalternative hypothesis: true location shift is greater than 0\n99 percent confidence interval:\n -0.9999444        Inf\nsample estimates:\ndifference in location \n              7.999962 \n```\n\n\n:::\n:::\n\n\n\nFor this test, the $p$-value gives the percentage of possible rank allocations among the groups for which the rank sum is at least as favorable to $H_A$; again this is computed using combinatorics or approximation methods.\n\nIn this instance, the $p$-value indicates that only about 1.96% of all possible rank allocations among the two groups would produce a rank sum statistic at least as large. Thus, testing at the 1% significance level:\n\n> The data provide do not provide sufficient evidence at the 1% significance level that the fish oil supplement caused a greater reduction in blood pressure than the regular oil supplement (rank sum statistic *W* = 41, *p* = 0.01957).\n\n::: callout-note\n## Your turn 3\n\nPerform the corresponding $t$ test for comparison at the 1% significance level. Do the tests agree?\n\n\n\n\n\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Solution\n\nThe tests do not agree; the $t$ test supports evidence of an effect at the 1% level where the rank sum test does not.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# t test for effect of treatment at 1% level\nt.test(bp ~ diet, data = fish.oil, mu = 0, \n       alternative = 'greater', conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  bp by diet\nt = 3.0621, df = 9.2643, p-value = 0.006542\nalternative hypothesis: true difference in means between group FishOil and group RegularOil is greater than 0\n95 percent confidence interval:\n 3.111056      Inf\nsample estimates:\n   mean in group FishOil mean in group RegularOil \n                6.571429                -1.142857 \n```\n\n\n:::\n:::\n\n\n:::\n\n::: callout-note\n## Your turn 4\n\nUse the `cancer` dataset (specifically the `delta` variable) to test whether the change in cancer rate is higher in years with high sunspot activity. Carry out the test at the 5% level, and report the result in the usual narrative style.\n\n\n\n\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Solution\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# test whether change in cancer rate is higher in years with high sunspot activity at the 5% level\nwilcox.test(delta ~ sunspot, data = cancer, mu = 0,\n            exact = F, alternative = 'greater', \n            conf.int = T, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  delta by sunspot\nW = 157.5, p-value = 0.3072\nalternative hypothesis: true location shift is greater than 0\n95 percent confidence interval:\n -0.1000484        Inf\nsample estimates:\ndifference in location \n            0.09999013 \n```\n\n\n:::\n:::\n\n\n\nInterpretation:\n\n> The data provide no evidence that the change in cancer rate is higher in years with high sunspot activity (rank sum statistic *W* = 157.5, *p* = 0.3072). \n\n:::\n\n### Practice problem\n\n1. Is there a difference in cholesterol associated with consuming oat bran compared with consuming corn flakes? Use the `cholesterol` dataset to test for a difference at the 5% level using a nonparametric test.\n\n    a. Construct boxplots to compare the distributions for location shift. Does the nonparametric test seem appropriate?\n    b. Carry out the test.\n    c. Report the test result in the usual narrative style.\n\n\n\n",
    "supporting": [
      "week7-activity-nonparametric_files/figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}