---
title: "Homework 1: Study designs"
author: "STAT218"
author-title: "Course"
date: "1/18/24"
published-title: "Due date"
execute: 
  eval: false
format: 
  html:
    toc: true
  docx:
    toc: false
prefer-html: true
embed-resources: true
---

*Instructions: type up your answers and submit your work electronically. Questions with a learning outcome indicated in brackets will be evaluated for credit; other questions are provided for additional practice. You are expected to answer all questions.*

## Education and injury prevention

Suppose you wish to study the efficacy of physical activity and exercise education as a means of sports injury prevention. Your research question is, "does knowledge about injury prevention during physical activity and exercise reduce the risk of injury?". Imagine that ASI offers a short injury prevention training.

Your initial study proposal is as follows:

> 150 Cal Poly students will be selected for the study: 75 from among those who completed the injury prevention training voluntarily, and 75 from among those who did not. Participants will be followed for a year to determine how many in each group experience an injury related to physical activity at any point during the study period. At the end of the study, injury rates will be compared between those that participated in the injury prevention training and those that did not.

1.  \[L2\] Is this an observational study or an experiment? Explain your answer.
2.  \[L1\] How would you go about selecting study participants at random? Propose a specific means of identifying and contacting students to participate in the study.
3.  \[L2\] Imagine you found that those who completed the training are less likely to experience injury. Are these results potentially subject to confounding? If you answer yes, give a hypothetical example of a confounding factor; if you answer no, explain why confounding is not a concern.
4.  \[L1\] If you answered that it is an observational study, propose an experiment that would address the same question. If you answered that it is an experiment, propose an observational study that would address the same question.
5.  \[L2\] Suppose the alternate study you proposed in (4) indicated that those who completed the training are less likely to experience injury. Are these results potentially subject to confounding? If so, give a hypothetical example of a confounding factor; if not, explain why confounding is not a concern.
6.  Is the original proposal a retrospective or prospective study? Explain your answer.
7.  If you answered that it is retrospective, determine an alternate study to investigate the same research question that is instead prospective; if you answered that it is prospective, determine an alternate study that is retrospective. Write a short proposal similar to the above for your alternate study.

## Peanut allergies

Consider the Learning Early About Peanut allergy (LEAP) study discussed in class and in your reading:

> For the LEAP study, 640 infants in the United Kingdom were enrolled with risk factors for peanut allergies (eczema or egg allergy); 530 passed a skin test at the start of the study showing no peanut allergy. Each infant was randomly assigned to peanut consumption (6g peanut protein per day) or peanut avoidance (no peanut consumption) groups. At 5 years of age, an allergy test was administered to each study participant; the rates of peanut allergy were compared between the two groups.

8.  \[L1\] Propose a retrospective observational study to investigate the research question, "is early peanut exposure associated with a lower risk of developing peanut allergies?" Include a specific description of how you might enroll participants.
