{
  "hash": "f92d8fc239312b15afee7d5269ef71e6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tests of association\"\nsubtitle: \"Chi-square tests for independence and association in two-way tables\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    tbl-colwidths: [30, 30, 40, 30]\n    mermaid:\n      theme: neutral\nexecute: \n  echo: false\n  warning: false\n  message: false\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n::: {.cell}\n\n:::\n\n\n## Today's agenda\n\n1. [lecture] tests of association in contingency tables\n2. [lab] $\\chi^2$ tests and residual analysis in R\n\n## Do asthma rates differ by sex?\n\n::: {.columns}\n\n::: {.column width=\"45%\"}\nFrom a subsample of NHANES data:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n---------------------------------\n   &nbsp;     asthma   no asthma \n------------ -------- -----------\n **female**     49        781    \n\n  **male**      30        769    \n---------------------------------\n\n\n:::\n:::\n\n\nInference for the difference in proportions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(asthma$sex, asthma$asthma) |>\n  prop.test(alternative = 'two.sided', \n            conf.level = 0.95,\n            correct = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  table(asthma$sex, asthma$asthma)\nX-squared = 4.0741, df = 1, p-value = 0.04355\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.0007323913 0.0422460305\nsample estimates:\n    prop 1     prop 2 \n0.05903614 0.03754693 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"55%\"}\nInterpretation:\n\n> There is moderate evidence that asthma prevalence differs between men and women (*Z* = 2.108, *p* = 0.0436). With 95% confidence, the difference in prevalence (F - M) is estimated to be between 0.07% and 4.22%, with a point estimate of 2.15%.\n\nThis inference relies on a specific measure of association (difference in prevalence) that we can't always estimate.\n\n*Could we test for association between sex and asthma without relying on a specific measure?*\n:::\n\n:::\n\n## Association and independence\n\n::: {.columns}\n\n::: {.column width=\"59%\"}\nConsider the hypotheses:\n\n$$\n\\begin{cases}\nH_0: &\\text{asthma}\\perp\\text{sex} \\; &(\\text{independence})\\\\\nH_A: &\\neg(\\text{asthma}\\perp\\text{sex}) \\; &(\\text{association})\n\\end{cases}\n$$\n\nConsider also the proportions:\n\n::: {.cell}\n::: {.cell-output-display}\n\n------------------------------------------------\n   &nbsp;     asthma    no asthma      total    \n------------ --------- ------------ ------------\n **female**   0.03008     0.4794       0.5095   \n\n  **male**    0.01842   **0.4721**   **0.4905** \n\n **total**    0.0485    **0.9515**       1      \n------------------------------------------------\n\n\n:::\n:::\n\n\n- $p_{ij}$: proportion of observations in cell $ij$ \n- $p_i$, $p_j$: marginal proportions in row $i$ or column $j$\n\n\n:::\n\n::: {.column width=\"41%\"}\n\nIf sex and asthma are independent:\n\n$$\np_{ij} \\approx p_i \\times p_j\n$$\n\nFor example, we'd expect: \n\n$$\n0.4721 \\approx 0.4905 \\times 0.9515\n$$\n\nIn other words:\n\n- 49% of respondents are men\n- 95% of respondents don't have asthma\n- so roughly 49% of 95% would be men without asthma\n\n\n:::\n\n:::\n\n## Basis for a test: expected counts\n\nExpected proportions translate directly to expected counts:\n$$p_{ij} = p_i \\times p_j \n\\quad\\Longleftrightarrow\\quad n_{ij} = \\frac{n_{i\\cdot} \\times n_{\\cdot j}}{n}$$\n\n::: {.columns}\n\n::: {.column width=\"40%\"}\nActual counts:\n\n&nbsp; | O1 | O2 | total\n---+---+---+---\n**G1** | $n_{11}$ | $n_{12}$ | $\\color{red}{n_{1\\cdot}}$\n**G2** | $n_{21}$ | $n_{22}$ | $\\color{orange}{n_{2\\cdot}}$\n**total** | $\\color{blue}{n_{\\cdot 1}}$ | $\\color{green}{n_{\\cdot 2}}$ | $n$\n:::\n\n::: {.column width=\"60%\"}\nExpected counts under independence:\n\n&nbsp; | O1 | O2 | total\n---+---+---+---\n**G1** | $\\hat{n}_{11} = \\frac{\\color{red}{n_{1\\cdot}} \\color{black}{\\times} \\color{blue}{n_{\\cdot 1}}}{n}$ | $\\hat{n}_{12} = \\frac{\\color{red}{n_{1\\cdot}} \\color{black}{\\times} \\color{green}{n_{\\cdot 2}}}{n}$ | $\\color{red}{n_{1\\cdot}}$\n**G2** | $\\hat{n}_{21} = \\frac{\\color{orange}{n_{2\\cdot}} \\color{black}{\\times} \\color{blue}{n_{\\cdot 1}}}{n}$ | $\\hat{n}_{22} = \\frac{\\color{orange}{n_{2\\cdot}} \\color{black}{\\times} \\color{green}{n_{\\cdot 2}}}{n}$ | $\\color{orange}{n_{2\\cdot}}$\n**total** | $\\color{blue}{n_{\\cdot 1}}$ | $\\color{green}{n_{\\cdot 2}}$ | $n$\n\n:::\n\n:::\nIdea for a test of independence: \n\n- reject $H_0$ if actual and expected counts differ enough across the table\n- *i.e.*, reject $H_0$ when $n_{ij} - \\hat{n}_{ij}$ is large across $i, j$\n\n## Computing expected counts\n\n::: {.columns}\n\n::: {.column width=\"40%\"}\nActual counts:\n\n&nbsp; | O1 | O2 | total\n---+---+---+---\n**G1** | $n_{11}$ | $n_{12}$ | $\\color{red}{n_{1\\cdot}}$\n**G2** | $n_{21}$ | $n_{22}$ | $\\color{orange}{n_{2\\cdot}}$\n**total** | $\\color{blue}{n_{\\cdot 1}}$ | $\\color{green}{n_{\\cdot 2}}$ | $n$\n:::\n\n::: {.column width=\"60%\"}\nExpected counts under independence:\n\n&nbsp; | O1 | O2 | total\n---+---+---+---\n**G1** | $\\hat{n}_{11} = \\frac{\\color{red}{n_{1\\cdot}} \\color{black}{\\times} \\color{blue}{n_{\\cdot 1}}}{n}$ | $\\hat{n}_{12} = \\frac{\\color{red}{n_{1\\cdot}} \\color{black}{\\times} \\color{green}{n_{\\cdot 2}}}{n}$ | $\\color{red}{n_{1\\cdot}}$\n**G2** | $\\hat{n}_{21} = \\frac{\\color{orange}{n_{2\\cdot}} \\color{black}{\\times} \\color{blue}{n_{\\cdot 1}}}{n}$ | $\\hat{n}_{22} = \\frac{\\color{orange}{n_{2\\cdot}} \\color{black}{\\times} \\color{green}{n_{\\cdot 2}}}{n}$ | $\\color{orange}{n_{2\\cdot}}$\n**total** | $\\color{blue}{n_{\\cdot 1}}$ | $\\color{green}{n_{\\cdot 2}}$ | $n$\n\n:::\n\n:::\n\nFor the asthma example:\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n\n-----------------------------------------\n   &nbsp;     asthma   no asthma   total \n------------ -------- ----------- -------\n **female**     49        781       830  \n\n  **male**      30        769       799  \n\n **total**      79       1550      1629  \n-----------------------------------------\n\nTable: Actual\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n\n-----------------------------------------\n   &nbsp;     asthma   no asthma   total \n------------ -------- ----------- -------\n **female**   40.25      789.7      830  \n\n  **male**    38.75      760.3      799  \n\n **total**      79       1550      1629  \n-----------------------------------------\n\nTable: Expected\n\n\n:::\n:::\n\n\n:::\n\n:::\n\n\n## The chi-square ($\\chi^2$) statistic\n\nA measure of the amount by which actual counts differ from expected counts under independence is the **chi** (pronounced /ˈkaɪ ) **square statistic**:\n\n$$\n\\chi^2 = \\sum_{ij} \\frac{\\left(n_{ij} - \\hat{n}_{ij}\\right)^2}{\\hat{n}_{ij}} \n\\qquad\\left(\\sum_\\text{all cells} \\frac{(\\text{observed} - \\text{expected})^2}{\\text{expected}}\\right)\n$$\n\n::: {.columns}\n\n::: {.column}\nCell-wise calculation:\n\n------------------------------------------------------------------------------\n   &nbsp;     asthma                           no asthma \n------------ -------------------------------- --------------------------------\n **female**   $\\frac{(49 - 40.25)^2}{40.25}$  $\\frac{(781 - 789.7)^2}{789.7}$  \n\n  **male**    $\\frac{(30 - 38.75)^2}{38.75}$  $\\frac{(769 - 760.3)^2}{760.3}$   \n------------------------------------------------------------------------------\n:::\n\n::: {.column}\nResult:\n\n::: {.cell}\n::: {.cell-output-display}\n\n---------------------------------\n   &nbsp;     asthma   no asthma \n------------ -------- -----------\n **female**   1.901     0.09691  \n\n  **male**    1.975     0.1007   \n---------------------------------\n\n\n:::\n:::\n\n:::\n\n:::\n\nChi-square statistic: \n$$\n\\chi^2 \n= 1.9014 + 1.9751 + 0.0969 + 0.1007 \n= 4.0741\n$$\n\n## Sampling distribution for $\\chi^2$\n\n::: {.columns}\n\n::: {.column}\nUnder $H_0$, the $\\chi^2$ statistic has a sampling distribution that can be approximated by a $\\chi^2_1$ model.\n\n- subscript indicates degrees of freedom parameter\n\nThe model assumes no expected counts are too small.\n\n- rule of thumb: at least 10 ($\\hat{n}_{ij} \\geq 10$)\n- consequences: if $\\hat{n}_{ij}$ are too small, the statistic is inflated relative to the model, leading to a higher type I error rate\n:::\n\n::: {.column}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week9-association_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n:::\n\n:::\n\n\n## Computing $p$ values\n\n\n::: {.columns}\n\n::: {.column width=\"60%\"}\n\n$$\n\\begin{cases}\nH_0: &\\text{asthma}\\perp\\text{sex} \\; &(\\text{independence})\\\\\nH_A: &\\neg(\\text{asthma}\\perp\\text{sex}) \\; &(\\text{association})\n\\end{cases}\n$$\n\nTo determine the test outcome, find the $p$-value: \n\n$$\nP(\\chi^2_1 > \\chi^2_\\text{obs}) = P(\\chi^2_1 > 4.074) = 0.0435\n$$\n\nSo if asthma and sex were independent, only 4% of random samples would produce a table that deviates from expected counts by more than what we observed.\n\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week9-association_files/figure-revealjs/unnamed-chunk-8-1.png){width=576}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npchisq(4.074, df = 1, lower.tail = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04354804\n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n\n## Implementation in R\n\nThe R implementation is `chisq.test(...)`.\n\n- input: contingency table\n- no constraints on row/column arrangement\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# construct table and pass to chisq.test\ntable(asthma$sex, asthma$asthma) |> \n  chisq.test(correct = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table(asthma$sex, asthma$asthma)\nX-squared = 4.0741, df = 1, p-value = 0.04355\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n> The data provide moderate evidence that asthma prevalence is associated with sex ($\\chi^2$ = 4.074 on 1 degree of freedom, *p* = 0.0435).\n:::\n\n:::\n\n## Residuals in $\\chi^2$ tests\n\n::: {.columns}\n\n::: {.column}\nThe **residual** for each cell is defined as a standardized difference between the observed and expected count:\n\n$$r_{ij} = \\frac{n_{ij} - \\hat{n}_{ij}}{\\sqrt{\\hat{n}_{ij}}} $$\n\nExamining residuals can indicate the source(s) of an inferred association. \n\n- $r_{ij} > 0$: observation exceeds expectation\n- $r_{ij} < 0$: observation is under expectation\n- large $|r_{ij}|$ explain the association\n\n:::\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# store test result\nrslt <- chisq.test(asthma.tbl, correct = F)\n\n# examine residuals\nrslt$residuals\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n---------------------------------\n   &nbsp;     asthma   no asthma \n------------ -------- -----------\n **female**   1.379     -0.3113  \n\n  **male**    -1.405    0.3173   \n---------------------------------\n\n\n:::\n:::\n\n\nLook for the largest residuals:\n\n> Asthma prevalence is higher-than-expected among women and lower-than-expected among men.\n:::\n\n:::\n\n## Continuity correction\n\nThe $\\chi^2$ test for independence is typically applied with Yates' continuity correction.\n\n::: {.columns}\n\n::: {.column}\nThis consists in using a modified version of the test statistic:\n\n$$\n\\chi^2_\\text{Yates} = \\sum_{ij} \\frac{\\left(|n_{ij} - \\hat{n}_{ij}| - 0.5\\right)^2}{\\hat{n}_{ij}}\n$$\n\n- every other detail of the test is the same\n- doesn't change expected counts\n- residuals are still computed as $\\frac{n_{ij} - \\hat{n}_{ij}}{\\sqrt{\\hat{n}_{ij}}}$\n:::\n\n::: {.column}\nImplementation:\n\n::: {.cell}\n\n```{.r .cell-code}\n# construct table and pass to chisq.test\ntable(asthma$sex, asthma$asthma) |> \n  chisq.test(correct = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  table(asthma$sex, asthma$asthma)\nX-squared = 3.6217, df = 1, p-value = 0.05703\n```\n\n\n:::\n:::\n\n\nNote the larger $p$-value -- this changes the conclusion!\n:::\n\n:::\n\n## Spot any similarities?\n\nCompare the $\\chi^2$ test with inference on the difference in proportions.\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# chi square test\ntable(asthma$sex, asthma$asthma) |> \n  chisq.test(correct = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  table(asthma$sex, asthma$asthma)\nX-squared = 3.6217, df = 1, p-value = 0.05703\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# difference in proportions\ntable(asthma$sex, asthma$asthma) |> \n  prop.test(alternative = 'two.sided', \n            conf.level = 0.95, \n            correct = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  table(asthma$sex, asthma$asthma)\nX-squared = 3.6217, df = 1, p-value = 0.05703\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.0004958005  0.0434742223\nsample estimates:\n    prop 1     prop 2 \n0.05903614 0.03754693 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n- the tests are identical!\n\n- the difference in proportions $\\hat{p}_F - \\hat{p}_M$ is one specific measure of association\n\n- next time we'll learn about other measures, which also have the same inference attached\n\n:::\n\n:::\n\n\n## Extending to $I \\times J$ tables\n\n::: {.columns}\n\n::: {.column}\nFAMuSS data:\n\n::: {.cell}\n::: {.cell-output-display}\n\n------------------------------------------\n     &nbsp;       CC    CT    TT    total \n---------------- ----- ----- ----- -------\n **African Am**   16     6     5     27   \n\n   **Asian**      21    18    16     55   \n\n **Caucasian**    125   216   126    467  \n\n  **Hispanic**     4    10     9     23   \n\n   **Other**       7    11     5     23   \n\n   **total**      173   261   161    595  \n------------------------------------------\n\n\n:::\n:::\n\n:::\n\n::: {.column}\nExpected counts:\n\n::: {.cell}\n::: {.cell-output-display}\n\n------------------------------------------------\n     &nbsp;        CC      CT      TT     total \n---------------- ------- ------- ------- -------\n **African Am**   7.85    11.84   7.31     27   \n\n   **Asian**      15.99   24.13   14.88    55   \n\n **Caucasian**    135.8   204.8   126.4    467  \n\n  **Hispanic**    6.69    10.09   6.22     23   \n\n   **Other**      6.69    10.09   6.22     23   \n\n   **total**       173     261     161     595  \n------------------------------------------------\n\n\n:::\n:::\n\n:::\n\n:::\n\n- expected counts and chi-square statistic are calculated exactly the same way\n- degrees of freedom are now $(I - 1)\\times(J - 1)$\n- appropriate provided all $\\hat{n}_{ij} > 1$ and most (~80%) $\\hat{n}_{ij} \\geq 5$\n\n## Extending to $I\\times J$ tables\n\nIn detail:\n\n---------------------------------------------------------------------------------------------------------------------\n     &nbsp;       CC                                CT                                TT  \n---------------- --------------------------------  --------------------------------  --------------------------------\n **African Am**   $\\frac{(16 - 7.85)^2}{7.85}$     $\\frac{(6 - 11.84)^2}{11.84}$     $\\frac{(5 - 7.306)^2}{7.306}$  \n\n   **Asian**      $\\frac{(21 - 15.99)^2}{15.99}$    $\\frac{(18 - 24.13)^2}{24.13}$    $\\frac{(16 -14.88)^2}{14.88}$  \n\n **Caucasian**    $\\frac{(125 - 135.8)^2}{135.8}$   $\\frac{(216 - 204.9)^2}{204.9}$   $\\frac{(126 - 126.4)^2}{126.4}$ \n\n  **Hispanic**     $\\frac{(4 - 6.687)^2}{6.687}$    $\\frac{(10 - 10.09)^2}{10.09}$     $\\frac{(9 - 6.224)^2}{6.224}$  \n\n   **Other**       $\\frac{(7 - 6.687)^2}{6.687}$    $\\frac{(11 - 10.09)^2}{10.09}$     $\\frac{(5 - 6.224)^2}{6.224}$  \n---------------------------------------------------------------------------------------------------------------------\n\nThen:\n\n$$\\begin{cases} &\\chi^2 = \\sum \\text{all cells above} = 19.4 \\\\\n&P(\\chi^2_{8} > 19.4) = 0.01286 \\end{cases}\n\\quad\\Longrightarrow\\quad \\text{reject hypothesis of no association}$$\n\n## Inference for $I\\times J$ tables in R\n\n::: {.columns}\n\n::: {.column}\nThe implementation is the same as for a $2\\times 2$ table:\n\n::: {.cell}\n\n```{.r .cell-code}\n# construct table and pass to chisq.test\ntable(famuss$race, famuss$actn3.r577x) |>\n  chisq.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table(famuss$race, famuss$actn3.r577x)\nX-squared = 19.4, df = 8, p-value = 0.01286\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n> The data provide evidence of an association between race and genotype ($\\chi^2$ = 19.4 on 8 degrees of freedom, *p = 0.01286*).\n\n:::\n\n:::\n\n*Which genotype/race combinations are contributing most to this inferred association?*\n\n## Residual analysis\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# store result of test; display residuals\nrslt <- chisq.test(tbl)\nrslt$residuals\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n------------------------------------------------\n     &nbsp;         CC         CT         TT    \n---------------- --------- ---------- ----------\n **African Am**    2.909     -1.698    -0.8531  \n\n   **Asian**       1.252     -1.247     0.2897  \n\n **Caucasian**    -0.9254    0.7789    -0.03244 \n\n  **Hispanic**    -1.039    -0.02804    1.113   \n\n   **Other**      0.1209     0.2868    -0.4905  \n------------------------------------------------\n\n\n:::\n:::\n\n\n:::\n\n::: {.column}\nAgain look for the largest absolute residuals to explain inferred association.\n\n> African American and Asian populations have higher CC and lower CT frequencies than would be expected if genotype were independent of race.\n:::\n\n:::\n\n\n",
    "supporting": [
      "week9-association_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}