{
  "hash": "14ed929b9e6bf8fad2ce3fc4447625ca",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simple linear regression\"\nsubtitle: \"Model specification, parameter estimation, inference, and diagnostics\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    mermaid:\n      theme: neutral\nexecute: \n  echo: false\n  warning: false\n  message: false\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n::: {.cell}\n\n:::\n\n\n\n## Today's agenda\n\n1. [lecture] estimation and inference for simple linear regression\n2. course evaluations\n3. final scheduling\n4. [lab] fitting SLR models in R\n\n## PREVEND data\n\n::: {.columns}\n\n::: {.column width=\"70%\"}\nRuff Figural Fluency Test (RFFT) is a cognitive assessment.\n\n- measures nonverbal capacity for initiation, planning, and divergent reasoning\n- scale: 0 (worst) to 175 (best)\n    \n\n:::\n\n::: {.column width=\"30%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n---------------------\n casenr   age   rfft \n-------- ----- ------\n  126     37    136  \n\n   33     36     80  \n\n  145     37    102  \n---------------------\n\n\n:::\n:::\n\n\n:::\n\n::: \n\n::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week10-slr_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n> How much does cognitive ability as measured by RFFT decline with age on average?\n\n:::\n\n:::\n\n## Best-fitting line\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week10-slr_files/figure-revealjs/unnamed-chunk-4-1.png){width=480}\n:::\n:::\n\n:::\n\n::: {.column}\nPreviously you found the best-fitting line:\n\n$$\n\\text{RFFT} = 134.098 - 1.191 \\times \\text{age}\n$$\n\n> With each year of age, RFFT decreases by 1.191 points on average.\n:::\n\n:::\n\n\n\n$$\n\\begin{align}\n\\text{slope}: \n\\quad-1.191 &= \\text{cor}(\\text{age}, \\text{RFFT})\\times\\frac{SD(\\text{RFFT})}{SD(\\text{age})} \n\\\\\n\\text{intercept}:\n\\quad134.098 &= \\text{mean}(\\text{RFFT}) - (-1.191)\\times\\text{mean}(\\text{age})\n\\end{align}\n$$\n\n## Bias and error\n\n::: {.columns}\n\n::: {.column}\nRecall how you found this line:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week10-slr_files/figure-revealjs/unnamed-chunk-5-1.png){width=480}\n:::\n:::\n\n\n:::\n\n::: {.column}\nBias and error are measured via residuals:\n$$\n\\textcolor{red}{e_i} = y_i - \\textcolor{blue}{\\hat{y}_i}\n$$\n\n- $\\text{bias} = -\\frac{1}{n}\\sum_i \\textcolor{red}{e_i}$\n- $\\text{SSE} = \\sum_i \\textcolor{red}{e_i}^2$\n\nWe said that the best-fitting line achieved two conditions:\n\n- **no bias**: underestimates and overestimates equally often\n- **minimal error**: as close as possible to as many data points as possible\n\n:::\n\n:::\n\n\n\n\n\n## The SLR model\n\n::: {.columns}\n\n::: {.column}\nThe simple linear regression model is:\n\n$$\nY \n= \\textcolor{blue}{\\underbrace{\\beta_0 + \\beta_1 x}_\\text{mean}} + \n\\textcolor{red}{\\underbrace{\\epsilon}_\\text{error}}\n$$\n:::\n\n::: {.column}\n- continuous response $Y$\n- explanatory variable $x$\n- regression coefficients $\\beta_0, \\beta_1$\n- model error $\\epsilon$\n:::\n\n:::\n\nThe values that minimize error subject to the model being unbiased are:\n\n$$\\begin{align*}\n\\hat{\\beta}_0 &= \\bar{y} - \\hat{\\beta}_1 \\bar{x} &\\quad(\\text{unbiased}) \\\\\n\\hat{\\beta}_1 &= \\frac{s_y}{s_x}\\times r  &\\quad(\\text{minimizes SSE})\n\\end{align*}$$\n\nThese are called the **least squares estimates**.\n\n\n## Least squares estimates in R\n\nAccording to the model, a one-unit increment in $x$ corresponds to a $\\beta_1$-unit change in mean $Y$:\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit model\nfit <- lm(formula = rfft ~ age, data = prevend)\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rfft ~ age, data = prevend)\n\nCoefficients:\n(Intercept)          age  \n    134.098       -1.191  \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\n> With each additional year of age, mean RFFT score decreases by an estimated 1.191 points.\n\n:::\n\n:::\n\n- `formula = <RESPONSE> ~ <EXPLANATORY>` specifies the model\n- `data = <DATAFRAME>` specifies the observations\n\n## Error variability and model fit\n\nThe residual standard deviation provides an estimate of error variability:\n\n$$\\textcolor{\\red}{\\hat{\\sigma}} = \\sqrt{\\frac{1}{n - 2} \\sum_i e_i^2} \\qquad\\text{(estimated error variability)}$$\n\n::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week10-slr_files/figure-revealjs/unnamed-chunk-7-1.png){width=480}\n:::\n:::\n\n:::\n\n::: {.column width=\"55%\"}\nThe proportion of variability explained by the model is:\n$$\nR^2 = 1 - \\frac{(n - 2)\\textcolor{red}{\\hat{\\sigma}^2}}{(n - 1)\\textcolor{darkgrey}{s_y^2}}\n\\quad\\left(1 - \\frac{\\text{error variability}}{\\text{total variability}}\\right)\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - (n - 2)*sigma(fit)^2/((n - 1)*var(rfft))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4043103\n```\n\n\n:::\n:::\n\n\n> Age explains 40.43% of variability in RFFT.\n:::\n\n:::\n\n## Standard errors for the coefficients\n\nStandard errors for the coefficients are:\n\n$$SE\\left(\\hat{\\beta}_0\\right) = \\hat{\\sigma}\\sqrt{\\frac{1}{n} + \\frac{\\bar{x}^2}{(n - 1)s_x^2}} \\qquad\\text{and}\\qquad\nSE\\left(\\hat{\\beta}_1\\right) = \\hat{\\sigma}\\sqrt{\\frac{1}{(n - 1)s_x^2}}$$\n\nWhile you won't need to know these formulae, do notice that:\n\n- more data $\\longrightarrow$ less sampling variability\n- more spread in $x$ $\\longrightarrow$ less sampling variability\n\n## Inference for the coefficients \n\n::: {.columns}\n\n::: {.column}\nIf the errors are symmetric and unimodal, then the sampling distribution of\n$$\nT = \\frac{\\hat{\\beta}_1 - \\beta_1}{SE(\\beta_1)}\n$$\nis well-approximated by a $t_{n - 2}$ model.\n\n1. Significance test:\n$\\begin{cases} H_0: \\beta_1 = 0 \\\\ H_A: \\beta_1 \\neq 0 \\end{cases}$\n\n2. Confidence interval: \n$\\hat{\\beta}_1 \\pm c\\times SE\\left(\\hat{\\beta}_1\\right)$\n:::\n\n::: {.column}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week10-slr_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=624}\n:::\n:::\n\n\n- $P(T > |T_\\text{obs}|) \\approx 0$: very strong evidence of an association (true slope is not zero)\n- confidence interval using $t_{206}$ critical value: (-1.389, -0.992)\n:::\n\n:::\n\n\n\n## Inference for the PREVEND study\n\n::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(rfft ~ age, data = prevend)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rfft ~ age, data = prevend)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-56.085 -14.690  -2.937  12.744  77.975 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 134.0981     6.0701   22.09   <2e-16 ***\nage          -1.1908     0.1007  -11.82   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.52 on 206 degrees of freedom\nMultiple R-squared:  0.4043,\tAdjusted R-squared:  0.4014 \nF-statistic: 139.8 on 1 and 206 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %      97.5 %\n(Intercept) 122.130647 146.0654574\nage          -1.389341  -0.9922471\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column}\nFitted model:\n$$\n\\text{RFFT} = 134.098 - 1.191 \\times \\text{age}\n$$\n\n\n- Age explains an estimated 40.43% of variation in RFFT.\n\n- With each year of age mean RFFT declines by an estimated 1.19 points (SE 0.10).\n\n- There is a significant association between age and mean RFFT score (*T* = -11.82 on 206 degrees of freedom, *p* < 0.0001). \n\n\n- With 95% confidence, each additional year of age is associated with an estimated decline in mean RFFT between 0.99 and 1.39 points.\n\n:::\n\n:::\n\n## Kleiber's law\n\n[Kleiber's law](https://en.wikipedia.org/wiki/Kleiber%27s_law) refers to the relationship between metabolic rate and body mass.\n\n::: columns\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week10-slr_files/figure-revealjs/unnamed-chunk-11-1.png){width=480}\n:::\n:::\n\n:::\n\n::: {.column width=\"55%\"}\nWe can estimate it via the SLR model: \n$$\n\\log(\\text{metabolism}) = \\beta_0 + \\beta_1 \\log(\\text{mass}) + \\epsilon\n$$ \n\nFitted model:\n$$\n\\log(\\text{metabolism}) = 5.64 + \n0.74 \\times \\log(\\text{mass})\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(log.metab ~ log.mass, data = kleiber)\n```\n:::\n\n\n:::\n:::\n\n## Kleiber's law: inference\n\n::: {.columns}\n\n::: {.column width=\"60%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(log.metab ~ log.mass, data = kleiber)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log.metab ~ log.mass, data = kleiber)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.14216 -0.26466 -0.04889  0.25308  1.37616 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  5.63833    0.04709  119.73   <2e-16 ***\nlog.mass     0.73874    0.01462   50.53   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4572 on 93 degrees of freedom\nMultiple R-squared:  0.9649,\tAdjusted R-squared:  0.9645 \nF-statistic:  2553 on 1 and 93 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](week10-slr_files/figure-revealjs/unnamed-chunk-14-1.png){width=288}\n:::\n:::\n\n\n- $\\hat{\\beta}_0 = 5.638$\n- $\\hat{\\beta}_1 = 0.739$\n- $\\hat{\\sigma} = 0.457$\n\n:::\n\n:::\n\n> There is a significant association between body mass and metabolism (*p* < 0.0001): body mass explains 96.49% of variation in metabolism; with 95% confidence, a unit increment in log mass is associated with an estimated increase in mean log metabolism between 0.7097 and 0.7678, with a point estimate of 0.7387.\n\n## Kleiber's law: model interpretation\n\nExponentiating both sides of the fitted SLR model equation:\n\n$$\n\\underbrace{\\text{metabolism}}_{e^{\\log(\\text{metabolism})}} = \\underbrace{280.99}_{e^{5.64}} \\times \\underbrace{\\text{mass}^{0.74}}_{e^{0.74 \\log(\\text{mass})}}\n$$\n\nSo we've really estimated what's known as a *power law* relationship: $y = ax^b$.\n\n- multiplicative, not additive, relationship\n- doubling $x$ corresponds to changing $y$ by a factor of $2^b$\n\nThe estimate and interval for $\\beta_1$ in the SLR model can be transformed appropriately for a more direct interpretation:\n\n> With 95% confidence, every doubling of body mass is associated with an estimated 63.55-70.26% increase in median metabolism.\n",
    "supporting": [
      "week10-slr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}