{
  "hash": "fa802ad4fc51096a2d5535ab3a92bf8b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 6: Hypothesis testing basics\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  eval: true\n  echo: true\n  message: false\n  warning: false\nformat: html\n---\n\n\nIn class we discussed the $t$ test for the hypotheses:\n\n$$\n\\begin{cases}\nH_0: &\\mu = \\mu_0 \\\\\nH_A: &\\mu \\neq \\mu_0\n\\end{cases}\n$$\n\nThe objective of this lab is to learn to perform the basic calculations involved in this $t$ test \"by hand\" (without the use of the function that we'll apply later):\n\n-   calculating the test statistic $T = \\frac{\\bar{x} - \\mu_0}{SE(\\bar{x})}$\n-   calculating a critical value for a level $\\alpha$ test\n-   calculating a $p$-value\n\nWe'll use the `temps` dataset to illustrate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload('data/temps.RData')\nhead(temps)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  body.temp    sex heart.rate\n1      98.8 female         69\n2      98.6 female         85\n3      98.4   male         68\n4      97.2 female         66\n5      99.5   male         75\n6      97.1   male         82\n```\n\n\n:::\n:::\n\n\n### Checking test assumptions\n\nThe $t$ test only makes sense for unimodal populations; otherwise, the population mean isn't an interpretable parameter. \n\nBeyond that, the test is based on the assumption that either the underlying population distribution is symmetric or the sample size is not too small. \"Too small\" is relative to just how much funny business you see in the distribution of values: more pronounced skewness or outliers means that more data are required for the test to work well.[^1]\n\n[^1]: I usually think in the following terms for the $t$-test:\n\n    -   small: $n \\leq 20$\n    -   modest: $20 < n \\leq 50$\n    -   large: $50 < n$\n\n    Unless I'm in the 'small' regime, I'm not too worried about skew or outliers. In the 'modest' regime, I'm not concerned unless I spot very pronounced skew or outliers. In the 'large' regime, I'm really only concerned about (strong) multimodality. Interestingly, in the latter case, the $t$ test still works for multimodal populations, but the population mean isn't meaningful.\n\nFocusing on the mean body temperature as the parameter of interest, we'll start by checking data summaries of the `body.temp` variable to assess the properties mentioned above: unimodality and subsequently symmetry and presence of outliers. Here, we have 39 observations, which is neither small nor large but modest. So, we don't need to be *too* sensitive unless strong skewness or extreme outliers are present.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract temperature variable\nbodytemp <- temps$body.temp\n\n# location measures\nsummary(bodytemp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  96.40   97.85   98.40   98.41   99.00  100.80 \n```\n\n\n:::\n\n```{.r .cell-code}\n# histogram\nhist(bodytemp, breaks = 10)\n```\n\n::: {.cell-output-display}\n![](lab6-hypothesis_files/figure-html/checking test assumptions-1.png){width=384}\n:::\n:::\n\n\nThe histogram suggests a unimodal population, so conceptually the test is sensible; moreover, there's no indication of strong skewness or outliers, so the test should work just fine. \n\n::: callout-note\n## Your turn 1\n\nCheck the `heart.rate` variable for any skewness or outliers. Assess whether the $t$ test is appropriate, taking account of the sample size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract heartrate variable\n\n# location measures\n\n# histogram\n```\n:::\n\n:::\n\n### Calculating the test statistic\n\nTo test the hypotheses:\n\n$$\n\\begin{cases}\nH_0: &\\mu = \\mu_0 \\\\\nH_A: &\\mu \\neq \\mu_0\n\\end{cases}\n$$ We use the test statistic:\n\n$$\nT = \\frac{\\bar{x} - \\mu_0}{SE(\\bar{x})}\n$$ \n\nIn these expressions, $\\mu_0$ is a placeholder for the hypothesized value of $\\mu$ in any particular problem. To test whether the mean body temperature is 98.6°F, set $\\mu_0 = 98.6$ and follow the formula:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# store sample mean and standard error\nbodytemp.mean <- mean(bodytemp)\nbodytemp.mean.se <- sd(bodytemp)/sqrt(length(bodytemp))\n\n# calculate t statistic\nbodytemp.tstat <- (bodytemp.mean - 98.6)/bodytemp.mean.se\nbodytemp.tstat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.328265\n```\n\n\n:::\n:::\n\n\nNotice that this matches the value obtained in class. The interpretation is:\n\n> If mean body temperature were 98.6°F, the estimation error would be -1.328 standard errors.\n\n::: callout-note\n## Your turn 2\n\nCalculate the test statistic to test the hypothesis that mean heart rate is 75 beats per minute (bpm).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# store sample mean and standard error for heart rate\n\n# calculate t statistic to test whether the mean is 75bpm\n```\n:::\n\n:::\n\n### Critical values\n\nOne way to make a test decision is to determine a threshold $q$ for the absolute value of $T$: \n\n- for any larger $|T| > q$, you'll reject the null hypothesis in favor of the alternative\n- for any smaller value $|T| \\leq q$, you'll fail to reject the null hypothesis in favor of the alternative \n\nThe threshold is chosen to control the error rate $\\alpha$: how often you make the mistake of rejecting $H_0$ when it's true. To do this, we use the $1 - \\frac{\\alpha}{2}$ quantile of the $t_{n - 1}$ model, *i.e.*, the value such that:\n\n$$\nP(T < q) = 1 - \\frac{\\alpha}{2}\n$$\n\nWe use this specific quantile so that $P(|T| > q) = \\alpha$, meaning, if $H_0$ is true, the proportion of samples for which $T$ exceeds the decision threshold -- and thus an error is made -- is $\\alpha$. \n\nSeveral examples follow to help you get the hang of determining the correct inputs to obtain critical values based on controlling the error rate at $\\alpha$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# to control error rate at 10%, use this critical value\nqt(0.95, df = 38)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.685954\n```\n\n\n:::\n\n```{.r .cell-code}\n# to control error rate at 5%, use this critical value\nqt(0.975, df = 38)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.024394\n```\n\n\n:::\n\n```{.r .cell-code}\n# to control error rate at 1%, use this critical value\nqt(0.995, df = 38)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.711558\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Your turn 3\n\nCalculate the critical value you'd use to control error rate at 20%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# to control error rate at 20%, use this critical value\n```\n:::\n\n:::\n\nThe error rate $\\alpha$ is also called a \"significance level\", leading to the following interpretations:\n\n- at the 20% significance level, we reject the null hypothesis $\\mu = 98.6$\n- at the 10% significance level, we fail to reject the null hypothesis $\\mu = 98.6$\n- at the 5% significance level, we fail to reject the null hypothesis $\\mu = 98.6$\n- at the 1% significance level, we fail to reject the null hypothesis $\\mu = 98.6$\n\nYou'll notice that the thresholds get more stringent as the significance level decreases; so we'll reject for every significance level below 10%.\n\nA 5% significance level is conventional. We'd report the test result as follows:\n\n> At the 5% significance level, the data do not provide evidence that mean body temperature differs from 98.6°F.\n\n::: callout-note\n## Your turn 4\n\nTest the hypothesis that mean heart rate is 75 bpm at the 5% significance level and report the test result following the language above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# to control error rate at 5%, use this critical value\n\n# decision whether mean heart rate is 75bpm?\n```\n:::\n\n:::\n\n### $p$-values\n\nA $p$-value quantifies exactly how unusual a particular $T$ statistic is. Technically, it's the proportion $p$ of samples for which $T$ exceeds the observed value; you can also think of it as the *minimum significance level at which the test rejects the null hypothesis*.\n\nTo calculate a $p$-value, we compute:\n\n$$\np = 2\\times P(T > |T_\\text{observed}|)\n$$\n\nIn R, the $p$-value for the test of mean body temperature is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2*pt(abs(bodytemp.tstat), df = 38, lower.tail = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1920133\n```\n\n\n:::\n:::\n\n\nThe interpretation of this quantity:\n\n> If mean body temperature is in fact 98.6°F then 19.2% of samples would produce a $T$ statistic as large or larger than the observed value.\n\n::: callout-note\n## Your turn 5\n\nCompute the $p$-value for the test of whether mean heart rate is 75 bpm. Interpret the value in context.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# p value for test of whether mean heart rate is 75bpm\n```\n:::\n\n:::\n\n### Reporting test results\n\nThe conventional style for reporting a test is to include a statement of the outcome, interpreted in context, with supporting statistics provided parenthetically:\n\n> The data do not provide evidence that the mean body temperature differs from 98.6°F (*T* = -1.328 on 38 degrees of freedom, *p* = 0.192).\n\n::: callout-note\n## Your turn 6\n\nWrite a report of your test of whether mean heart rate is 75bpm following the convention above.\n\n:::\n\n### Practice problems\n\n1.  Use the `nhanes` dataset to test the hypothesis that the average U.S. adult gets 8 hours of sleep per night.\n\n    a.  Produce a histogram of the observations and assess, considering the sample size, whether the $t$ test is appropriate based on its shape and the presence or absence of outliers.\n    b.  Calculate a point estimate and standard error for the mean nightly hours of sleep among U.S. adults.\n    c.  Write the hypotheses to test in notation.\n    d.  Calculate the test statistic, critical value for a 5% significance level test, and $p$-value.\n    e.  Report the test result following the conventional style introduced in class.\n    f. Calculate and interpret a 95% confidence interval for the mean nightly hours of sleep among U.S. adults.\n\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "lab6-hypothesis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}