{
  "hash": "6c4073c97477710c097faa2227e5acce",
  "result": {
    "markdown": "---\ntitle: \"More one-sample tests\"\nsubtitle: \"Reporting test results, understanding error types, and paired tests for differences\"\nformat: \n  revealjs:\n    logo: img/poly-logo-2.jpg\n    footer: \"STAT218\"\n    smaller: true\n    mermaid:\n      theme: neutral\nexecute: \n  echo: false\n  warning: false\n  message: false\n---\n\n\n## Today's agenda\n\n\n::: {.cell}\n\n:::\n\n\n1.  Reading quiz \\[[2pm section](https://forms.office.com/r/gwE5PwNEvd)\\] \\[[4pm section](https://forms.office.com/r/ZjVfgSQP1k)\\]\n2.  More one-sample inference: reporting test results; decision errors\n3.  Comparing two population means via paired differences\n4.  Lab: more $t$-tests in R\n\n## From last time\n\n::: columns\n::: column\n1.  What hypotheses were tested? $$  $$\n\n2.  What was the test statistic and p-value? $$  $$\n\n3.  What was the sample size? $$  $$\n\n4.  What is the conclusion of the test? $$  $$\n\n5.  Interpret the confidence interval.\n:::\n\n::: column\nInference for the body temperature data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(thermometry)\nbody_temps <- thermometry$body.temp\nt.test(body_temps, \n       mu = 98.6, \n       alternative = 'two.sided')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  body_temps\nt = -5.4548, df = 129, p-value = 2.411e-07\nalternative hypothesis: true mean is not equal to 98.6\n95 percent confidence interval:\n 98.12200 98.37646\nsample estimates:\nmean of x \n 98.24923 \n```\n:::\n:::\n\n:::\n:::\n\n\n## Significance conventions\n\n::: {.columns}\n\n::: {.column width=\"43%\"}\n\n**Convention 1:** statistical significance\n\n- $p < 0.05$: reject $H_0$\n- $p \\geq 0.05$: fail to reject $H_0$\n\n> \"The data provide **significant evidence at level $\\alpha$ = 0.05** against the hypothesis that mean body temperature is 98.6 °F in favor of the alternative that mean body temperature differs from 98.6 °F (*T* = -5.4548 on 129 degrees of freedom, *p* = .0000002411).\"\n\n:::\n\n::: {.column width=\"57%\"}\n\n**Convention 2:** weight of evidence against $H_0$\n\n- $p < 0.01$: strong evidence\n- $0.01 \\leq p < 0.05$: moderate evidence\n- $0.05 \\leq p < 0.1$: weak evidence \n- $0.1 \\leq p$: no evidence\n\n> \"The data **provide strong evidence** against the hypothesis that mean body temperature is 98.6 °F in favor of the alternative that mean body temperature differs from 98.6 °F (*T* = -5.4548 on 129 degrees of freedom, *p* = .0000002411).\"\n\n:::\n\n:::\n\nYou may use either convention to interpret test results.\n\n## Choosing alternatives\n\n::: columns\n::: column\n> Is the mean body temp less than 98.6?\n\nWhich test should you use? Consider the interpretations:\n\na.  \\[lower\\] *evidence favoring* lower temp\nb.  \\[upper\\] *no evidence against* lower temp\n\nThe conclusions are consistent but not equivalent -- (a) is a better answer.\n\n**Your alternative should be the claim you hope to support with evidence, and your null the claim you hope to refute.**\n:::\n\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(body_temps, \n       mu = 98.6, \n       alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  body_temps\nt = -5.4548, df = 129, p-value = 1.205e-07\nalternative hypothesis: true mean is less than 98.6\n95 percent confidence interval:\n     -Inf 98.35577\nsample estimates:\nmean of x \n 98.24923 \n```\n:::\n\n```{.r .cell-code}\nt.test(body_temps, \n       mu = 98.6, \n       alternative = 'greater')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  body_temps\nt = -5.4548, df = 129, p-value = 1\nalternative hypothesis: true mean is greater than 98.6\n95 percent confidence interval:\n 98.14269      Inf\nsample estimates:\nmean of x \n 98.24923 \n```\n:::\n:::\n\n:::\n:::\n\n\n## Reporting test results\n\n::: columns\n::: {.column width=\"40%\"}\nTo report the result of a hypothesis test, you should:\n\n1.  Lead with your conclusion\n2. State the hypotheses tested\n3.  Interpret the conclusion of the test in context\n4.  Provide the $T$ statistic, degrees of freedom, and $p$-value\n5.  State and interpret the point estimate and interval for the mean\n:::\n\n::: {.column width=\"60%\"}\n> Our results suggest mean body temperature is less than 98.6 °F. We tested the null hypothesis that mean body temperature is 98.6 °F or greater against the alternative that mean body temperature is less than 98.6 °F. The data provide sufficiently strong evidence against the hypothesis that mean body temperature is 98.6 °F or greater in favor of the alternative that mean body temperature is less than 98.6 °F (*T* = -5.4548 on 129 degrees of freedom, p-value = .0000001205). With 95% confidence, the mean nightly hours of sleep is estimated to be at most 98.36 °F, with a point estimate of 98.23 (*SE* = 0.0643).\n:::\n:::\n\n## Your turn: sleep data\n\nOpen `lab7-moretests` in the class workspace.\n\n::: {.columns}\n\n::: {.column}\n\nWork with your group on just *one* of the questions below. \n\n1. Do US adults sleep 7.5 hours per night on average?\n2. Do US adults sleep less than 7.5 hours per night on average?\n3. Do US adults sleep more than 7.5 hours per night on average?\n4. Do US adults sleep more than 6.5 hours per night on average?\n\n:::\n\n::: {.column}\n\nYour task is to determine and carry out an appropriate test, and then write a complete report of the test outcome:\n    \n- answer the question\n- hypotheses tested\n- test conclusion, interpreted in context\n- test statistic, degrees of freedom, $p$-value\n- confidence interval and point estimate, interpreted in context\n\nThese elements should be summarized together in complete sentences.\n\n:::\n\n:::\n\n## Tests and intervals\n\nNotice that `t.test` produces a confidence interval.\n\n- for the two-sided test, the interval is *exactly* the one we calculated before\n- for the one-sided tests, the interval is a lower/upper confidence bound: \n$$\\begin{align*}\n\\bar{x} - c \\times SE(\\bar{x}) &\\qquad \\text{lower confidence bound} \\quad\\Longleftrightarrow\\quad \\text{upper-sided test}\\\\\n\\bar{x} + c \\times SE(\\bar{x}) &\\qquad \\text{upper confidence bound} \\quad\\Longleftrightarrow\\quad \\text{lower-sided test}\n\\end{align*}$$\nwhere $c$ is chosen to ensure a specified coverage level\n\nThe tests and intervals correspond in the following sense:\n\n> The level $\\alpha$ test rejects just in case the $(1 - \\alpha)$ confidence interval excludes $\\mu_0$ \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# changing confidence level for interval\nt.test(body_temps, mu = 98.6, alternative = 'less', conf.level = 0.99)\n```\n:::\n\n\n## Decision errors\n\n::: {.columns}\n\n::: {.column width=\"40%\"}\nThere are two ways to make a mistake in a hypothesis test:\n\n1. reject a true $H_0$\n2. fail to reject a false $H_0$\n\nThese are known as **type I** and **type II** errors.\n\nBecause rejecting $H_0$ is a stronger conclusion, type I errors are considered more severe.\n\n:::\n\n::: {.column width=\"60%\"}\n\n![](img/testing-errors.png)\n\n> The significance level of a test is a cap on the type I error rate. \n\n:::\n\n:::\n\n\n## Exploring type I error rates\n\nIn `lab7-moretests`, there are codes to draw a sample from a mock population and **test a true null hypothesis**. Run these and take note of your $p$-value.\n\n::: {.columns}\n\n::: {.column}\n\nIn this situation, a type I error is rejecting $H_0$.\n\n- rule: reject if $p < \\alpha$. \n\n- we will tally rejections for various $\\alpha$ values\n\n:::\n\n::: {.column}\n\nSignificance level| Error frequency\n---|---\n$\\alpha = 0.2$ |  \n$\\alpha = 0.1$ | \n$\\alpha = 0.05$ | \n$\\alpha = 0.02$ | \n\n:::\n\n:::\n\n> Takeaway: using larger significance thresholds leads to [more/less] type 1 errors\n\n## Exploring type II errors\n\nNow let's **test a false null hypothesis**. \n\n::: {.columns}\n\n::: {.column}\nA type II error is failing to reject $H_0$.\n\n- rule: $p < 0.05$\n\n- use example commands to test each hypothesis at right\n\n- use a two-sided test\n\n:::\n\n::: {.column}\n\nNull value $\\mu_0$ | Error frequency\n---|---\n4.2 |\n4.6 |\n4.9 |\n5.1 |\n5.4 |\n5.7 |\n\n:::\n\n:::\n\n> Notice that the type II error is quite high for null values near the true mean; this indicates the test has little power to detect such alternatives.\n\n## Swimsuit data\n\nLet's consider our first *two-sample* problem.\n\n> Are swimmers faster in bodysuits than in regular swimsuits?\n\nBelow are the first few observations of the average velocity of competitive swimmers in a 1500m; one measurement was taken in a swimsuit, the other in a bodysuit.\n\n\n::: {.cell}\n::: {.cell-output-display}\n---------------------------------------------------------\n swimmer.number   wet.suit.velocity   swim.suit.velocity \n---------------- ------------------- --------------------\n       1                1.57                 1.49        \n\n       2                1.47                 1.37        \n\n       3                1.42                 1.35        \n---------------------------------------------------------\n:::\n:::\n\n\n*Can you formulate a pair of hypotheses to test to answer this question using methods from last time?*\n\n## Comparing two means\n\nWe can formulate the question as a *comparison of two means*:\n\n$$H_0: \\mu_\\text{bodysuit} \\leq \\mu_\\text{swimsuit}$$ $$H_A: \\mu_\\text{bodysuit} > \\mu_\\text{swimsuit}$$ It is common to express hypotheses of this form in terms of a difference in means: $$H_0: \\underbrace{\\mu_\\text{bodysuit} - \\mu_\\text{swimsuit}}_\\delta \\leq 0$$ $$H_A: \\underbrace{\\mu_\\text{bodysuit} - \\mu_\\text{swimsuit}}_\\delta > 0$$\n\n## Pairing\n\nThe velocities in the swimsuit dataset are paired because every swimmer is measured in both suits.\n\n> Data are **paired** just in case the measurements in each group are taken on exactly the same study units *or* the study units can be placed in one-to-one correspondence.\n\nThis is the easiest situation to handle, because it reduces to a one-sample problem with the observed differences.\n\n## Inference for paired data\n\n1.  Calculate paired differences.\n\n\n::: {.cell}\n::: {.cell-output-display}\n-------------------------------------------------------------------------\n swimmer.number   wet.suit.velocity   swim.suit.velocity   velocity.diff \n---------------- ------------------- -------------------- ---------------\n       1                1.57                 1.49              0.08      \n\n       2                1.47                 1.37               0.1      \n\n       3                1.42                 1.35              0.07      \n-------------------------------------------------------------------------\n:::\n:::\n\n\n::: columns\n::: column\n2.  Perform test as before.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# test for paired difference\nt.test(diffs, mu = 0, alternative = 'greater')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  diffs\nt = 12.318, df = 11, p-value = 4.443e-08\nalternative hypothesis: true mean is greater than 0\n95 percent confidence interval:\n 0.06620114        Inf\nsample estimates:\nmean of x \n   0.0775 \n```\n:::\n:::\n\n:::\n\n::: column\n3.  Report the result of the test. *You try.*\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}