{
  "hash": "9ebe666e1a87b2b83f789d5a5033bf0f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 14: Simple linear regression\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  echo: true\n  eval: true\n  message: false\n  warning: false\n  results: 'markup'\nformat: \n  html:\n    toc: true\n  docx:\n    toc: false\nprefer-html: true\nembed-resources: true\nfig-width: 4\nfig-height: 3\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n\n\nThe objective of this lab is to learn to fit simple linear regression models in R and use/interpret relevant output to construct intervals and perform significance tests on the slope parameter.\n\nSpecifically, the lab covers the following:\n\n- use of `lm` to fit models\n- interpreting the output of `summary.lm`\n- constructing confidence intervals using `confint`\n\nWe'll use three now-familiar datsets: \n\n- `prevend`: cognitive assessment scores and age from the PREVEND study\n- `kleiber`: observations of metabolic rate and body mass among animals\n- `mammals`: observations of brain size and body size among common species of mammal\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload('data/prevend.RData')\nload('data/kleiber.RData')\nload('data/mammals.RData')\n```\n:::\n\n\n\n### Warm-up\n\nConsider constructing a scatterplot using formula-dataframe syntax (rather than vector inputs):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# scatterplot of rfft against age\nplot(rfft ~ age, data = prevend)\n```\n\n::: {.cell-output-display}\n![](lab14-slr_files/figure-docx/scatterplots with formula input-1.png)\n:::\n:::\n\n\nThe formula should specify the response variable on the left-hand side and the explanatory variable on the right-hand side, *e.g.*:\n\n```<RESPONSE> ~ <EXPLANATORY>```\n\nThe variable names that appear in the formula must match exactly variables contained in the dataframe supplied as the `data = ...` argument.\n\n::: callout-note\n## Your turn 1\n\nConstruct a scatterplot of log brain size (response) against log body size (explanatory).\n\n::: {.cell}\n\n```{.r .cell-code}\n# scatterplot of log brain size against log body size\n```\n:::\n:::\n\n### Fitting SLR models\n\nThe general form of a simple linear regression model for a response $y$ in terms of an explanatory varaible $x$ is:\n\n$$\ny = \\beta_0 + \\beta_1 x + \\epsilon\n$$\n\nAbove, the coefficients $\\beta_0, \\beta_1$ are model parameters. Here you'll see how to obtain the 'fitted model' in which estimates are provided for the model parameters:\n\n$$\ny = \\hat{\\beta}_0 + \\hat{\\beta}_1 x\n$$\nNote that the fitted model is written without the error term $\\epsilon$. \n\n#### Computing estimates\n\nSLR models are fitted via the function `lm` in R. The syntax for `lm(...)` -- short for **l**inear **m**odel -- is identical to constructing scatterplots using the formula-dataframe syntax:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# slr model of rfft (response) by age (explanatory)\nfit.rfft <- lm(rfft ~ age, data = prevend)\n```\n:::\n\n\nThe default output shows only the coefficient estimates. Here, the fitted model equation is:\n$$\n\\text{RFFT} = 134.098052187513 + 1.19079380169042\\times\\text{age}\n$$\n\nThe slope parameter on `age` captures the relationship of interest:\n\n> Each year of age is associated with an estimated decrease in mean RFFT score of 1.191.\n\n::: callout-note\n## Your turn 2\n\nFit a simple linear regression model of log brain size with log body size as the explanatory variable. Write the fitted model equation and interpret the coefficient estimate for the slope parameter in context.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# slr model of log brain size by log body size\n```\n:::\n\n\n:::\n\n#### Visualizing a fitted model\n\nThe model is easy to visualize using `abline(...)`, which adds a line to an existing plot. Conveniently, the function has a method for the output of an `lm` call:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# reproduce the scatterplot, then add a line using abline\nplot(rfft ~ age, data = prevend)\nabline(reg = fit.rfft, col = 'blue', lwd = 2)\n```\n\n::: {.cell-output-display}\n![](lab14-slr_files/figure-docx/model visualization-1.png)\n:::\n:::\n\n\nThe additional arguments (color `col` and line width `lwd`) make the line easier to distinguish from the data scatter.\n\n::: callout-note \n## Your turn 3\n\nAdd a line showing the fitted SLR model to your scatterplot from before of log brain size against log body size.\n\n\n\n\n\n\n:::\n\n### Fit summary\n\nThe full set of information about a fitted model -- estimates and standard errors, variance explained, significance tests, and the error variability estimate -- are obtained using the `summary(...)` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# inspect model summary for estimates, inference, and measures of fit\nsummary(fit.rfft)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rfft ~ age, data = prevend)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-56.085 -14.690  -2.937  12.744  77.975 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 134.0981     6.0701   22.09   <2e-16 ***\nage          -1.1908     0.1007  -11.82   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.52 on 206 degrees of freedom\nMultiple R-squared:  0.4043,\tAdjusted R-squared:  0.4014 \nF-statistic: 139.8 on 1 and 206 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nTake a moment to locate the following among the output above:\n\n- age explains 40.43% of total variability in RFFT scores\n- $\\hat{\\beta}_1 = -1.191$\n- $SE\\left(\\hat{\\beta}_1\\right) = 0.1007$\n- $\\hat{\\sigma} = 20.518$\n\nInference for simple linear regression models usually focuses on the slope parameter $\\beta_1$. The $p$-values you see in the coefficient summary table show the results of *partial significance tests*, which are *t* tests of the hypotheses:\n\n$$\n\\begin{cases}\nH_0: &\\beta_j = 0 \\\\\nH_A: &\\beta_j \\neq 0\n\\end{cases}\n$$\nThe partial significance test on the slope parameter is typically interpreted as a test of association, since if the slope is zero then, *e.g.*, age and mean RFFT are unrelated. So the small $p$-value for the slope coefficient indicates:\n\n> The data provide very strong evidence that age is associated with RFFT score (*T* = -11.82 on 206 degrees of freedom, *p* < 0.0001).\n\n::: callout-note\n## Your turn 4\n\nInspect the model summary for your simple linear regression model of log brain and log body size and interpret the inference on the slope parameter in context.\n\n\n\n\n\n\n\n:::\n\n### Confidence intervals\n\nConfidence intervals can be obtained for coefficient estimates using the `confint(...)` function; this takes a fitted `lm` object as input together with a confidence level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 95% confidence intervals\nconfint(object = fit.rfft, level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %      97.5 %\n(Intercept) 122.130647 146.0654574\nage          -1.389341  -0.9922471\n```\n\n\n:::\n\n```{.r .cell-code}\n# 99% confidence intervals\nconfint(object = fit.rfft, level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                0.5 %      99.5 %\n(Intercept) 118.31647 149.8796336\nage          -1.45262  -0.9289675\n```\n\n\n:::\n\n```{.r .cell-code}\n# for slope only...\nconfint(object = fit.rfft, parm = 'age', level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       0.5 %     99.5 %\nage -1.45262 -0.9289675\n```\n\n\n:::\n:::\n\n\n\nThe interpretation is as follows:\n\n> With 99% confidence, each additional year of age is associated with an estimated decrease in mean RFFT score of between 0.929 and 1.453 points.\n\n::: callout-note\n## Your turn 5\n\nCompute a 95% confidence interval for the slope parameter from your SLR model of log brain size. Interpret the interval in context.\n\n\n\n\n\n\n:::\n\n### Practice problem\n\n1. [L10] The `kleiber` dataset contains observations of log-transformed average mass (kg) and log-transformed metabolic rate (kJ/day). Kleiber's law refers to the relationship by which metabolism depends on body mass.\n\n    a. Fit an SLR model of log metabolism (response) against log mass (explanatory). Write the fitted model equation and interpret the coefficient estimate for the slope parameter.\n    b. Construct a scatterplot with a line overlaid to visualize the fitted model.\n    c. Produce the model summary and identify the proportion of variability explained by the model.\n    d. Interpret the partial significance test for the slope parameter.\n    e. Construct a 99% confidence interval for the slope parameter.\n    \n\n\n",
    "supporting": [
      "lab14-slr_files/figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}