{
  "hash": "ee389b80d42a6dfa78fff0c76abca122",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 3: Bivariate summaries\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  warning: false\n  message: false\nformat: \n  html:\n    toc: true\n  docx:\n    toc: false\nprefer-html: true\nembed-resources: true\n---\n\n\nThis lab covers descriptive summaries and graphics for two variables. The goal of the activity is to learn to produce joint summaries of two variables for identifying relationships, in particular:\n\n-   contingency tables\n-   proportional stacked bar plots\n-   scatterplots\n-   side-by-side boxplots\n\nWe will use the FAMuSS dataset again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload('data/famuss.RData')\n```\n:::\n\n\n### Contingency tables\n\n#### Counts\n\nA contingency table is a summary of two categorical variables. Specifically, it is a two-way table in which:\n\n-   rows correspond to the values of one variable\n-   columns correspond to the values of the other variable\n-   entries are counts of the numbers of observations for each combination of values\n\nIn fact, a contingency table is a frequency distribution for *two* variables. It can be constructed in R by retrieving the two variables of interest and providing them as arguments to `table()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# retrieve variables of interest\ngenotype <- famuss$genotype\nsex <- famuss$sex\n\n# make a contingency table\ntable(sex, genotype)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        genotype\nsex       CC  CT  TT\n  Female 106 149  98\n  Male    67 112  63\n```\n\n\n:::\n:::\n\n\nThe order of the arguments determines the row/column orientation of the table.\n\nThe values show the observation counts for each combination, so, for example, the number 106 in the upper-leftmost cell indicates that 106 participants were women with genotype CC.\n\n::: callout-note\n## Your turn\n\nMake a contingency table of race and genotype, with race as the row variable and genotype as the column variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# retrieve variables of interest\n\n# make a contingency table\n```\n:::\n\n:::\n\n#### Proportions\n\nTo convert a contingency table to proportions, one can use either the grand total, row totals, or column totals. The resulting proportions have different meanings:\n\n-   grand total -- combination frequencies\n-   row totals -- column variable frequencies by row variable value\n-   column totals -- row variable frequencies by column variable value\n\nIn the sex/genotype contingency table, these proportions would be computed and interpreted as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# combination frequencies (using grand total as denominator)\ntable(sex, genotype) |> proportions(margin = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        genotype\nsex             CC        CT        TT\n  Female 0.1781513 0.2504202 0.1647059\n  Male   0.1126050 0.1882353 0.1058824\n```\n\n\n:::\n\n```{.r .cell-code}\n# genotype frequencies by sex (using row margins as denominators)\ntable(sex, genotype) |> proportions(margin = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        genotype\nsex             CC        CT        TT\n  Female 0.3002833 0.4220963 0.2776204\n  Male   0.2768595 0.4628099 0.2603306\n```\n\n\n:::\n\n```{.r .cell-code}\n# sex frequencies by genotype (using column margins as denominators)\ntable(sex, genotype) |> proportions(margin = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        genotype\nsex             CC        CT        TT\n  Female 0.6127168 0.5708812 0.6086957\n  Male   0.3872832 0.4291188 0.3913043\n```\n\n\n:::\n:::\n\n\nNotice that the `margin = ...` argument controls which totals are used as denominators in computing proportions. The syntax is:\n\n-   `margin = NULL` specifies grand total\n-   `margin = 1` uses row totals\n-   `margin = 2` uses column totals\n\nThe interpretation of entries depends on which type of proportion is comupted. For instance, looking at only the upper-leftmost entry in each of the three tables above:\n\n-   \\[first table\\] 17.82% of participants were women with genotype CC\n-   \\[second table\\] 30.03% of female participants had genotype CC\n-   \\[third table\\] 61.27% of participants with genotype CC were women\n\nIf you lose track of which margin was which, you can always check yourself by looking at which values sum to one: if all the values add up to one, grand totals were used; if rows sum to one, row totals were used; and if columns add up to one, column totals were used.\n\n::: callout-note\n## Your turn\n\nConvert your contingency table of genotype and race from the previous 'your turn' to a table showing genotype frequencies by race.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# genotype frequencies by race\n```\n:::\n\n\nThen, interpret the entry for Hispanic/CT in context.\n:::\n\n#### Graphics\n\nThe latter two proportion tables -- those constructed using row or column totals -- can be visualized graphically using `barplot(...)`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# stacked bar plot showing genotype frequencies by sex\ntable(genotype, sex) |> \n  proportions(margin = 2) |> \n  barplot(legend = T)\n```\n\n::: {.cell-output-display}\n![](lab3-bivariate_files/figure-html/stacked bar plot using row totals-1.png){width=672}\n:::\n:::\n\n\nThis function is a little finnicky about the table orientation, so the most straightforward way to approach making the plot is to adhere to this rule of thumb:\n\n-   always use `margin = 2`\n-   specify the order of the variables as they are input to `table(...)` so that the grouping variable appears second\n\nSo, for instance, to visualize the sex frequencies by genotype, we would do the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# stacked bar plot showing sex frequencies by genotype\ntable(sex, genotype) |> \n  proportions(margin = 2) |> \n  barplot(legend = T)\n```\n\n::: {.cell-output-display}\n![](lab3-bivariate_files/figure-html/stacked bar plot using column totals-1.png){width=672}\n:::\n:::\n\n\nIf you see uneven bar heights, that means you have not configured the table correctly before passing it to `barplot(...)`.\n\n::: callout-note\n## Your turn\n\nMake a plot showing the genotype frequencies by race.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# stacked bar plot showing genotype frequencies by race\n```\n:::\n\n\nCheck your understanding:\n\n1.  For which group is the CC frequency highest?\n2.  For which group is the CC frequency lowest?\n:::\n\n### Scatterplots and correlation\n\nTaller people tend to be heavier. We should expect a relationship between weight and height. The example below shows a scatterplot of the two variables, and computes the correlation (measure of linear relationship).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# retrieve height and weight columns\nheight <- famuss$height\nweight <- famuss$weight\n\n# basic scatterplot\nplot(height, weight)\n```\n\n::: {.cell-output-display}\n![](lab3-bivariate_files/figure-html/scatterplot and correlation-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# correlation\ncor(weight, height)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5308787\n```\n\n\n:::\n:::\n\n\nA rough rule of thumb for interpreting correlations is as follows:\n\n-   $|r| < 0.3$: no relationship\n-   $0.3 \\leq |r| < 0.6$: weak to moderate relationship\n-   $0.6 \\leq |r| < 1$: moderate to strong relationship\n\nIn this case, the correlation of 0.53 indicates a moderate positive relationship.\n\n::: callout-note\n## Your turn\n\nIs there a relationship between nondominant and dominant percent change in arm strength? Make a scatterplot and compute the correlation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# retrieve the percent change variables\n\n# construct a scatterplot\n\n# compute the correlation\n```\n:::\n\n:::\n\n### Side-by-side boxplots\n\nConsider one of the main questions for the study: *were differences on the ACTN gene region associated with differential change in arm strength after resistance training?*\n\nThis is a comparison between a categorical variable (genotype) and numeric variable (percent change in arm strength). For this type of comparison, a set of side-by-side boxplots is best:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# side-by-side boxplots for non-dominant arm\nboxplot(ndrm.ch ~ genotype, data = famuss)\n```\n\n::: {.cell-output-display}\n![](lab3-bivariate_files/figure-html/num-cat-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# change the orientation \nboxplot(ndrm.ch ~ genotype, data = famuss, horizontal = T)\n```\n\n::: {.cell-output-display}\n![](lab3-bivariate_files/figure-html/num-cat-2.png){width=672}\n:::\n:::\n\n\nThis graphics summarizes the frequency distribution of percent change in non-dominant arm strength *separately for each genotype*. It is essentially a grouped summary.\n\n::: callout-note\n## Your turn\n\nConstruct side-by-side boxplots of percent change in dominant arm strength by genotype.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make side-by-side boxplots of percent change in dominant arm strength by genotype\n```\n:::\n\n:::\n\n### Practice problems\n\n1.  Trait anger is defined as a relatively stable personality trait that is manifested in the frequency, intensity, and duration of feelings associated with anger. It is thought that people with high trait anger might be particularly susceptible to coronary heart disease (CHD); 12,986 participants were recruited for a study examining this hypothesis and followed for five years. The `anger` dataset includes data for the 8557 participants identified as having normal blood pressure (normotensives) and records, for each participant, whether they are classified as having high, moderate, or low trait anger, and whether they experienced a CHD event during the study period.\n\n    a.  Make a contingency table showing trait anger and CHD event occurrence.\n    b.  Find the proportion of participants who experienced a CHD event in each trait anger group.\n    c.  Construct a stacked bar plot to visualize the frequencies you found in (b).\n    d.  Find the ratio $\\frac{\\text{CHD frequency in the high anger group}}{\\text{CHD frequency in the low anger group}}$. This is called the \"relative risk\" of a CHD event. (You can calculate this quantity by hand based on your result in (b).)\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n2.  Use the `nhanes` data from earlier to answer the following questions.\n\n    a.  Make a scatterplot of systolic blood pressure and diastolic blood pressure. Put systolic blood pressure on the y axis. Characterize the association, if any, as positive/negative/non-associated and linear/nonlinear.\n    b.  Compute and interpret the correlation between systolic blood pressure and diastolic blood pressure.\n    c.  Does there appear to be a substantial difference in the distribution of total cholesterol by sex? Construct side-by-side boxplots to answer this question.\n\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "lab3-bivariate_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}