{
  "hash": "3b210fcf4d70e9efbd74b13fd7a0e2b9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 5: Confidence intervals\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  eval: true\n  echo: true\n  message: false\n  warning: false\nformat: \n  html:\n    toc: true\n  docx:\n    toc: false\nprefer-html: true\nembed-resources: true\n---\n\n::: {.cell}\n\n:::\n\n\nThe objective of this lab is to learn to compute confidence intervals for a population mean, and more specifically, to learn to adjust interval coverage by calculating appropriate critical values. Since you already learned to calculate an interval in the last lab, the basic mechanics of the arithmetic are familiar.\n\nWe'll use data from a sample of 100 births in North Carolina in 2004. To change things up a little, the data is stored as a `.csv` file (not an `.RData` file). If you were to download and open this file on your computer, it would likely appear as a spreadsheet (try if you're curious). Read in the data using the command below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in data and preview\nncbirths <- read_csv('data/ncbirths.csv')\nhead(ncbirths)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  mother.age weeks birth.weight sex   \n       <dbl> <dbl>        <dbl> <chr> \n1         36    39         7.69 male  \n2         35    40         8.88 male  \n3         40    40         9    female\n4         37    40         7.94 male  \n5         35    28         1.63 female\n6         25    40         8.75 female\n```\n\n\n:::\n:::\n\n\nRecall that the general formula for an interval is:\n\n$$\n\\bar{x} \\pm c\\times SE(\\bar{x})\n$$\nThroughout this lab, you'll manipulate the coverage by obtaining different values of the critical value $c$. We'll start the back-of-the-envelope approach following the empirical rule.\n\n### Intervals using the empirical rule\n\nThe empirical rule allows us to construct intervals using whole number multiples of the standard error and obtain the following approximate coverages:\n\n- $c = 1$ gives 68% coverage\n- $c = 2$ gives 95% coverage\n- $c = 3$ gives 99.7% coverage\n\nAn approximate 95% confidence interval for the mean birth weight (lbs) in NC in 2004 is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# retrieve variable of interest\nbweight <- ncbirths$birth.weight\n\n# interval ingredients\nbweight.mean <- mean(bweight)\nbweight.sd <- sd(bweight)\nbweight.n <- length(bweight)\n\n# standard error\nbweight.se <- bweight.sd/sqrt(bweight.n)\n\n# 95% interval using empirical rule\nbweight.mean + c(-2, 2)*bweight.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.89267 7.46633\n```\n\n\n:::\n:::\n\n\nFollowing class discussion, we'd interpret this as follows:\n\n> With 95% confidence, the mean birth weight of babies born in North Carolina in 2004 is estimated to be between 6.893 and 7.466 lbs.\n\nTo compute a 68% interval, we need only change the critical value. All of the above remains the same except the last command, which we change to:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 68% interval using empirical rule\nbweight.mean + c(-1, 1)*bweight.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.036085 7.322915\n```\n\n\n:::\n:::\n\n\nNotice that the interval got narrower: a more precise estimate can be given at a reduced coverage rate (which of course means the estimate is wrong more often).\n\n> With 68% confidence, the mean birth weight of babies born in North Carolina in 2004 is estimated to be between 7.036 and 7.323 lbs. \n\n::: callout-note\n## Your turn 1\n\nCalculate and interpret a 99.7% confidence interval for the mean number of weeks at birth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# retrieve variable of interest (no. weeks at birth)\n\n# interval ingredients\n\n# standard error\n\n# 99.7% interval for mean number of weeks at birth using empirical rule\n```\n:::\n\n:::\n\nBecause we're only changing the critical value here, let's save some work and write a simple function to calculate an interval from a vector of values and a critical value. (You don't need to understand the syntax or be able to write functions in R, as this is a programming technique, but it may interest you to see how it can be done.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run this before continuing, but ignore unless interested\nmake_ci <- function(vec, cval){\n  vec.mean <- mean(vec)\n  vec.mean.se <- sd(vec)/sqrt(length(vec) - 1)\n  interval <- vec.mean + c(-1, 1)*cval*vec.mean.se \n  names(interval) <- c('lwr', 'upr')\n  return(interval)\n}\n```\n:::\n\n\nWe can use this function to compute an interval a bit more efficiently. Check that the following give the same intervals as obtained above using fully manual calculations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 95% interval\nmake_ci(bweight, cval = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     lwr      upr \n6.891225 7.467775 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 68% interval\nmake_ci(bweight, cval = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     lwr      upr \n7.035362 7.323638 \n```\n\n\n:::\n:::\n\n\nTry it yourself to get the hang of using this function.\n\n::: callout-note\n## Your turn 2\n\nUse `make_ci(...)` to compute 95% and 99.7% confidence intervals for the mean number of weeks at birth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 99.7% interval for mean number of weeks at birth, using make_ci(...)\n\n# 95% interval for mean number of weeks at birth, using make_ci(...)\n```\n:::\n\n:::\n\n### Intervals using $t$ critical values\n\nIf you want to construct an interval with a coverage other than 68%, 95%, or 99.7%, you'll need to use a different critical value. Instead of a whole number, you'll need the $p$th quantile from the $t_{n-1}$ model where:\n\n$$p = \\left[1 - \\left(\\frac{1 - \\text{coverage}}{2}\\right)\\right]$$\nThis is perhaps a little more complex than it looks. You could probably determine which quantile to use in your head -- the quantile you want is just the midpoint between your coverage level and 1. Consider the following examples:\n\n- for a 95% interval, use $p = 0.975$\n- for an 80% interval, use $p = 0.9$\n- for a 99% interval, use $p = 0.995$\n\n::: callout-note\n## Your turn 3\n\nWhich quantile would you use for...\n\n1. A 96% confidence interval?\n2. An 85% confidence interval?\n3. A 98% confidence interval?\n\n\n::: {.cell}\n\n:::\n\n:::\n\n#### Calculating quantiles\n\nThe `qt(...)` function in R will calculate quantiles for you. It takes two arguments: which quantile you want ($p$) and the degrees of freedom for the $t_{n - 1}$ model. The degrees of freedom is one less than the sample size in this case ($n - 1$). The following commands illustrate the calculation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# for 80% interval from n = 15 observations, use this quantile\nqt(p = 0.9, df = 14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.34503\n```\n\n\n:::\n\n```{.r .cell-code}\n# for a 92% interval from n = 30 observations, use this quantile\nqt(p = 0.96, df = 29)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.814238\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Your turn 4\n\nCalculate $t$ quantiles for the following scenarios:\n\n1. 90% interval from 27 observations\n2. 95% interval from 18 observations\n3. 99% interval from 51 observations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# quantile for a 90% interval from 27 observations\n\n# quantile for a 95% interval from 18 observations\n\n# quantile for a 99% interval from 51 observations\n```\n:::\n\n:::\n\nThese quantiles are the critical values you'd use to construct an interval with the specified coverage and number of observations.\n\n#### Constructing intervals\n\nIf we want a confidence interval for the mean with a specific coverage, first determine which quantile is needed as above and compute it, and then construct the interval as usual using that quantile as the critical value.\n\nFor example, if we want confidence intervals for the mean birth weight:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 98% ci for mean birth weight\ncrit.val <- qt(p = 0.99, df = 99)\nmake_ci(bweight, cval = crit.val)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     lwr      upr \n6.838671 7.520329 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 95% ci for mean birth weight\ncrit.val <- qt(p = 0.975, df = 99)\nmake_ci(bweight, cval = crit.val)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     lwr      upr \n6.893499 7.465501 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 90% ci for mean birth weight\ncrit.val <- qt(p = 0.95, df = 99)\nmake_ci(bweight, cval = crit.val)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     lwr      upr \n6.940175 7.418825 \n```\n\n\n:::\n:::\n\n\nAs a matter of interest, note that the critical value for the 95% interval is 1.9842. Technically, this is the value that provides an interval with 95% coverage; the approximation of 2 provided by the empirical rule is just that -- an approximation.\n\n::: callout-note\n## Your turn 5\n\nConstruct and interpret a 99% confidence interval for the mean number of weeks at birth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 99% ci for mean number of weeks at birth\n```\n:::\n\n:::\n\nNow that you have a sense of the critical value calculation, it's helpful to remind yourself how to make the interval fully from scratch.\n\n::: callout-note\n## Your turn 6\n\nRepeat the previous calculation, but without using the `make_ci(...)` function. You should obtain exactly the same numerical result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## repeat last calculation but fully 'by hand'\n\n# point estimate and standard error\n\n# critical value\n\n# interval\n```\n:::\n\n:::\n\n### Working backwards to determine coverage\n\nNow let's try doing the above backwards. If you're given a confidence interval and you know the summary statistics, you can figure out the interval coverage by solving for the critical value and using the `pt(...)` function. Really, you only need to know the standard error (or sample size and standard deviation) to do this.\n\nFirst, find the margin of error by taking half the interval width.\n\n$$\n\\text{margin of error} = \\frac{\\text{upr} - \\text{lwr}}{2}\n$$\n\nThen, divide by the standard error to solve for the critical value:\n\n$$\nc = \\frac{\\text{margin of error}}{SE(\\bar{x})}\n$$\nLastly, find the coverage as the area of the sampling distribution below the critical value:\n$$\n\\text{coverage} = P(T < c)\n$$\n\nIn R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# example interval for mean birth weight\nbweight.ci <- c(7.030077, 7.328923)\n\n# margin of error (half the width)\nbweight.ci.me <- diff(bweight.ci)/2\n\n# divide out standard error to get critical value\ncrit.val <- bweight.ci.me/bweight.se\n\n# coverage\npt(q = crit.val, df = bweight.n - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.85\n```\n\n\n:::\n:::\n\n\nTake a moment to align the R commands with the calculations shown above and check to make sure you see how this is consistent with the way we formed the interval in the first place. Then try it on your own.\n\n::: callout-note\n## Your turn 7\n\nDetermine the coverage for the interval below for the mean number of weeks at birth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# interval for mean number of weeks at birth\nbweeks.ci <- c(37.79485, 39.30515)\n\n# margin of error (half the width)\n\n# divide out standard error to get critical value\n\n# coverage\n```\n:::\n\n:::",
    "supporting": [
      "lab5-intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}