{
  "hash": "716121904472e4becb2d9b5d22907845",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 13: Odds ratio and relative risk\"\nauthor: \"STAT218\"\nauthor-title: \"Course activity\"\nexecute: \n  echo: true\n  eval: true\n  message: false\n  warning: false\n  results: 'markup'\nformat: \n  html:\n    toc: true\n  docx:\n    toc: false\nprefer-html: true\nembed-resources: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n::: {.cell}\n\n:::\n\n\n\nThis lab has two main objectives:\n\n1. learn to estimate odds ratios and relative risk in R using `epitools`\n2. distinguish which measure of association is most appropriate based on desired interpretation and/or study design\n\nIn addition, you'll get some practice combining inference of association in two-way tables with inference for an appropriate measure of association and interpreting results correctly.\n\nWe'll use the datasets from class, along with a few additional examples.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(epitools)\nload('data/smoking.RData')\nload('data/asthma.RData')\nload('data/chd.RData')\nload('data/outbreak.RData')\nmalaria <- openintro::malaria\n```\n:::\n\n\n\n\n### Odds ratios\n\nIt is worth underscoring at the outset that odds ratios can be estimated for any study design; they are not reserved strictly for case-control studies.\n\nThat said, the `smoking` dataset is an example of a situation in which we can *only* estimate odds ratios, because of the case-control study design: 86 lung cancer patients and 86 controls were sampled separately, and the smoking status of each participant was recorded.\n\nNotice below how adding names when constructing the contingency table adds labels to the row and column dimensions in the output.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# construct table with dimension names group, smoking\nsmoking.tbl <- table(group = smoking$group, smoking = smoking$smoking)\nsmoking.tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         smoking\ngroup     Smokers NonSmokers\n  cancer       83          3\n  control      72         14\n```\n\n\n:::\n:::\n\n\n\nIt is good practice to check whether expected counts are sufficiently large to use the $\\chi^2$ test; if they aren't, then we'll know to use the Fisher's exact $p$-value later.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check whether expected counts are at least ten \nchisq.test(smoking.tbl)$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         smoking\ngroup     Smokers NonSmokers\n  cancer     77.5        8.5\n  control    77.5        8.5\n```\n\n\n:::\n:::\n\n\n\nLast time, we bent the rules a little and went ahead with the $\\chi^2$ test anyway because the counts were close enough to the cutoff. So this time, it'll be interesting to see how much results differ using the exact inference method.\n\nTo compute odds ratios *and* inference for association simultaneously, use the `oddsratio(...)` function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noddsratio(smoking.tbl, rev = 'both', conf.level = 0.95, method = 'wald', correction = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n         smoking\ngroup     NonSmokers Smokers Total\n  control         14      72    86\n  cancer           3      83    86\n  Total           17     155   172\n\n$measure\n         odds ratio with 95% C.I.\ngroup     estimate    lower    upper\n  control  1.00000       NA       NA\n  cancer   5.37963 1.486376 19.47045\n\n$p.value\n         two-sided\ngroup      midp.exact fisher.exact chi.square\n  control          NA           NA         NA\n  cancer  0.005116319  0.008822805 0.01062183\n\n$correction\n[1] TRUE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n```\n\n\n:::\n:::\n\n\n\nThis command has several moving parts:\n\n- `rev` rearranges the table by **rev**ersing rows, columns, or both\n- `conf.level` determines the confidence level of the resulting interval\n- `method` determines how the interval is computed (the version we learned in class is a Wald approximation)\n- `correction` determines whether a continuity correction is applied (always set to `T`)\n\nThe most important argument is `rev`: the contingency table must be arranged so that the outcome of interest is in the second position in the rows/columns. \n\n- if the order of columns were opposite what is shown above, we would get instead an estimate of the odds of cancer among nonsmokers compared with smokers\n- if the order of rows were opposite what is shown above, we would get instead an estimate of the odds of *not* having cancer among smokers compared with nonsmokers\n- if both were opposite what is shown above, we would get instead an estimate of the odds of *not* having cancer among nonsmokers compared with smokers\n\nIt may be a good idea to double-check that the odds ratio you obtained is in fact the right one by doing the calculations by hand and checking the point estimate.\n\n::: callout-note\n## Your turn 1\n\nCompute the odds ratio using direct arithmetic to double-check that the output above gives you the odds ratio you intend.\n\n\n\n::: {.cell}\n\n:::\n\n\n:::\n\nIn this example, the exact $p$-value is fairly close to the $\\chi^2$ test; they would produce different conclusions at the 1% significance level, but not otherwise. Either would be appropriate to use here, but if you prefer to stick to the $\\hat{n} \\geq 10$ rule of thumb strictly, use Fisher's exact test:\n\n> The data provide evidence that smoking is associated with lung cancer (Fisher's exact test, *p* = 0.0088). With 95% confidence, the odds of lung cancer are estimated to be between 1.49 and 19.47 times higher among smokers compared with nonsmokers, with a point estimate of 5.38.\n\n::: callout-note\n## Your turn 2\n\nUsing the `outbreak` data, which comprise data from a case-control study in which 30 cases and 60 controls were sampled and each subject's exposure to raspberries was assessed, perform inference on association using the odds ratio:\n\n1. Check assumptions for the chi square test\n2. Use `oddsratio(...)` to perform calculations for the inference with the odds ratio\n3. Interpret relevant outputs in context\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# construct contingency table\n\n# check assumptions for chi square test\n\n# perform inference with odds ratio\n\n# double-check your point estimate to verify data were arranged in correct orientation\n```\n:::\n\n\n:::\n\n### Relative risk\n\nThe implementation for inference with relative risk is identical to that for inference with odds ratios, but a bit more care is required to orient the contingency table correctly. To obtain the correct relative risk, **it is essential to put the groups in rows and outcomes in columns**. This orientation did not matter for the odds ratio implementation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# put groups in rows and outcome in columns\nasthma.tbl <- table(sex = asthma$sex, asthma = asthma$asthma)\nasthma.tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        asthma\nsex      asthma no asthma\n  female     49       781\n  male       30       769\n```\n\n\n:::\n\n```{.r .cell-code}\n# check assumptions for chi square test\nchisq.test(asthma.tbl)$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        asthma\nsex        asthma no asthma\n  female 40.25169  789.7483\n  male   38.74831  760.2517\n```\n\n\n:::\n:::\n\n\n\nHere, all expected counts are above 10, so when we interpret the output of `riskratio(...)`, we can use the *p*-value from the $\\chi^2$ test.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nriskratio(asthma.tbl, rev = 'both', conf.level = 0.90, method = 'wald', correction = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n        asthma\nsex      no asthma asthma Total\n  male         769     30   799\n  female       781     49   830\n  Total       1550     79  1629\n\n$measure\n        risk ratio with 90% C.I.\nsex      estimate    lower    upper\n  male   1.000000       NA       NA\n  female 1.572329 1.083353 2.282007\n\n$p.value\n        two-sided\nsex      midp.exact fisher.exact chi.square\n  male           NA           NA         NA\n  female 0.04412095   0.04961711 0.05703135\n\n$correction\n[1] TRUE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n```\n\n\n:::\n:::\n\n\n\nHere, the consequences of reversing the order of rows/columns are as follows:\n\n- if rows were arranged opposite of what is shown above, we would obtain the relative risk of asthma among men compared with women (sensible but different)\n- if columns were arranged opposite of what is shown above, we would obtain the relative risk of *not* having asthma among women compared with men (not sensible)\n- if both rows and columns were arranged opposite of what is shown above, we would obtain the relative risk of *not* having asthma amond men compared with women (not sensible)\n\nIn addition, the consequence of orienting the table opposite is:\n\n- if columns and rows were swapped, but the order were the same as shown above, we would obtain an estimate of the relative risk of being a woman among asthmatics compared with non-asthmatics (not sensible) \n\nYou can double check that the risk ratio computed is the one intended by direct arithmetic:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute proportions\nasthma.tbl |> prop.table(margin = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        asthma\nsex          asthma  no asthma\n  female 0.05903614 0.94096386\n  male   0.03754693 0.96245307\n```\n\n\n:::\n\n```{.r .cell-code}\n# risk ratio by hand\n0.05903614/0.03754693\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.572329\n```\n\n\n:::\n:::\n\n\n\nSince assumptions for the $\\chi^2$ test were met, we can combine the inference from this test with the interval estimate for the relative risk:\n\n> The data provide evidence at the 10% significance level of an association between asthma and sex ($\\chi^2$ = 3.62 on 1 degree of freedom, *p* = 0.057). With 90% confidence, the risk of asthma is estimated to be betwen 1.08 and 2.28 times greater for women than for men, with a point estimate of 1.57.\n\n::: callout-note\n## Your turn 3\n\nThe `chd` data contain observations on the incidence of coronary heart disease from a cohort study of 3000 smokers and 5000 nonsmokers.\n\n1. Construct the contingency table with the groups you wish to compare shown in the row dimension and the outcome of interest in the column dimension.\n2. Check assumptions for the $\\chi^2$ test.\n3. Perform inference on association with relative risk at the 1% significance level.\n4. Double-check the relative risk point estimate to make sure you obtained the comparison you intended.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# construct contingency table in proper orientation for inference with relative risk\n\n# check assumptions for chi square test\n\n# carry out inference at 1% significance level\n\n# double check point estimate by manual calculation\n```\n:::\n\n\n\n:::\n\n### Practice problems\n\n1. [L8] For the `diabetes_meds` dataset from last time comparing rates of cardiovascular problems between two diabetes medications among ~200K medicare beneficiaries, determine an appropriate measure of association to add to the inference you performed previously. Provide a narrative interpretation of the result (both the test and estimates) following the style introduced in class.\n\n\n\n\n\n\n\n2. [L8] The Learning Early About Peanut allergy (LEAP) study recruited 530 children with risk factors for developing peanut allergies and randomly allocated peanut exposure and peanut avoidance regimens to each participant. At 5 years of age, an oral food challenge (OFC) test was administered to determine whether participants had developed allergies. Data are contained in the `leap` dataset.\n\n    a. Construct the contingency table for this data.\n    b. Check the assumptions for the $\\chi^2$ test of association.\n    c. Test for association at the 1% significance level and provide point and interval estimates for an appropriate measure of association.\n\n\n\n\n\n\n\n3. [L8] Researchers studying the link between prenatal vitamin use and autism surveyed the mothers of a random sample of children aged 24 - 60 months with autism and seperately surveyed the mothers of a random sample of children with typical development. The `vitamin` dataset contains observations of whether mothers in each group did or did not use prenatal vitamins during the three months before pregnancy (periconceptional period).\n\n    a. Which proportions are possible to estimate? Based on the study design, is it possible to estimate the relative risk of autism?\n    b. Construct the contingency table and check assumptions for the $\\chi^2$ test.\n    c. Test for an association between taking prenatal vitamins and autism at the 1% significance level; include an appropriate meausre of association and provide point and interval estimates.\n    d. Interpret the result in context following the narrative style introduced in class.\n\n\n\n\n",
    "supporting": [
      "lab13-measures_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}