---
title: "Project guidelines"
author: "STAT218"
author-title: "Course"
date: "3/21/24"
published-title: "Due date"
execute: 
  eval: false
  echo: false
  message: false
  warning: false
format: 
  html:
    toc: true
  docx:
    toc: false
prefer-html: true
embed-resources: true
---

In place of a final exam, you will work with a partner to find a case study relevant to one of your major fields of study that employs a method from the class (or a method closely related) to answer a research question. You'll prepare a short summary and meet with me in person during the final exam time to briefly present your case study and field a few questions.

## Expectations

Your case study should meet the following criteria:

- address a research question in your field of study
- use a statistical method we have discussed in class
- be included in a published paper or report (*i.e.*, citeable and not a textbook or anecdotal example)

Although it is not required, it is preferable (and will make your life easier) if the data are published along with the paper or otherwise publicly available. 

Most papers report multiple findings. Thus, you can expect to focus on a small portion of your case study; you do *not* need to summarize the case study in its entirety. You will be expected to identify **one inferential analysis** and prepare a short summary addressing the following items:

1. What is the research question that the analysis addresses?

    + stated in plain language

2. What inference(s) are used to answer the question?
    
    + study population
    + parameter of interest
    + hypotheses, if applicable
    
3. What data were utilized for the inference(s)?

    + sample characteristics
    + number of observations
    + variable(s) measured
    
4. What statistical method(s) are used to perform the inference(s)?

    + type of test, interval estimation, ANOVA, etc.
    
5. What are the results?

    + interpret findings in the context of the research question

Keep it simple in terms of the analysis you summarize -- a few intervals/tests/estimates are fine, but don't overcomplicate things by trying to summarize too many results at once. Keep in mind that you'll need to be able to explain your answers to the above questions in just a few minutes during our meeting. 

## Evaluation criteria

You will be evaluated on the appropriateness of the example you choose, the clarity of your answers to the question above, and your understanding of the statistical method(s) you discuss. Satisfactory work should:

- demonstrate an understanding of the case study and its relevance
- demonstrate an adequate understanding of the data and statistical method(s) involved
- be free of obvious errors/misconceptions

## Deliverables

You should prepare and submit at least 24 hours in advance of the scheduled exam time:

1. a 1-2 page written summary addressing the question above
2. a copy of the paper/report

## Logistics

Exam times are held at:

- 2pm section: Tuesday 3/19 4:10pm -- 7:00pm
- 4pm section: Thursday 3/21 7:10pm -- 10:00pm

You can expect to schedule a 10-minute time slot in the window of the scheduled exam. A scheduling link will be provided at the end of week 10. Requests for alternate times must be made by the end of week 10 and include a motivation for the request. We will be on a tight schedule, so once you have your time slot, you should plan on arriving five minutes in advance.